import { useState } from 'react'
import { BookOpen, Eye, FilePlus2, Globe2, Plus, Sparkles, Trash2, TrendingUp, X } from 'lucide-react'
import useMarketingOpsStore from '@stores/marketingOpsStore'
import useBrandStore from '@stores/brandStore'

const trends=[['女性力量训练持续增长','搜索热度 +18%','高腰支撑与真实训练场景内容更受关注'],['夏季浅色运动服需求上升','相关素材互动率 +12%','增加浅色产品和不透肤测试内容'],['消费者更重视真实测评','UGC 素材 CTR 高 21%','减少棚拍广告占比，强化使用证据']]
const MarketCompetitorPage=()=>{
 const [tab,setTab]=useState('market'),[modal,setModal]=useState(false)
 const competitors=useMarketingOpsStore(s=>s.competitors),add=useMarketingOpsStore(s=>s.addCompetitor),remove=useMarketingOpsStore(s=>s.removeCompetitor),createAction=useMarketingOpsStore(s=>s.createAction),addActivity=useMarketingOpsStore(s=>s.addActivity),addInsightToReport=useMarketingOpsStore(s=>s.addInsightToReport)
 const addKnowledge=useBrandStore(s=>s.addBrandKnowledge)
 const submit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);add({name:d.get('name'),website:d.get('website'),positioning:d.get('positioning')});setModal(false)}
 const saveKnowledge=(title,summary)=>{addKnowledge({title,summary,updateFrequency:'由市场与竞品洞察更新',maintainer:'Luna + 优化师',status:'active'});addActivity({actor:'优化师',action:'保存外部洞察到知识库',object:title,module:'市场与竞品'})}
 const strategy=(target,action)=>createAction({type:'策略建议',source:'市场与竞品',target,before:'外部洞察触发',action,status:'待执行',proposedBy:'Luna',approvedBy:'优化师'})
 return <div className="space-y-5"><section className="flex flex-col gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">市场与竞品</h2><p className="mt-1 text-sm text-neutral-500">外部环境动态分析，结论可进入策略、报告或品牌知识库。</p></div>{tab==='competitor'&&<button onClick={()=>setModal(true)} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={15}/>添加竞品</button>}</section><div className="flex w-fit rounded-xl border bg-white p-1">{[['market','市场洞察'],['competitor','竞品洞察']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab===id?'bg-neutral-900 text-white':'text-neutral-500'}`}>{label}</button>)}</div>
 {tab==='market'?<div className="grid gap-4 lg:grid-cols-3">{trends.map(([title,metric,summary])=><article key={title} className="rounded-2xl border bg-white p-5 shadow-sm"><TrendingUp size={18} className="text-success-600"/><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-lg font-bold text-primary-700">{metric}</p><p className="mt-2 text-sm leading-6 text-neutral-500">{summary}</p><div className="mt-4 flex flex-wrap gap-2 border-t pt-4"><button onClick={()=>strategy(title,summary)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><Sparkles size={13}/>生成策略</button><button className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><FilePlus2 size={13}/>加入报告</button><button onClick={()=>saveKnowledge(title,summary)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><BookOpen size={13}/>保存知识</button></div></article>)}</div>:<div className="grid gap-4 lg:grid-cols-2">{competitors.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary-50 text-primary-600"><Eye size={20}/></span><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-neutral-400 hover:bg-danger-50 hover:text-danger-600"><Trash2 size={15}/></button></div><div className="mt-4 flex items-center gap-2"><h3 className="font-bold">{item.name}</h3><span className="rounded-full bg-warning-50 px-2 py-0.5 text-[10px] text-warning-700">{item.status}</span></div><p className="mt-1 flex items-center gap-1 text-xs text-neutral-400"><Globe2 size={12}/>{item.website}</p><div className="mt-4 rounded-xl bg-neutral-50 p-4 text-sm"><p><span className="text-neutral-400">定位：</span>{item.positioning}</p><p className="mt-2"><span className="text-neutral-400">近期动态：</span>{item.activity}</p><p className="mt-2"><span className="text-neutral-400">渠道：</span>{item.channels.join('、')}</p></div><div className="mt-4 flex gap-2 border-t pt-4"><button onClick={()=>strategy(item.name,`针对 ${item.activity} 制定差异化素材与投放动作`)} className="inline-flex items-center gap-1 rounded-lg bg-neutral-900 px-3 py-2 text-xs text-white"><Sparkles size={13}/>生成应对策略</button><button onClick={()=>saveKnowledge(`${item.name} 竞品动态`,item.activity)} className="rounded-lg border px-3 py-2 text-xs">保存知识</button></div></article>)}</div>}
 {modal&&<div className="fixed inset-0 z-[9998] grid place-items-center bg-neutral-950/40 p-4" onMouseDown={()=>setModal(false)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><header className="flex justify-between border-b p-5"><h3 className="font-bold">添加竞品</h3><button type="button" onClick={()=>setModal(false)}><X size={18}/></button></header><div className="space-y-4 p-5"><label className="block text-sm">竞品名称<input required name="name" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="block text-sm">网站<input name="website" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="block text-sm">定位描述<textarea name="positioning" className="mt-1.5 min-h-24 w-full rounded-lg border px-3 py-2.5"/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button type="button" onClick={()=>setModal(false)} className="rounded-lg border px-4 py-2 text-sm">取消</button><button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">保存竞品</button></footer></form></div>}</div>
}
export default MarketCompetitorPage
