import { Activity, ArrowRight, BrainCircuit, Check, CheckCircle2, Clock3, History, Play, X } from 'lucide-react'
import { useState } from 'react'
import useMarketingOpsStore from '@stores/marketingOpsStore'
import useBrandStore from '@stores/brandStore'
import ActionTracePanel from './ActionTracePanel'

const tabs=[['actions','动作链'],['effects','效果追踪'],['knowledge','候选知识'],['activity','活动记录']]

const OperationsClosurePage=()=>{
 const [tab,setTab]=useState('actions')
 const [verifying,setVerifying]=useState(null)
 const [notice,setNotice]=useState('')
 const actions=useMarketingOpsStore(s=>s.actions)
 const effects=useMarketingOpsStore(s=>s.effectTracks)
 const candidates=useMarketingOpsStore(s=>s.knowledgeCandidates)
 const activities=useMarketingOpsStore(s=>s.activityLog)
 const review=useMarketingOpsStore(s=>s.reviewKnowledgeCandidate)
 const execute=useMarketingOpsStore(s=>s.executeAction)
 const verify=useMarketingOpsStore(s=>s.verifyAction)
 const addBrandKnowledge=useBrandStore(s=>s.addBrandKnowledge)
 const accept=item=>{addBrandKnowledge({title:item.title,summary:item.summary,updateFrequency:'由效果验证持续更新',maintainer:'Luna + 优化师',status:'active',sourceType:'效果验证',sourceActionId:item.actionId,sourceRecommendationId:item.recommendationId});review(item.id,'已采纳');setNotice('候选经验已进入 L4 品牌知识，下一次 Luna 判断会引用它')}
 return <div className="space-y-5"><ActionTracePanel/><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">效果与复盘</h2><p className="mt-1 text-sm text-neutral-500">动作不是终点。验证执行结果，形成品牌经验，并为平台行业能力提供脱敏反馈。</p></section>{notice&&<div className="rounded-xl border border-success-200 bg-success-50 px-4 py-3 text-xs font-semibold text-success-700">{notice}</div>}<div className="flex w-fit max-w-full overflow-x-auto rounded-xl border bg-white p-1">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-semibold ${tab===id?'bg-neutral-900 text-white':'text-neutral-500'}`}>{label}{id==='knowledge'&&<span className="ml-2 rounded-full bg-warning-100 px-1.5 py-0.5 text-[10px] text-warning-700">{candidates.filter(x=>x.status==='待审核').length}</span>}</button>)}</div>
 {tab==='actions'&&<section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="hidden grid-cols-4 border-b bg-neutral-50 px-5 py-3 text-xs font-medium text-neutral-500 md:grid"><span>动作</span><span>来源与决策</span><span>状态</span><span className="text-right">下一步</span></div><div className="divide-y">{actions.map(item=><article key={item.id} className="grid gap-4 p-5 md:grid-cols-4 md:items-center"><div><span className="rounded bg-primary-50 px-2 py-0.5 text-[10px] font-semibold text-primary-700">{item.type}</span><h3 className="mt-2 text-sm font-bold">{item.target}</h3><p className="mt-1 text-xs text-neutral-500">{item.action}</p><p className="mt-1 text-[10px] text-neutral-400">执行前：{item.before}</p></div><div className="text-xs text-neutral-500"><p>{item.source} · {item.proposedBy}</p><p className="mt-1">决策：{item.decision||'采纳'}</p>{item.difference&&<p className="mt-1 text-violet-700">差异：{item.difference}</p>}<p className="mt-1">审批：{item.approvedBy}</p></div><div><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${item.status==='已验证'?'bg-success-50 text-success-700':item.status==='验证中'?'bg-warning-50 text-warning-700':'bg-neutral-100 text-neutral-600'}`}>{item.status==='已验证'?<CheckCircle2 size={13}/>:<Clock3 size={13}/>} {item.status}</span>{item.result&&<p className="mt-2 text-xs text-neutral-500">{item.result}</p>}</div><div className="flex justify-end gap-2">{item.status==='待执行'&&<button onClick={()=>{execute(item.id);setNotice('动作已标记执行，已进入观察窗口')}} className="inline-flex items-center gap-1 rounded-lg bg-neutral-900 px-3 py-2 text-xs text-white"><Play size={13}/>标记已执行</button>}{item.status==='验证中'&&<button onClick={()=>setVerifying(item)} className="rounded-lg bg-success-50 px-3 py-2 text-xs font-semibold text-success-700">填写验证结果</button>}{item.generatedCandidateId&&<button onClick={()=>setTab('knowledge')} className="rounded-lg border px-3 py-2 text-xs">查看候选知识</button>}</div></article>)}</div></section>}
 {tab==='effects'&&<div className="grid gap-4 lg:grid-cols-3">{effects.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><Activity size={18} className="text-primary-600"/><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${item.status==='有效'?'bg-success-50 text-success-700':'bg-warning-50 text-warning-700'}`}>{item.status}</span></div><h3 className="mt-4 text-sm font-bold">{item.action}</h3><div className="mt-4 flex items-center gap-2 rounded-xl bg-neutral-50 p-3 text-xs"><div className="flex-1"><p className="text-neutral-400">执行前</p><p className="mt-1">{item.before}</p></div><ArrowRight size={15}/><div className="flex-1"><p className="text-neutral-400">执行后</p><p className="mt-1">{item.after}</p></div></div><p className="mt-3 text-xs text-neutral-500">{item.window} · {item.owner}</p><p className="mt-2 text-lg font-bold text-success-700">{item.change}</p></article>)}</div>}
 {tab==='knowledge'&&<div className="grid gap-4 md:grid-cols-2">{candidates.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><BrainCircuit size={18} className="text-luna-violet"/><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px]">{item.status}</span></div><h3 className="mt-4 font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{item.summary}</p><div className="mt-3 rounded-xl bg-neutral-50 p-3 text-xs"><p><span className="text-neutral-400">来源：</span>{item.source}</p><p className="mt-1"><span className="text-neutral-400">证据：</span>{item.evidence}</p><p className="mt-1"><span className="text-neutral-400">建议沉淀：</span>{item.targetType}</p></div>{item.status==='待审核'&&<div className="mt-4 flex gap-2 border-t pt-4"><button onClick={()=>accept(item)} className="inline-flex items-center gap-1 rounded-lg bg-neutral-900 px-3 py-2 text-xs text-white"><Check size={13}/>采纳到品牌知识</button><button onClick={()=>review(item.id,'已忽略')} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><X size={13}/>忽略</button></div>}</article>)}</div>}
 {tab==='activity'&&<section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="divide-y">{activities.map(item=><div key={item.id} className="flex gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-neutral-100"><History size={15}/></span><div><p className="text-sm"><strong>{item.actor}</strong> · {item.action}</p><p className="mt-1 text-sm text-neutral-500">{item.object}</p><p className="mt-2 text-xs text-neutral-400">{item.time} · {item.module}</p></div></div>)}</div></section>}
 {verifying&&<VerifyModal item={verifying} onClose={()=>setVerifying(null)} onConfirm={(effect,result)=>{verify(verifying.id,effect,result);setVerifying(null);setNotice('效果已验证，并自动生成一条待审核的品牌候选知识');setTab('knowledge')}}/>}
 </div>
}

const VerifyModal=({item,onClose,onConfirm})=>{const [effect,setEffect]=useState('有效'),[after,setAfter]=useState('ROAS 1.96 · CPA $45.80'),[reason,setReason]=useState('核心指标改善且购买量保持稳定，建议在相同条件下复用');return <div className="fixed inset-0 z-[9999] grid place-items-center bg-neutral-950/50 p-4" onMouseDown={onClose}><div onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><h3 className="font-bold">验证动作效果</h3><p className="mt-1 text-xs text-neutral-500">{item.target} · 观察窗口 {item.verificationWindow}</p><div className="mt-4 grid grid-cols-3 gap-2">{['有效','无效','继续观察'].map(x=><button key={x} onClick={()=>setEffect(x)} className={`rounded-xl border p-3 text-xs font-bold ${effect===x?'border-violet-500 bg-violet-50 text-violet-700':''}`}>{x}</button>)}</div><label className="mt-4 block text-xs font-semibold">执行后指标<input value={after} onChange={e=>setAfter(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label><label className="mt-4 block text-xs font-semibold">验证结论<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-1.5 min-h-24 w-full rounded-xl border px-3 py-2.5"/></label><div className="mt-4 rounded-xl bg-violet-50 p-3 text-xs text-violet-800">确认后会生成品牌候选知识，不会直接修改正式 Skill 或品牌规则。</div><div className="mt-4 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-2.5 text-sm">取消</button><button onClick={()=>onConfirm(effect,`${after}；${reason}`)} className="rounded-xl bg-neutral-950 px-5 py-2.5 text-sm font-bold text-white">确认验证</button></div></div></div>}

export default OperationsClosurePage
