/**
 * Meta Marketing API v25 — AdSet 创建/更新可写字段
 * Reference: https://developers.facebook.com/docs/marketing-api/reference/ad-campaign
 *
 * Phase 2.C：补全 mock 选项 + 完整 SPEC 联动（destination_type / optimization_goal / promoted_object 子字段差异）。
 * Phase 2.K v25 sync：
 *   - 新增 advantage_audience（v23 起新 ad sets 默认开启）
 *   - 新增 targeting_automation composite（v23：age/gender/detailed_targeting suggestion）
 *   - 新增 placement_soft_opt_out（v24，仅 Sales/Leads）
 *   - facebook_positions 选项 video_feeds 标 deprecated（v24 起停用 → 改用 facebook_reels）
 *   - group 重排：targeting → audience；版位字段拆为 placement；预算字段拆为 budget
 */

import {
  COUNTRIES, REGIONS, CITIES, ZIPS,
  META_PIXELS, META_APPS, META_PAGES, META_PRODUCT_SETS, META_IG_ACCOUNTS,
  META_CUSTOM_AUDIENCES, META_LAL_AUDIENCES, META_INTERESTS, META_BEHAVIORS,
  META_CONNECTIONS, META_DEVICE_MODELS,
} from '../services/platformResources';

const channel = 'meta';
const level = 'adset';
const apiVersion = 'meta-v25';

// 把 REGIONS/CITIES/ZIPS（按国家分组）拍平为完整 options（不依 countries 过滤——简化处理）
const ALL_REGION_OPTIONS = Object.values(REGIONS).flat();
const ALL_CITY_OPTIONS = Object.values(CITIES).flat();
const ALL_ZIP_OPTIONS = Object.values(ZIPS).flat();

// 优化目标选项的双层联动 helper：按 [campaign.objective] × [adset.destination_type] 决定可见
const ogVis = (objs, destTypes) => ({
  predicate: (_, root) => {
    const obj = root?.campaign?.objective;
    const dt  = root?.adset?.destination_type;
    const objOk  = !objs || objs.length === 0 || objs.includes(obj);
    // destTypes 为空 = 任何 destination_type；含 null = 允许"未填"
    const dtOk = !destTypes || destTypes.length === 0
      || destTypes.includes(dt)
      || (destTypes.includes('__ANY__') && true);
    return objOk && dtOk;
  },
});

/** @type {import('./schema').FieldDef[]} */
const fields = [
  // ───────────── 基础 ─────────────
  {
    name: 'name',
    label: '广告组名称',
    sdkPath: 'adset.name',
    level, channel, apiVersion,
    type: 'text',
    customRenderer: 'nameTemplate',
    required: true,
    group: 'basic',
    validation: { maxLength: 200 },
  },
  {
    name: 'status',
    label: '初始状态',
    sdkPath: 'adset.status',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'PAUSED', label: '已暂停' },
      { value: 'ACTIVE', label: '已激活' },
    ],
    defaultValue: 'PAUSED',
    excludeFromCreate: true,
  },
  {
    name: 'destination_type',
    label: '转化场景',
    sdkPath: 'adset.destination_type',
    level, channel, apiVersion,
    type: 'select',
    // Phase 2.I：仅 Awareness 之外的目标需要"转化场景"；Awareness 不需要
    requiredWhen: (_, root) => [
      'OUTCOME_TRAFFIC', 'OUTCOME_ENGAGEMENT', 'OUTCOME_LEADS',
      'OUTCOME_APP_PROMOTION', 'OUTCOME_SALES',
    ].includes(root?.campaign?.objective),
    group: 'basic',
    helpText: '广告点击后的目的地类型；它会决定优化目标可选范围与 promoted_object 子字段必填项。',
    options: [
      { value: 'WEBSITE',           label: '网站' },
      { value: 'APP',               label: '应用' },
      { value: 'MESSENGER',         label: 'Messenger 对话' },
      { value: 'INSTAGRAM_DIRECT',  label: 'Instagram Direct' },
      { value: 'WHATSAPP',          label: 'WhatsApp' },
      { value: 'PHONE_CALL',        label: '电话来电' },
      { value: 'INSTANT_FORM',      label: '即时表单' },
      { value: 'SHOP_AUTOMATIC',    label: '商店自动' },
      { value: 'ON_AD',             label: '广告内' },
      { value: 'ON_PAGE',           label: '主页内' },
      { value: 'ON_VIDEO',          label: '视频内' },
      { value: 'FACEBOOK',          label: 'Facebook' },
    ],
  },
  {
    name: 'optimization_goal',
    label: '优化目标',
    sdkPath: 'adset.optimization_goal',
    level, channel, apiVersion,
    type: 'select',
    required: true,
    group: 'basic',
    helpText: '可选范围由「推广目标 × 转化场景」共同决定。',
    options: [
      // Awareness
      { value: 'REACH',                     label: '触达（Reach）',
        dependsOn: ogVis(['OUTCOME_AWARENESS']) },
      { value: 'IMPRESSIONS',               label: '展示量',
        dependsOn: ogVis(['OUTCOME_AWARENESS']) },
      { value: 'AD_RECALL_LIFT',            label: '广告记忆提升',
        dependsOn: ogVis(['OUTCOME_AWARENESS']) },
      { value: 'THRUPLAY',                  label: 'ThruPlay（视频完整观看）',
        dependsOn: ogVis(['OUTCOME_AWARENESS', 'OUTCOME_ENGAGEMENT']) },
      // Traffic
      { value: 'LINK_CLICKS',               label: '链接点击',
        dependsOn: ogVis(['OUTCOME_TRAFFIC', 'OUTCOME_ENGAGEMENT', 'OUTCOME_LEADS']) },
      { value: 'LANDING_PAGE_VIEWS',        label: '落地页浏览',
        dependsOn: { predicate: (_, root) =>
          ['OUTCOME_TRAFFIC', 'OUTCOME_SALES'].includes(root?.campaign?.objective)
          && [undefined, null, 'WEBSITE'].includes(root?.adset?.destination_type) } },
      { value: 'VISIT_INSTAGRAM_PROFILE',   label: 'Instagram 主页访问',
        dependsOn: ogVis(['OUTCOME_TRAFFIC', 'OUTCOME_ENGAGEMENT']) },
      // Engagement
      { value: 'POST_ENGAGEMENT',           label: '帖子互动',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT']) },
      { value: 'PAGE_LIKES',                label: '主页点赞',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT']) },
      { value: 'EVENT_RESPONSES',           label: '活动响应',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT']) },
      { value: 'PROFILE_VISIT',             label: '主页访问',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT']) },
      { value: 'PROFILE_AND_PAGE_ENGAGEMENT', label: '主页与个人资料互动',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT']) },
      { value: 'CONVERSATIONS',             label: '对话开启',
        dependsOn: { predicate: (_, root) =>
          ['OUTCOME_ENGAGEMENT', 'OUTCOME_SALES'].includes(root?.campaign?.objective)
          && ['MESSENGER', 'INSTAGRAM_DIRECT', 'WHATSAPP'].includes(root?.adset?.destination_type) } },
      { value: 'REPLIES',                   label: '回复',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_ENGAGEMENT'
          && ['MESSENGER', 'INSTAGRAM_DIRECT', 'WHATSAPP'].includes(root?.adset?.destination_type) } },
      { value: 'REMINDERS_SET',             label: '设置提醒',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT']) },
      { value: 'SUBSCRIBERS',               label: '订阅',
        dependsOn: ogVis(['OUTCOME_ENGAGEMENT', 'OUTCOME_LEADS']) },
      // Leads
      { value: 'LEAD_GENERATION',           label: '潜在客户生成',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_LEADS'
          && [undefined, null, 'INSTANT_FORM', 'WEBSITE'].includes(root?.adset?.destination_type) } },
      { value: 'QUALITY_LEAD',              label: '高质量潜在客户',
        dependsOn: ogVis(['OUTCOME_LEADS']) },
      { value: 'QUALITY_CALL',              label: '高质量电话',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_LEADS'
          && root?.adset?.destination_type === 'PHONE_CALL' } },
      { value: 'MEANINGFUL_CALL_ATTEMPT',   label: '有意义的来电尝试',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_LEADS'
          && root?.adset?.destination_type === 'PHONE_CALL' } },
      // App Promotion
      { value: 'APP_INSTALLS',              label: '应用安装',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_APP_PROMOTION'
          && [undefined, null, 'APP'].includes(root?.adset?.destination_type) } },
      { value: 'APP_INSTALLS_AND_OFFSITE_CONVERSIONS', label: '应用安装 + 站外转化',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_APP_PROMOTION'
          && root?.adset?.destination_type === 'APP' } },
      { value: 'IN_APP_VALUE',              label: '应用内价值',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_APP_PROMOTION'
          && root?.adset?.destination_type === 'APP' } },
      // Sales
      { value: 'OFFSITE_CONVERSIONS',       label: '站外转化',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_SALES'
          && [undefined, null, 'WEBSITE'].includes(root?.adset?.destination_type) } },
      { value: 'VALUE',                     label: '价值（ROAS）',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_SALES'
          && [undefined, null, 'WEBSITE'].includes(root?.adset?.destination_type) } },
      { value: 'DERIVED_EVENTS',            label: '推导事件',
        dependsOn: ogVis(['OUTCOME_SALES']) },
      { value: 'MESSAGING_PURCHASE_CONVERSION',    label: '消息购买转化',
        dependsOn: { predicate: (_, root) =>
          root?.campaign?.objective === 'OUTCOME_SALES'
          && ['MESSENGER', 'INSTAGRAM_DIRECT', 'WHATSAPP'].includes(root?.adset?.destination_type) } },
      { value: 'MESSAGING_APPOINTMENT_CONVERSION', label: '消息预约转化',
        dependsOn: { predicate: (_, root) =>
          ['OUTCOME_SALES', 'OUTCOME_LEADS'].includes(root?.campaign?.objective)
          && ['MESSENGER', 'INSTAGRAM_DIRECT', 'WHATSAPP'].includes(root?.adset?.destination_type) } },
      { value: 'ADVERTISER_SILOED_VALUE',   label: '广告主独立价值',
        dependsOn: ogVis(['OUTCOME_SALES']) },
      { value: 'ENGAGED_USERS',             label: '活跃用户',
        dependsOn: ogVis(['OUTCOME_AWARENESS', 'OUTCOME_ENGAGEMENT']) },
      { value: 'NONE',                      label: '无' },
    ],
    legacyStateKey: 'adsetGoal',
  },
  {
    name: 'billing_event',
    label: '计费事件',
    sdkPath: 'adset.billing_event',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'IMPRESSIONS',     label: '展示（CPM）' },
      { value: 'LINK_CLICKS',     label: '链接点击（CPC）',
        dependsOn: { field: 'optimization_goal', in: ['LINK_CLICKS', 'LANDING_PAGE_VIEWS'] } },
      { value: 'CLICKS',          label: '所有点击',
        dependsOn: { field: 'optimization_goal', in: ['LINK_CLICKS', 'POST_ENGAGEMENT'] } },
      { value: 'APP_INSTALLS',    label: '应用安装',
        dependsOn: { field: 'optimization_goal', equals: 'APP_INSTALLS' } },
      { value: 'PAGE_LIKES',      label: '主页点赞',
        dependsOn: { field: 'optimization_goal', equals: 'PAGE_LIKES' } },
      { value: 'POST_ENGAGEMENT', label: '帖子互动',
        dependsOn: { field: 'optimization_goal', equals: 'POST_ENGAGEMENT' } },
      { value: 'OFFER_CLAIMS',    label: '优惠领取' },
      { value: 'THRUPLAY',        label: 'ThruPlay',
        dependsOn: { field: 'optimization_goal', equals: 'THRUPLAY' } },
      { value: 'PURCHASE',        label: '购买',
        dependsOn: { field: 'optimization_goal', in: ['OFFSITE_CONVERSIONS', 'VALUE'] } },
      { value: 'LISTING_INTERACTION', label: '商品互动' },
      { value: 'NONE',            label: '无' },
    ],
  },
  {
    name: 'promoted_object',
    label: '推广对象（像素 / 应用 / 主页）',
    sdkPath: 'adset.promoted_object',
    level, channel, apiVersion,
    type: 'composite',
    group: 'basic',
    helpText: '依"转化位置（destination_type）"动态决定子字段必填：网站→pixel+event；应用→application；表单/对话→page。',
    requiredWhen: (_, root) => {
      const dt = root?.adset?.destination_type;
      return ['WEBSITE', 'APP', 'INSTANT_FORM', 'MESSENGER', 'INSTAGRAM_DIRECT', 'WHATSAPP'].includes(dt);
    },
    subFields: [
      { name: 'pixel_id',           label: '像素', sdkPath: 'pixel_id', level, channel, apiVersion,
        type: 'select', options: META_PIXELS,
        helpText: '转化位置=网站时必填。',
        requiredWhen: (_, root) => root?.adset?.destination_type === 'WEBSITE' },
      { name: 'custom_event_type',  label: '标准事件', sdkPath: 'custom_event_type', level, channel, apiVersion,
        type: 'select',
        options: [
          { value: 'PURCHASE',              label: '购买（Purchase）' },
          { value: 'ADD_TO_CART',           label: '加入购物车' },
          { value: 'INITIATE_CHECKOUT',     label: '开始结账' },
          { value: 'LEAD',                  label: '潜在客户' },
          { value: 'COMPLETE_REGISTRATION', label: '完成注册' },
          { value: 'CONTACT',               label: '联系' },
          { value: 'SEARCH',                label: '搜索' },
          { value: 'VIEW_CONTENT',          label: '浏览内容' },
          { value: 'SUBSCRIBE',             label: '订阅' },
          { value: 'CUSTOMIZE_PRODUCT',     label: '定制商品' },
          { value: 'DONATE',                label: '捐赠' },
          { value: 'FIND_LOCATION',         label: '查找位置' },
          { value: 'SCHEDULE',              label: '预约' },
          { value: 'START_TRIAL',           label: '开始试用' },
          { value: 'SUBMIT_APPLICATION',    label: '提交申请' },
          { value: 'ADD_PAYMENT_INFO',      label: '添加支付信息' },
          { value: 'ADD_TO_WISHLIST',       label: '加入愿望单' },
        ],
        helpText: '转化位置=网站时必填。',
        requiredWhen: (_, root) => root?.adset?.destination_type === 'WEBSITE' },
      { name: 'application_id',     label: '应用', sdkPath: 'application_id', level, channel, apiVersion,
        type: 'select', options: META_APPS,
        helpText: '转化位置=应用时由 AppListField 接管；本字段隐藏。',
        hideInUi: true,
        requiredWhen: (_, root) => root?.adset?.destination_type === 'APP' && !(root?.adset?._app_list?.length) },
      { name: 'object_store_url',   label: '应用商店 URL', sdkPath: 'object_store_url', level, channel, apiVersion,
        type: 'url',
        hideInUi: true,
        requiredWhen: (_, root) => root?.adset?.destination_type === 'APP' && !(root?.adset?._app_list?.length) },
      { name: 'page_id',            label: '主页', sdkPath: 'page_id', level, channel, apiVersion,
        type: 'select', options: META_PAGES,
        helpText: '即时表单 / Messenger / IG Direct / WhatsApp 时必填。',
        requiredWhen: (_, root) =>
          ['INSTANT_FORM', 'MESSENGER', 'INSTAGRAM_DIRECT', 'WHATSAPP'].includes(root?.adset?.destination_type) },
      { name: 'product_set_id',     label: '商品集合（DPA）', sdkPath: 'product_set_id', level, channel, apiVersion,
        type: 'select', options: META_PRODUCT_SETS,
        helpText: 'DPA 必填；由产品模块的 catalogCombos 注入，不在 manual core 暴露。',
        hideInUi: true,
        requiredWhen: (_, root) => root?.ad?.ad_format === 'DPA' },
      { name: 'offer_id',           label: '优惠 ID', sdkPath: 'offer_id', level, channel, apiVersion, type: 'text' },
      { name: 'event_id',           label: '活动 ID', sdkPath: 'event_id', level, channel, apiVersion, type: 'text',
        requiredWhen: (_, root) => root?.adset?.optimization_goal === 'EVENT_RESPONSES' },
    ],
    sdkConstantsRef: 'AdSet.Fields.promoted_object',
    legacyStateKey: 'event',
  },

  // ───────────── 出价与预算 ─────────────
  {
    name: 'bid_strategy',
    label: '广告组出价策略',
    sdkPath: 'adset.bid_strategy',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'LOWEST_COST_WITHOUT_CAP',   label: '最大化成果（无上限）' },
      { value: 'LOWEST_COST_WITH_BID_CAP',  label: '出价上限（Bid Cap）' },
      { value: 'COST_CAP',                  label: '成本上限（Cost Cap）' },
      { value: 'LOWEST_COST_WITH_MIN_ROAS', label: 'ROAS 目标' },
    ],
    sdkConstantsRef: 'AdSet.BidStrategy',
  },
  {
    name: 'bid_amount',
    label: '出价金额',
    sdkPath: 'adset.bid_amount',
    level, channel, apiVersion,
    type: 'currency',
    group: 'bidding',
    helpText: '使用 Bid Cap / Cost Cap / ROAS 时必填。CBO 时由系列出价策略决定。',
    dependsOn: { predicate: (_, root) => {
      const strat = root?.adset?.bid_strategy || root?.campaign?.bid_strategy;
      return ['LOWEST_COST_WITH_BID_CAP', 'COST_CAP', 'LOWEST_COST_WITH_MIN_ROAS'].includes(strat);
    } },
    requiredWhen: (_, root) => {
      const strat = root?.adset?.bid_strategy || root?.campaign?.bid_strategy;
      return ['LOWEST_COST_WITH_BID_CAP', 'COST_CAP', 'LOWEST_COST_WITH_MIN_ROAS'].includes(strat);
    },
    legacyStateKey: 'bidAmount',
  },
  {
    name: 'bid_constraints',
    label: '出价约束',
    sdkPath: 'adset.bid_constraints',
    level, channel, apiVersion,
    type: 'json',
    group: 'bidding',
    excludeFromCreate: true,
  },
  // ───────────── 预算 ───────────── (Phase 2.K：从 bidding 拆出)
  {
    name: 'daily_budget',
    label: '广告组日预算（ABO）',
    sdkPath: 'adset.daily_budget',
    level, channel, apiVersion,
    type: 'currency',
    group: 'budget',
    helpText: 'ABO 模式时填写。与 lifetime_budget 二选一。',
    validation: { min: 1 },
    mutuallyExclusiveWith: ['lifetime_budget'],
    legacyStateKey: 'dailyBudget',
  },
  {
    name: 'lifetime_budget',
    label: '广告组总预算',
    sdkPath: 'adset.lifetime_budget',
    level, channel, apiVersion,
    type: 'currency',
    group: 'budget',
    mutuallyExclusiveWith: ['daily_budget'],
  },
  // Phase 2.L：4 个高级花费字段 — Ads Manager UI 不暴露但 API 高阶用户场景需要 → 移到 'advanced' 组
  {
    name: 'daily_min_spend_target',
    label: '日最低花费目标',
    sdkPath: 'adset.daily_min_spend_target',
    level, channel, apiVersion,
    type: 'currency',
    group: 'advanced',
  },
  {
    name: 'daily_spend_cap',
    label: '日花费上限',
    sdkPath: 'adset.daily_spend_cap',
    level, channel, apiVersion,
    type: 'currency',
    group: 'advanced',
  },
  {
    name: 'lifetime_min_spend_target',
    label: '总最低花费目标',
    sdkPath: 'adset.lifetime_min_spend_target',
    level, channel, apiVersion,
    type: 'currency',
    group: 'advanced',
  },
  {
    name: 'lifetime_spend_cap',
    label: '总花费上限',
    sdkPath: 'adset.lifetime_spend_cap',
    level, channel, apiVersion,
    type: 'currency',
    group: 'advanced',
  },
  {
    name: 'pacing_type',
    label: '投放节奏',
    sdkPath: 'adset.pacing_type',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'bidding',
    options: [
      { value: 'standard',    label: '标准' },
      { value: 'day_parting', label: '分时段' },
      { value: 'no_pacing',   label: '无节奏' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'attribution_spec',
    label: '归因窗口',
    sdkPath: 'adset.attribution_spec',
    level, channel, apiVersion,
    type: 'select',
    group: 'tracking',
    options: [
      { value: 'CLICK_7D_VIEW_1D', label: '7 天点击 + 1 天浏览（默认）' },
      { value: 'CLICK_7D_ONLY',    label: '7 天点击' },
      { value: 'CLICK_1D_VIEW_1D', label: '1 天点击 + 1 天浏览' },
      { value: 'CLICK_1D_ONLY',    label: '1 天点击' },
    ],
    helpText: '决定多久之内的点击 / 浏览算作转化（发布时由 expandAttributionPreset 展开为 SDK 数组）。',
  },
  {
    name: 'optimization_sub_event',
    label: '优化子事件',
    sdkPath: 'adset.optimization_sub_event',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'NONE',                 label: '无' },
      { value: 'TRAVEL_INTENT',        label: '旅行意图' },
      { value: 'TRAVEL_INTENT_WEAK',   label: '旅行意图（弱）' },
      { value: 'VIDEO_SOUND_ON',       label: '视频开声' },
    ],
    excludeFromCreate: true,
  },

  // ───────────── 定向 ─────────────
  // Phase 2.M：geo_locations 由 GeoLocationField 合并控件接管（含/排合并）→ schema 字段 hideInUi
  {
    name: 'geo_locations',
    label: '投放地区',
    sdkPath: 'adset.targeting.geo_locations',
    level, channel, apiVersion,
    type: 'composite',
    required: true,
    group: 'audience',
    hideInUi: true,
    helpText: '至少填一个国家。可叠加省/市/邮编/位置类型。',
    subFields: [
      { name: 'countries', label: '国家', sdkPath: 'countries', level, channel, apiVersion,
        type: 'multiselect', options: COUNTRIES },
      { name: 'regions',   label: '州/省', sdkPath: 'regions', level, channel, apiVersion,
        type: 'multiselect', options: ALL_REGION_OPTIONS },
      { name: 'cities',    label: '城市',  sdkPath: 'cities',  level, channel, apiVersion,
        type: 'multiselect', options: ALL_CITY_OPTIONS },
      { name: 'zips',      label: '邮编',  sdkPath: 'zips',    level, channel, apiVersion,
        type: 'multiselect', options: ALL_ZIP_OPTIONS },
      { name: 'location_types', label: '地区类型', sdkPath: 'location_types', level, channel, apiVersion,
        type: 'multiselect',
        options: [
          { value: 'home',       label: '居住地' },
          { value: 'recent',     label: '最近所在地' },
          { value: 'travel_in',  label: '旅行至' },
          { value: 'visitor',    label: '访客' },
        ]},
      { name: 'custom_locations', label: '自定义位置（半径）', sdkPath: 'custom_locations', level, channel, apiVersion,
        type: 'json',
        helpText: '数组：[{ latitude, longitude, radius, distance_unit }]。' },
    ],
    legacyStateKey: 'selectedLocations',
  },
  {
    name: 'excluded_geo_locations',
    label: '排除地区',
    sdkPath: 'adset.targeting.excluded_geo_locations',
    level, channel, apiVersion,
    type: 'composite',
    group: 'audience',
    hideInUi: true,  // Phase 2.M: 由 GeoLocationField 接管
    subFields: [
      { name: 'countries', label: '国家', sdkPath: 'countries', level, channel, apiVersion, type: 'multiselect', options: COUNTRIES },
      { name: 'regions',   label: '州/省', sdkPath: 'regions',   level, channel, apiVersion, type: 'multiselect', options: ALL_REGION_OPTIONS },
      { name: 'cities',    label: '城市', sdkPath: 'cities',    level, channel, apiVersion, type: 'multiselect', options: ALL_CITY_OPTIONS },
      { name: 'zips',      label: '邮编', sdkPath: 'zips',      level, channel, apiVersion, type: 'multiselect', options: ALL_ZIP_OPTIONS },
    ],
  },
  {
    name: 'locales',
    label: '语言',
    sdkPath: 'adset.targeting.locales',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 6,  label: 'English (All)' },
      { value: 24, label: 'English (US)' },
      { value: 5,  label: 'French' },
      { value: 7,  label: 'German' },
      { value: 8,  label: 'Spanish' },
      { value: 9,  label: 'Italian' },
      { value: 10, label: 'Portuguese' },
      { value: 16, label: 'Japanese' },
      { value: 17, label: 'Chinese (Simplified)' },
      { value: 18, label: 'Chinese (Traditional)' },
      { value: 31, label: 'Korean' },
    ],
    legacyStateKey: 'selectedLanguage',
  },
  {
    name: 'age_min',
    label: '最小年龄',
    sdkPath: 'adset.targeting.age_min',
    level, channel, apiVersion,
    type: 'number',
    group: 'audience',
    validation: { min: 13, max: 65 },
    defaultValue: 18,
  },
  {
    name: 'age_max',
    label: '最大年龄',
    sdkPath: 'adset.targeting.age_max',
    level, channel, apiVersion,
    type: 'number',
    group: 'audience',
    validation: {
      min: 13, max: 65,
      custom: (v, root) => {
        const min = root?.adset?.age_min;
        if (typeof v === 'number' && typeof min === 'number' && v < min) {
          return '最大年龄不能小于最小年龄';
        }
        return null;
      },
    },
    defaultValue: 65,
  },
  {
    name: 'genders',
    label: '性别',
    sdkPath: 'adset.targeting.genders',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    helpText: '空数组 = 全部。',
    options: [
      { value: 1, label: '男' },
      { value: 2, label: '女' },
    ],
  },
  {
    name: 'custom_audiences',
    label: '自定义受众（包含）',
    sdkPath: 'adset.targeting.custom_audiences',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [...META_CUSTOM_AUDIENCES, ...META_LAL_AUDIENCES],
    mutuallyExclusiveWith: ['excluded_custom_audiences'],
  },
  {
    name: 'excluded_custom_audiences',
    label: '自定义受众（排除）',
    sdkPath: 'adset.targeting.excluded_custom_audiences',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [...META_CUSTOM_AUDIENCES, ...META_LAL_AUDIENCES],
  },
  {
    name: 'interests',
    label: '兴趣',
    sdkPath: 'adset.targeting.interests',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: META_INTERESTS,
  },
  {
    name: 'behaviors',
    label: '行为',
    sdkPath: 'adset.targeting.behaviors',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: META_BEHAVIORS,
  },
  {
    name: 'family_statuses',
    label: '家庭状态',
    sdkPath: 'adset.targeting.family_statuses',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 1, label: '父母（全部）' }, { value: 2, label: '父母（学龄前）' },
      { value: 3, label: '父母（小学）' }, { value: 4, label: '父母（中学）' },
      { value: 5, label: '已婚' },           { value: 6, label: '订婚' },
    ],
  },
  {
    name: 'life_events',
    label: '人生大事',
    sdkPath: 'adset.targeting.life_events',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 'le_1', label: '即将搬家' },     { value: 'le_2', label: '新工作' },
      { value: 'le_3', label: '新婚' },         { value: 'le_4', label: '即将生日（≤30 天）' },
      { value: 'le_5', label: '订婚（≤6 月）' }, { value: 'le_6', label: '远离家人' },
    ],
  },
  {
    name: 'industries',
    label: '行业',
    sdkPath: 'adset.targeting.industries',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 'ind_1', label: '科技 / IT' }, { value: 'ind_2', label: '金融 / 保险' },
      { value: 'ind_3', label: '医疗 / 制药' }, { value: 'ind_4', label: '教育' },
      { value: 'ind_5', label: '零售 / 电商' }, { value: 'ind_6', label: '媒体 / 广告' },
    ],
  },
  {
    name: 'education_statuses',
    label: '学历',
    sdkPath: 'adset.targeting.education_statuses',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 1, label: '高中' }, { value: 2, label: '本科在读' }, { value: 3, label: '已毕业' },
      { value: 4, label: '高中毕业' }, { value: 5, label: '大学（部分）' }, { value: 6, label: '副学士' },
      { value: 7, label: '研究生在读' }, { value: 8, label: '研究生（部分）' }, { value: 9, label: '硕士' },
      { value: 10, label: '专业学位' }, { value: 11, label: '博士' }, { value: 12, label: '未指定' },
      { value: 13, label: '高中（部分）' },
    ],
  },
  {
    name: 'income',
    label: '收入',
    sdkPath: 'adset.targeting.income',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 'inc_top10', label: '前 10%' }, { value: 'inc_top25', label: '前 11-25%' },
      { value: 'inc_top50', label: '前 26-50%' },
    ],
  },
  {
    name: 'relationship_statuses',
    label: '感情状态',
    sdkPath: 'adset.targeting.relationship_statuses',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 1, label: '单身' }, { value: 2, label: '恋爱中' }, { value: 3, label: '已婚' },
      { value: 4, label: '订婚' }, { value: 6, label: '未指定' }, { value: 11, label: '分居' },
      { value: 12, label: '离婚' }, { value: 13, label: '丧偶' },
    ],
  },
  {
    name: 'connections',
    label: '关联（主页/应用/活动）',
    sdkPath: 'adset.targeting.connections',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: META_CONNECTIONS,
    mutuallyExclusiveWith: ['excluded_connections'],
  },
  {
    name: 'excluded_connections',
    label: '排除关联',
    sdkPath: 'adset.targeting.excluded_connections',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: META_CONNECTIONS,
  },
  {
    name: 'friends_of_connections',
    label: '关联好友',
    sdkPath: 'adset.targeting.friends_of_connections',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: META_CONNECTIONS,
  },
  {
    name: 'targeting_optimization',
    label: '受众扩展（Advantage+）',
    sdkPath: 'adset.targeting.targeting_optimization',
    level, channel, apiVersion,
    type: 'select',
    group: 'audience',
    options: [
      { value: 'none',          label: '关闭' },
      { value: 'expansion_all', label: '开启 Advantage+ 受众扩展' },
    ],
  },
  // Phase 2.K v25：v23 起新 ad sets 默认开启 Advantage+ Audience
  {
    name: 'advantage_audience',
    label: 'Advantage+ 受众',
    sdkPath: 'adset.targeting.advantage_audience',
    level, channel, apiVersion,
    type: 'switch',
    group: 'audience',
    helpText: 'v23+：新广告组默认开启；让 Meta 自动扩展受众范围以提升投放效果。',
    defaultValue: true,
  },
  // Phase 2.K v25：v23 引入 targeting_automation，可让 age/gender/detailed_targeting 作为"建议"
  {
    name: 'targeting_automation',
    label: '受众自动化建议',
    sdkPath: 'adset.targeting.targeting_automation',
    level, channel, apiVersion,
    type: 'composite',
    group: 'audience',
    helpText: 'v23+：把年龄/性别/详细定向变为"建议"——Meta 可在预设范围之外触达更优受众。',
    subFields: [
      { name: 'age',                label: '年龄放宽',   sdkPath: 'age',                level, channel, apiVersion, type: 'switch' },
      { name: 'gender',             label: '性别放宽',   sdkPath: 'gender',             level, channel, apiVersion, type: 'switch' },
      { name: 'detailed_targeting', label: '详细定向放宽', sdkPath: 'detailed_targeting', level, channel, apiVersion, type: 'switch' },
    ],
  },
  {
    name: 'flexible_spec',
    label: '弹性受众组合（Flexible Spec）',
    sdkPath: 'adset.targeting.flexible_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'audience',
    excludeFromCreate: true,
  },
  {
    name: 'exclusions',
    label: '受众排除（Exclusions）',
    sdkPath: 'adset.targeting.exclusions',
    level, channel, apiVersion,
    type: 'json',
    group: 'audience',
    excludeFromCreate: true,
  },

  // 版位
  {
    name: 'publisher_platforms',
    label: '投放渠道',
    sdkPath: 'adset.targeting.publisher_platforms',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'facebook',         label: 'Facebook' },
      { value: 'instagram',        label: 'Instagram' },
      { value: 'audience_network', label: 'Audience Network' },
      { value: 'messenger',        label: 'Messenger' },
    ],
  },
  {
    name: 'facebook_positions',
    label: 'Facebook 版位',
    sdkPath: 'adset.targeting.facebook_positions',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'feed',                  label: '信息流' },
      { value: 'right_hand_column',     label: '右栏' },
      { value: 'marketplace',           label: 'Marketplace' },
      { value: 'video_feeds',           label: '视频信息流（v24 已停用，请改用 Reels）', deprecated: true },
      { value: 'story',                 label: '快拍' },
      { value: 'search',                label: '搜索结果' },
      { value: 'instream_video',        label: '插播视频' },
      { value: 'facebook_reels',        label: 'Reels' },
      { value: 'facebook_reels_overlay',label: 'Reels 叠加' },
    ],
    dependsOn: { field: 'publisher_platforms',
      predicate: (v) => Array.isArray(v) && v.includes('facebook') },
  },
  {
    name: 'instagram_positions',
    label: 'Instagram 版位',
    sdkPath: 'adset.targeting.instagram_positions',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'stream',         label: '信息流' },
      { value: 'story',          label: '快拍' },
      { value: 'explore',        label: '发现' },
      { value: 'explore_home',   label: '发现首页' },
      { value: 'reels',          label: 'Reels' },
      { value: 'shop',           label: 'Shop' },
      { value: 'profile_feed',   label: '主页信息流' },
      { value: 'ig_search',      label: '搜索' },
      { value: 'reels_overlay',  label: 'Reels 叠加' },
    ],
    dependsOn: { field: 'publisher_platforms',
      predicate: (v) => Array.isArray(v) && v.includes('instagram') },
  },
  {
    name: 'audience_network_positions',
    label: 'Audience Network 版位',
    sdkPath: 'adset.targeting.audience_network_positions',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'classic',        label: '原生 / 横幅 / 插屏' },
      { value: 'rewarded_video', label: '激励视频' },
    ],
    dependsOn: { field: 'publisher_platforms',
      predicate: (v) => Array.isArray(v) && v.includes('audience_network') },
  },
  {
    name: 'messenger_positions',
    label: 'Messenger 版位',
    sdkPath: 'adset.targeting.messenger_positions',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'messenger_home',     label: 'Messenger 收件箱' },
      { value: 'story',              label: '快拍' },
      { value: 'sponsored_messages', label: '赞助消息' },
    ],
    dependsOn: { field: 'publisher_platforms',
      predicate: (v) => Array.isArray(v) && v.includes('messenger') },
  },
  {
    name: 'device_platforms',
    label: '设备平台',
    sdkPath: 'adset.targeting.device_platforms',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'mobile',  label: '移动设备' },
      { value: 'desktop', label: '桌面' },
    ],
  },
  {
    name: 'user_os',
    label: '操作系统',
    sdkPath: 'adset.targeting.user_os',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'iOS',           label: 'iOS' },
      { value: 'Android',       label: 'Android' },
      { value: 'Windows Phone', label: 'Windows Phone' },
    ],
  },
  {
    name: 'user_device',
    label: '设备型号',
    sdkPath: 'adset.targeting.user_device',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: META_DEVICE_MODELS,
  },
  {
    name: 'wireless_carrier',
    label: '运营商',
    sdkPath: 'adset.targeting.wireless_carrier',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [{ value: 'wifi', label: '仅 Wi-Fi' }],
  },
  {
    name: 'app_install_state',
    label: '应用安装状态',
    sdkPath: 'adset.targeting.app_install_state',
    level, channel, apiVersion,
    type: 'select',
    group: 'audience',
    options: [
      { value: 'installed',     label: '已安装' },
      { value: 'not_installed', label: '未安装' },
    ],
    dependsOn: { field: 'destination_type', equals: 'APP' },
  },
  {
    name: 'targeting_relaxation_types',
    label: '受众放宽（Lookalike / Custom）',
    sdkPath: 'adset.targeting.targeting_relaxation_types',
    level, channel, apiVersion,
    type: 'json',
    group: 'audience',
    excludeFromCreate: true,
  },
  // Phase 2.K v25：v24 引入，仅 OUTCOME_SALES / OUTCOME_LEADS 时使用
  {
    name: 'placement_soft_opt_out',
    label: '版位软退出（Sales / Leads）',
    sdkPath: 'adset.targeting.placement_soft_opt_out',
    level, channel, apiVersion,
    type: 'json',
    group: 'placement',
    helpText: 'v24+：允许将至多 5% 预算分配到指定版位（仅 Sales / Leads 目标可用）。',
    excludeFromCreate: true,
    dependsOn: { predicate: (_, root) =>
      ['OUTCOME_SALES', 'OUTCOME_LEADS'].includes(root?.campaign?.objective) },
  },
  {
    name: 'brand_safety_content_filter_levels',
    label: '品牌安全过滤等级',
    sdkPath: 'adset.targeting.brand_safety_content_filter_levels',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 'FACEBOOK_STANDARD', label: 'Facebook 标准' },
      { value: 'FACEBOOK_RELAXED',  label: 'Facebook 宽松' },
      { value: 'FACEBOOK_LIMITED',  label: 'Facebook 严格' },
      { value: 'AN_STANDARD',       label: 'AN 标准' },
      { value: 'AN_RELAXED',        label: 'AN 宽松' },
      { value: 'AN_LIMITED',        label: 'AN 严格' },
    ],
  },

  // ───────────── 排期 ─────────────
  {
    name: 'start_time',
    label: '开始时间',
    sdkPath: 'adset.start_time',
    level, channel, apiVersion,
    type: 'datetime',
    group: 'schedule',
    helpText: '使用广告组总预算时必填。',
    requiredWhen: (_, root) => !!root?.adset?.lifetime_budget,
  },
  {
    name: 'end_time',
    label: '结束时间',
    sdkPath: 'adset.end_time',
    level, channel, apiVersion,
    type: 'datetime',
    group: 'schedule',
    helpText: '使用广告组总预算时必填。',
    requiredWhen: (_, root) => !!root?.adset?.lifetime_budget,
  },
  {
    name: 'adset_schedule',
    label: '分时段投放',
    sdkPath: 'adset.adset_schedule',
    level, channel, apiVersion,
    type: 'json',
    group: 'schedule',
    helpText: '数组：[{ start_minute, end_minute, days, timezone_type }]。',
    excludeFromCreate: true,
  },

  // ───────────── 跟踪 ─────────────
  {
    name: 'tracking_specs',
    label: '跟踪规则',
    sdkPath: 'adset.tracking_specs',
    level, channel, apiVersion,
    type: 'json',
    group: 'tracking',
    excludeFromCreate: true,
  },
  {
    name: 'conversion_specs',
    label: '转化规则',
    sdkPath: 'adset.conversion_specs',
    level, channel, apiVersion,
    type: 'json',
    group: 'tracking',
    excludeFromCreate: true,
  },
  {
    name: 'use_new_app_click',
    label: '启用新版应用点击',
    sdkPath: 'adset.use_new_app_click',
    level, channel, apiVersion,
    type: 'switch',
    group: 'tracking',
  },

  // ───────────── 高级 ─────────────
  {
    name: 'frequency_control_specs',
    label: '频次控制规则',
    sdkPath: 'adset.frequency_control_specs',
    level, channel, apiVersion,
    type: 'json',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'is_dynamic_creative',
    label: '启用动态创意',
    sdkPath: 'adset.is_dynamic_creative',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
  },
  {
    name: 'dynamic_creative_optimization_mode',
    label: '动态创意优化模式',
    sdkPath: 'adset.dynamic_creative_optimization_mode',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'OFF',                 label: '关闭' },
      { value: 'PLACEMENT_BASED',     label: '按版位优化' },
      { value: 'CREATIVE_TAG_BASED',  label: '按创意标签优化' },
    ],
    dependsOn: { field: 'is_dynamic_creative', equals: true },
  },
  {
    name: 'is_budget_schedule_enabled',
    label: '启用预算阶段调整',
    sdkPath: 'adset.is_budget_schedule_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'multi_optimization_goal_weight',
    label: '多目标权重偏好',
    sdkPath: 'adset.multi_optimization_goal_weight',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'BALANCED',        label: '平衡' },
      { value: 'PREFER_INSTALL',  label: '偏好安装' },
      { value: 'PREFER_EVENT',    label: '偏好事件' },
      { value: 'UNDEFINED',       label: '未定义' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'existing_customer_budget_percentage',
    label: '老客户预算占比',
    sdkPath: 'adset.existing_customer_budget_percentage',
    level, channel, apiVersion,
    type: 'percent',
    group: 'advanced',
    validation: { min: 0, max: 100 },
    excludeFromCreate: true,
  },
  {
    name: 'campaign_attribution',
    label: '系列归因模式',
    sdkPath: 'adset.campaign_attribution',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'SKAN', label: 'SKAdNetwork 归因' },
      { value: 'AEM',  label: 'AEM 聚合事件衡量' },
    ],
  },
  {
    name: 'execution_options',
    label: '执行选项',
    sdkPath: 'adset.execution_options',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'advanced',
    options: [
      { value: 'validate_only',           label: '仅校验' },
      { value: 'include_recommendations', label: '包含推荐' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'adlabels',
    label: '广告标签',
    sdkPath: 'adset.adlabels',
    level, channel, apiVersion,
    type: 'tags',
    group: 'advanced',
  },

  // ═════════════ Phase 2.L 新增（SDK 验证 — adset.py + targeting.py） ═════════════
  // ── AdSet 顶层 ──
  {
    name: 'dsa_beneficiary',
    label: 'DSA 受益方',
    sdkPath: 'adset.dsa_beneficiary',
    level, channel, apiVersion,
    type: 'text',
    group: 'basic',
    helpText: '欧盟数字服务法（DSA）合规：受益方主体（投放欧盟时必填）。',
  },
  {
    name: 'dsa_payor',
    label: 'DSA 付款方',
    sdkPath: 'adset.dsa_payor',
    level, channel, apiVersion,
    type: 'text',
    group: 'basic',
    helpText: '欧盟数字服务法（DSA）合规：付款方主体（投放欧盟时必填）。',
  },
  {
    name: 'tune_for_category',
    label: '类别校准',
    sdkPath: 'adset.tune_for_category',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    helpText: '与 special_ad_categories 配套，用于校准定向。',
    options: [
      { value: 'NONE',                          label: '无' },
      { value: 'CREDIT',                        label: '信贷' },
      { value: 'EMPLOYMENT',                    label: '就业' },
      { value: 'FINANCIAL_PRODUCTS_SERVICES',   label: '金融产品与服务' },
      { value: 'HOUSING',                       label: '住房' },
      { value: 'ISSUES_ELECTIONS_POLITICS',     label: '社会议题 / 选举 / 政治' },
      { value: 'ONLINE_GAMBLING_AND_GAMING',    label: '在线博彩与游戏' },
    ],
  },
  {
    name: 'value_rule_set_id',
    label: 'Value Optimization 规则集 ID',
    sdkPath: 'adset.value_rule_set_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'bidding',
    helpText: '价值优化规则集 ID（高阶 ROAS 场景）。',
  },
  {
    name: 'instagram_user_id',  // adset 层级
    label: 'Instagram 账户（广告组级）',
    sdkPath: 'adset.instagram_user_id',
    level, channel, apiVersion,
    type: 'select',
    options: META_IG_ACCOUNTS,
    group: 'basic',
    helpText: '广告组级别覆盖 — 通常在 ad.creative 处指定。',
  },
  {
    name: 'targeting_optimization_types',
    label: '定向优化类型（高级）',
    sdkPath: 'adset.targeting_optimization_types',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 'AGE',                  label: '年龄放宽' },
      { value: 'GENDER',               label: '性别放宽' },
      { value: 'DETAILED_TARGETING',   label: '详细定向放宽' },
      { value: 'CUSTOM_AUDIENCE',      label: '自定义受众放宽' },
      { value: 'LOOKALIKE_AUDIENCE',   label: 'Lookalike 受众放宽' },
    ],
    helpText: 'SDK 字段；与 advantage_audience / targeting_automation 配套。',
  },

  // ── Targeting 子字段：device / placement / demographic / custom audience（用户重点要求） ──
  {
    name: 'excluded_user_device',
    label: '排除设备型号',
    sdkPath: 'adset.targeting.excluded_user_device',
    level, channel, apiVersion,
    type: 'multiselect',
    options: META_DEVICE_MODELS,
    group: 'placement',
    helpText: '排除指定设备型号上的投放（与 user_device 互斥但单字段使用）。',
  },
  {
    name: 'excluded_mobile_device_model',
    label: '排除移动设备型号',
    sdkPath: 'adset.targeting.excluded_mobile_device_model',
    level, channel, apiVersion,
    type: 'multiselect',
    options: META_DEVICE_MODELS,
    group: 'placement',
  },
  {
    name: 'threads_positions',
    label: 'Threads 版位',
    sdkPath: 'adset.targeting.threads_positions',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [{ value: 'feed', label: '信息流' }],
    helpText: 'v22+：Threads 应用内版位。',
    dependsOn: { field: 'publisher_platforms',
      predicate: (v) => Array.isArray(v) && v.includes('threads') },
  },
  {
    name: 'whatsapp_positions',
    label: 'WhatsApp 版位',
    sdkPath: 'adset.targeting.whatsapp_positions',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [{ value: 'status', label: 'Status 状态' }],
    helpText: 'v22+：WhatsApp Status 状态版位。',
    dependsOn: { field: 'publisher_platforms',
      predicate: (v) => Array.isArray(v) && v.includes('whatsapp') },
  },
  {
    name: 'excluded_brand_safety_content_types',
    label: '排除品牌安全内容类型',
    sdkPath: 'adset.targeting.excluded_brand_safety_content_types',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'placement',
    options: [
      { value: 'DEBATED_SOCIAL_ISSUES', label: '社会争议话题' },
      { value: 'TRAGEDY_AND_CONFLICT',  label: '悲剧 / 冲突' },
      { value: 'OBJECTIONABLE_ACTIVITY',label: '不当活动' },
      { value: 'SEXUAL_AND_SUGGESTIVE', label: '性暗示' },
      { value: 'PROFANITY_AND_ROUGH_LANGUAGE', label: '脏话 / 粗鲁言语' },
      { value: 'CRIME_AND_HARMFUL_ACTS_TO_SELF_AND_OTHERS', label: '犯罪 / 自伤 / 伤害他人' },
    ],
  },
  {
    name: 'generation',
    label: '世代（Gen）',
    sdkPath: 'adset.targeting.generation',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 'GEN_Z',       label: 'Z 世代（1997-2012）' },
      { value: 'MILLENNIAL',  label: '千禧一代（1981-1996）' },
      { value: 'GEN_X',       label: 'X 世代（1965-1980）' },
      { value: 'BABY_BOOMER', label: '婴儿潮（1946-1964）' },
    ],
  },
  {
    name: 'interested_in',
    label: '兴趣对象',
    sdkPath: 'adset.targeting.interested_in',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'audience',
    options: [
      { value: 1, label: '男性' },
      { value: 2, label: '女性' },
      { value: 3, label: '不限' },
    ],
    helpText: '部分地区 UI 暴露的兴趣对象定向。',
  },
  {
    name: 'dynamic_audience_ids',
    label: '动态受众',
    sdkPath: 'adset.targeting.dynamic_audience_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: META_CUSTOM_AUDIENCES,
    group: 'audience',
    helpText: 'NEW：v23+ 动态受众，由 Meta 实时计算。',
  },
  {
    name: 'excluded_dynamic_audience_ids',
    label: '排除动态受众',
    sdkPath: 'adset.targeting.excluded_dynamic_audience_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: META_CUSTOM_AUDIENCES,
    group: 'audience',
  },

  // ── 长尾 excludeFromCreate 占位（SDK 验证存在，UI 不暴露 / rare） ──
  ...[
    'creative_sequence', 'creative_sequence_repetition_pattern', 'time_based_ad_rotation_intervals',
    'time_based_ad_rotation_id_blocks', 'is_incremental_attribution_enabled', 'attribution_count_type',
    'multi_event_conversion_attribution_window_seconds', 'anchor_event_attribution_window_days',
    'min_budget_spend_percentage', 'max_budget_spend_percentage', 'recurring_budget_semantics',
    'regional_regulated_categories', 'regional_regulation_identities',
    'is_ba_skip_delayed_eligible', 'low_creative_reach', 'learning_stage_info',
    'direct_install_devices', 'install_state_application', 'user_age_unknown',
    'instream_video_skippable_excluded', 'is_whatsapp_destination_ad', 'contextual_targeting_categories',
    'education_schools', 'education_majors', 'college_years',
    'home_ownership', 'home_type', 'home_value', 'household_composition',
    'net_worth', 'political_views', 'politics',
    'office_type', 'work_employers', 'work_positions',
    'keywords', 'engagement_specs', 'excluded_engagement_specs', 'user_event', 'user_adclusters',
    'ethnic_affinity', 'moms',
    'product_audience_specs', 'excluded_product_audience_specs', 'catalog_based_targeting',
    'radius', 'country', 'country_groups',
    'place_page_set_ids', 'prospecting_audience', 'site_category', 'publisher_list_ids',
    'exclude_reached_since', 'alternate_auto_targeting_option', 'fb_deal_id',
  ].map(n => ({
    name: n,
    label: n,
    sdkPath: `adset.${n.startsWith('targeting.') ? n : 'targeting.' + n}`,
    level, channel, apiVersion,
    type: 'json',  // placeholder; UI 不渲染（hideInUi via excludeFromCreate）
    group: 'advanced',
    excludeFromCreate: true,
  })),
];

export default fields;
