/**
 * Meta Marketing API v25 — Ad / AdCreative 创建/更新可写字段
 * Reference: https://developers.facebook.com/docs/marketing-api/reference/adgroup
 *            https://developers.facebook.com/docs/marketing-api/reference/ad-creative
 *
 * Phase 2.C：补 mock 选项（page/ig/video/image/product_set）+ ad_format 联动必填。
 * Phase 2.K v25 sync：
 *   - object_story_spec.subFields[instagram_actor_id] 重命名为 instagram_user_id（v22 起替换）
 *   - enroll_status helpText 更新（v22 起 STANDARD_ENHANCEMENTS bundle 不再支持）
 *   - call_to_action_type group 改为 'cta'（独立分组，与海量 creative 字段拆开）
 */

import {
  META_PAGES, META_IG_ACCOUNTS, META_VIDEOS, META_IMAGES, META_PRODUCT_SETS,
} from '../services/platformResources';

const channel = 'meta';
const level = 'ad';
const apiVersion = 'meta-v25';

// CTA 选项依 campaign.objective 的关联
const ctaForObjective = (vals) => ({ level: 'campaign', field: 'objective', in: vals });

/** @type {import('./schema').FieldDef[]} */
const fields = [
  // ───────────── 基础 ─────────────
  {
    name: 'name',
    label: '广告名称',
    sdkPath: 'ad.name',
    level, channel, apiVersion,
    type: 'text',
    customRenderer: 'nameTemplate',
    required: true,
    group: 'basic',
  },
  {
    name: 'status',
    label: '初始状态',
    sdkPath: 'ad.status',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'PAUSED', label: '已暂停' },
      { value: 'ACTIVE', label: '已激活' },
    ],
    defaultValue: 'PAUSED',
    excludeFromCreate: true,
  },
  {
    name: 'display_sequence',
    label: '展示序列号',
    sdkPath: 'ad.display_sequence',
    level, channel, apiVersion,
    type: 'number',
    group: 'basic',
    excludeFromCreate: true,
  },
  {
    name: 'priority',
    label: '优先级',
    sdkPath: 'ad.priority',
    level, channel, apiVersion,
    type: 'number',
    group: 'basic',
    excludeFromCreate: true,
  },
  {
    name: 'engagement_audience',
    label: '互动受众',
    sdkPath: 'ad.engagement_audience',
    level, channel, apiVersion,
    type: 'switch',
    group: 'basic',
    excludeFromCreate: true,
  },

  // ───────────── 创意 ─────────────
  {
    name: 'ad_format',
    label: '广告形式',
    sdkPath: 'ad.creative.format',
    level, channel, apiVersion,
    type: 'select',
    required: true,
    group: 'creative',
    options: [
      { value: 'SINGLE_IMAGE', label: '单图' },
      { value: 'SINGLE_VIDEO', label: '单视频' },
      { value: 'CAROUSEL',     label: '轮播' },
      { value: 'COLLECTION',   label: '精品栏（Collection）' },
      { value: 'FLEXIBLE',     label: '灵活（多素材）' },
      { value: 'DPA',          label: '动态产品广告（DPA）' },
    ],
    legacyStateKey: 'adType',
  },
  {
    name: 'creative_id',
    label: '已有创意 ID',
    sdkPath: 'ad.creative.creative_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    helpText: '复用现有创意。与 object_story_spec 互斥。',
    mutuallyExclusiveWith: ['object_story_spec'],
  },
  {
    name: 'object_story_spec',
    label: '创意素材规格',
    sdkPath: 'ad.creative.object_story_spec',
    level, channel, apiVersion,
    type: 'composite',
    group: 'creative',
    helpText: '新建创意的核心结构。与 creative_id 互斥。CAROUSEL 时通过 link_data.child_attachments[] 配置。',
    mutuallyExclusiveWith: ['creative_id'],
    // Phase 2.I：CAROUSEL（轮播）时若未复用 creative_id，则 object_story_spec 必填（child_attachments 在内部）
    requiredWhen: (_, root) => root?.ad?.ad_format === 'CAROUSEL' && !root?.ad?.creative_id,
    subFields: [
      { name: 'page_id',            label: 'Facebook 主页', sdkPath: 'page_id',            level, channel, apiVersion,
        type: 'select', options: META_PAGES, required: true },
      // Phase 2.K v25 (v22+ rename): instagram_actor_id → instagram_user_id
      { name: 'instagram_user_id', label: 'Instagram 账户', sdkPath: 'instagram_user_id', level, channel, apiVersion,
        type: 'select', options: META_IG_ACCOUNTS },
      // Phase 2.L: 5 个 JSON 子字段 hideInUi —— 用户通过顶层 title/body/link_url/image_hash/video_id 编辑（publish 层组装）
      { name: 'link_data',          label: '链接广告数据',     sdkPath: 'link_data',          level, channel, apiVersion, type: 'json',
        helpText: '{ link, message, name, description, call_to_action, image_hash, child_attachments[] }。',
        hideInUi: true },
      { name: 'video_data',         label: '视频广告数据',     sdkPath: 'video_data',         level, channel, apiVersion, type: 'json',
        helpText: '{ video_id, image_url, title, message, call_to_action }。',
        hideInUi: true },
      { name: 'photo_data',         label: '图片广告数据',     sdkPath: 'photo_data',         level, channel, apiVersion, type: 'json',
        hideInUi: true },
      { name: 'template_data',      label: '模板广告数据',     sdkPath: 'template_data',      level, channel, apiVersion, type: 'json',
        hideInUi: true },
      { name: 'text_data',          label: '纯文本广告数据',   sdkPath: 'text_data',          level, channel, apiVersion, type: 'json',
        hideInUi: true },
    ],
    sdkConstantsRef: 'AdCreative.Fields.object_story_spec',
  },
  {
    name: 'object_story_id',
    label: '现有帖子 ID',
    sdkPath: 'ad.creative.object_story_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    helpText: '形如 {page_id}_{post_id}，用于推广已有帖子。',
    excludeFromCreate: true,
  },
  {
    name: 'asset_feed_spec',
    label: '多素材源（Asset Feed）',
    sdkPath: 'ad.creative.asset_feed_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    helpText: '{ images, videos, bodies, titles, descriptions, link_urls, call_to_action_types, ad_formats, asset_customization_rules, optimization_type }。',
    excludeFromCreate: true,
  },
  {
    name: 'object_type',
    label: '对象类型',
    sdkPath: 'ad.creative.object_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    excludeFromCreate: true,
    options: [
      { value: 'PAGE',    label: '主页' }, { value: 'DOMAIN', label: '域名' },
      { value: 'EVENT',   label: '活动' }, { value: 'OFFER',  label: '优惠' },
      { value: 'PHOTO',   label: '图片' }, { value: 'SHARE',  label: '分享' },
      { value: 'STATUS',  label: '状态' }, { value: 'STORE_ITEM', label: '商品' },
      { value: 'VIDEO',   label: '视频' },
    ],
  },
  // Phase 2.M：title / body / link_url / image_hash / video_id 等创意文案字段移到「素材组级」AdCopyEditor 编辑
  {
    name: 'title',
    label: '广告标题',
    sdkPath: 'ad.creative.title',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    validation: { max: 40 },
    helpText: '建议 ≤ 40 字符。Phase 2.M：在产品模块「📝 文案」per 素材组配置。',
    excludeFromCreate: true,
  },
  {
    name: 'body',
    label: '广告正文',
    sdkPath: 'ad.creative.body',
    level, channel, apiVersion,
    type: 'textarea',
    group: 'creative',
    validation: { max: 125 },
    helpText: '建议 ≤ 125 字符。Phase 2.M：在产品模块「📝 文案」per 素材组配置。',
    excludeFromCreate: true,
  },
  {
    name: 'link_url',
    label: '落地页 URL',
    sdkPath: 'ad.creative.link_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'cta',
    excludeFromCreate: true,
  },
  {
    name: 'image_hash',
    label: '广告图片',
    sdkPath: 'ad.creative.image_hash',
    level, channel, apiVersion,
    type: 'select',
    options: META_IMAGES,
    group: 'creative',
    dependsOn: { field: 'ad_format', in: ['SINGLE_IMAGE', 'COLLECTION', 'FLEXIBLE'] },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'SINGLE_IMAGE' && !root?.ad?.image_url,
    excludeFromCreate: true,
  },
  {
    name: 'image_url',
    label: '图片 URL',
    sdkPath: 'ad.creative.image_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'video_id',
    label: '广告视频',
    sdkPath: 'ad.creative.video_id',
    level, channel, apiVersion,
    type: 'select',
    options: META_VIDEOS,
    group: 'creative',
    dependsOn: { field: 'ad_format', in: ['SINGLE_VIDEO', 'FLEXIBLE'] },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'SINGLE_VIDEO',
    excludeFromCreate: true,
  },
  {
    name: 'instagram_user_id',
    label: 'Instagram 账户',
    sdkPath: 'ad.creative.instagram_user_id',
    level, channel, apiVersion,
    type: 'select',
    options: META_IG_ACCOUNTS,
    group: 'creative',
  },
  {
    name: 'instagram_permalink_url',
    label: 'Instagram 帖子链接',
    sdkPath: 'ad.creative.instagram_permalink_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
  },
  {
    name: 'product_set_id',
    label: '商品集合（DPA）',
    sdkPath: 'ad.creative.product_set_id',
    level, channel, apiVersion,
    type: 'select',
    options: META_PRODUCT_SETS,
    group: 'creative',
    helpText: '动态产品广告必填。',
    dependsOn: { field: 'ad_format', equals: 'DPA' },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'DPA',
  },
  {
    name: 'applink_treatment',
    label: '深链处理方式',
    sdkPath: 'ad.creative.applink_treatment',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'deeplink_with_web_fallback',      label: '深链 + Web 兜底' },
      { value: 'deeplink_with_appstore_fallback', label: '深链 + 应用商店兜底' },
      { value: 'web_only',                        label: '仅 Web' },
    ],
  },
  {
    name: 'call_to_action_type',
    label: '行动号召按钮',
    sdkPath: 'ad.creative.call_to_action_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'cta',
    // Phase 2.I：流量/销售/线索类对 CTA 强需求
    requiredWhen: (_, root) => ['OUTCOME_TRAFFIC', 'OUTCOME_SALES', 'OUTCOME_LEADS'].includes(root?.campaign?.objective),
    // Phase 2.M：移到「素材组级」AdCopyEditor 配置；schema 字段保留供 publish 层映射
    excludeFromCreate: true,
    // Phase 2.L：SDK CallToActionType enum 全 95+ 值（按 facebook-python-business-sdk adcreative.py 源码同步）
    options: [
      // — 通用 / 默认 —
      { value: 'LEARN_MORE',          label: '了解更多' },
      { value: 'NO_BUTTON',           label: '无按钮' },
      { value: 'OPEN_LINK',           label: '打开链接' },
      { value: 'SEE_MORE',            label: '查看更多' },
      { value: 'GET_DETAILS',         label: '查看详情' },
      { value: 'FIND_OUT_MORE',       label: '获取更多信息' },
      // — Shopping / 购物 —
      { value: 'SHOP_NOW',            label: '立即购买',   dependsOn: ctaForObjective(['OUTCOME_SALES']) },
      { value: 'BUY_NOW',             label: '立即购买',   dependsOn: ctaForObjective(['OUTCOME_SALES']) },
      { value: 'BUY',                 label: '购买',       dependsOn: ctaForObjective(['OUTCOME_SALES']) },
      { value: 'ORDER_NOW',           label: '立即订购' },
      { value: 'START_ORDER',         label: '开始下单' },
      { value: 'ADD_TO_CART',         label: '加入购物车', dependsOn: ctaForObjective(['OUTCOME_SALES']) },
      { value: 'VIEW_CART',           label: '查看购物车' },
      { value: 'VIEW_IN_CART',        label: '在购物车中查看' },
      { value: 'BROWSE_SHOP',         label: '浏览店铺' },
      { value: 'SEE_SHOP',            label: '查看店铺' },
      { value: 'VIEW_PRODUCT',        label: '查看商品' },
      { value: 'SELL_NOW',            label: '立即出售' },
      { value: 'SHOP_WITH_AI',        label: 'AI 智能购物' },
      { value: 'TRY_ON_WITH_AI',      label: 'AI 虚拟试穿' },
      { value: 'TRY_DEMO',            label: '试用 Demo' },
      { value: 'SWIPE_UP_PRODUCT',    label: '上滑查看商品' },
      { value: 'SWIPE_UP_SHOP',       label: '上滑查看店铺' },
      { value: 'PURCHASE_GIFT_CARDS', label: '购买礼品卡' },
      { value: 'BUY_VIA_MESSAGE',     label: '通过消息购买' },
      { value: 'GET_OFFER',           label: '获取优惠' },
      { value: 'GET_OFFER_VIEW',      label: '查看优惠' },
      { value: 'GET_PROMOTIONS',      label: '获取促销' },
      // — Lead / 潜客 —
      { value: 'GET_QUOTE',           label: '获取报价',   dependsOn: ctaForObjective(['OUTCOME_LEADS']) },
      { value: 'SIGN_UP',             label: '立即注册',   dependsOn: ctaForObjective(['OUTCOME_LEADS', 'OUTCOME_SALES']) },
      { value: 'APPLY_NOW',           label: '立即申请',   dependsOn: ctaForObjective(['OUTCOME_LEADS']) },
      { value: 'SUBSCRIBE',           label: '订阅' },
      { value: 'SOTTO_SUBSCRIBE',     label: '订阅（Sotto）' },
      { value: 'CONFIRM',             label: '确认' },
      { value: 'CONTACT',             label: '联系' },
      { value: 'CONTACT_US',          label: '联系我们',   dependsOn: ctaForObjective(['OUTCOME_LEADS', 'OUTCOME_ENGAGEMENT']) },
      { value: 'GET_IN_TOUCH',        label: '取得联系' },
      { value: 'INQUIRE_NOW',         label: '立即询问' },
      { value: 'ASK_A_QUESTION',      label: '提问' },
      { value: 'ASK_FOR_MORE_INFO',   label: '咨询更多信息' },
      { value: 'ASK_ABOUT_SERVICES',  label: '咨询服务' },
      { value: 'ASK_US',              label: '咨询我们' },
      { value: 'EVENT_RSVP',          label: '活动响应' },
      { value: 'BOOK_NOW',            label: '立即预订' },
      { value: 'BOOK_A_CONSULTATION', label: '预约咨询' },
      { value: 'BOOK_TRAVEL',         label: '预订行程' },
      { value: 'BUY_TICKETS',         label: '购买门票' },
      { value: 'GET_SHOWTIMES',       label: '查看场次' },
      { value: 'MAKE_AN_APPOINTMENT', label: '预约' },
      { value: 'REQUEST_TIME',        label: '请求时间' },
      { value: 'SAY_THANKS',          label: '说声谢谢' },
      // — App —
      { value: 'INSTALL_APP',         label: '安装应用',         dependsOn: ctaForObjective(['OUTCOME_APP_PROMOTION']) },
      { value: 'INSTALL_MOBILE_APP',  label: '安装移动应用',     dependsOn: ctaForObjective(['OUTCOME_APP_PROMOTION']) },
      { value: 'USE_APP',             label: '使用应用',         dependsOn: ctaForObjective(['OUTCOME_APP_PROMOTION']) },
      { value: 'USE_MOBILE_APP',      label: '使用移动应用',     dependsOn: ctaForObjective(['OUTCOME_APP_PROMOTION']) },
      { value: 'UPDATE_APP',          label: '更新应用' },
      { value: 'PLAY_GAME',           label: '玩游戏',           dependsOn: ctaForObjective(['OUTCOME_APP_PROMOTION']) },
      { value: 'PLAY_GAME_ON_FACEBOOK', label: '在 Facebook 玩游戏' },
      { value: 'OPEN_INSTANT_APP',    label: '打开 Instant App' },
      { value: 'MOBILE_DOWNLOAD',     label: '移动下载' },
      { value: 'DOWNLOAD',            label: '下载' },
      // — Phone / Call —
      { value: 'CALL',                label: '致电' },
      { value: 'CALL_NOW',            label: '立即致电' },
      { value: 'CALL_ME',             label: '致电我' },
      { value: 'AUDIO_CALL',          label: '语音通话' },
      { value: 'VIDEO_CALL',          label: '视频通话' },
      // — Messaging / 消息 —
      { value: 'CHAT_NOW',            label: '立即聊天' },
      { value: 'CHAT_WITH_US',        label: '与我们聊天' },
      { value: 'START_A_CHAT',        label: '开始聊天' },
      { value: 'MESSAGE_PAGE',        label: '私信主页',         dependsOn: ctaForObjective(['OUTCOME_ENGAGEMENT']) },
      { value: 'WHATSAPP_MESSAGE',    label: 'WhatsApp 消息',    dependsOn: ctaForObjective(['OUTCOME_ENGAGEMENT', 'OUTCOME_LEADS']) },
      { value: 'SEND_UPDATES',        label: '发送更新' },
      // — Engagement / 互动 —
      { value: 'LIKE_PAGE',           label: '点赞主页',         dependsOn: ctaForObjective(['OUTCOME_ENGAGEMENT']) },
      { value: 'FOLLOW_PAGE',         label: '关注主页' },
      { value: 'FOLLOW_USER',         label: '关注用户' },
      { value: 'FOLLOW_NEWS_STORYLINE', label: '关注新闻话题' },
      { value: 'FIND_A_GROUP',        label: '查找群组' },
      { value: 'FIND_YOUR_GROUPS',    label: '查找你的群组' },
      { value: 'JOIN_CHANNEL',        label: '加入频道' },
      { value: 'SHARE',               label: '分享' },
      { value: 'REFER_FRIENDS',       label: '推荐好友' },
      { value: 'VISIT_PAGES_FEED',    label: '访问主页动态' },
      { value: 'VISIT_WEBSITE',       label: '访问网站' },
      { value: 'VIEW_CHANNEL',        label: '查看频道' },
      { value: 'RECORD_NOW',          label: '立即录制' },
      // — Video / 视频 —
      { value: 'WATCH_VIDEO',         label: '观看视频' },
      { value: 'WATCH_MORE',          label: '查看更多视频' },
      { value: 'WATCH_LIVE_VIDEO',    label: '观看直播' },
      { value: 'LISTEN_NOW',          label: '立即收听' },
      { value: 'LISTEN_MUSIC',        label: '听音乐' },
      { value: 'VIDEO_ANNOTATION',    label: '视频标注' },
      // — Donation / 捐赠 —
      { value: 'DONATE',              label: '捐赠' },
      { value: 'DONATE_NOW',          label: '立即捐赠' },
      { value: 'RAISE_MONEY',         label: '筹款' },
      { value: 'SEND_A_GIFT',         label: '送礼物' },
      { value: 'SEND_GIFT_MONEY',     label: '送礼金' },
      // — Local / 本地 —
      { value: 'GET_DIRECTIONS',      label: '获取路线' },
      // — Misc —
      { value: 'PAY_TO_ACCESS',       label: '付费访问' },
      { value: 'WOODHENGE_SUPPORT',   label: 'Woodhenge 支持' },
    ],
  },
  {
    name: 'phone_number',
    label: '电话号码',
    sdkPath: 'ad.creative.phone_number',
    level, channel, apiVersion,
    type: 'text',
    group: 'cta',
    dependsOn: { field: 'call_to_action_type', in: ['CALL', 'CALL_ME'] },
    requiredWhen: (_, root) => ['CALL', 'CALL_ME'].includes(root?.ad?.call_to_action_type),
  },
  {
    name: 'phone_region_calling_code',
    label: '电话区号',
    sdkPath: 'ad.creative.phone_region_calling_code',
    level, channel, apiVersion,
    type: 'text',
    group: 'cta',
    placeholder: '例：+1',
    dependsOn: { field: 'call_to_action_type', in: ['CALL', 'CALL_ME'] },
    requiredWhen: (_, root) => ['CALL', 'CALL_ME'].includes(root?.ad?.call_to_action_type),
  },
  {
    name: 'enroll_status',
    label: '广告增强（按字段独立选）',
    sdkPath: 'ad.creative.enroll_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    helpText: 'v22+：STANDARD_ENHANCEMENTS bundle 不再支持；OPT_IN/OUT 仅作用于 degrees_of_freedom_spec 内单字段。',
    options: [
      { value: 'OPT_IN',  label: '加入' },
      { value: 'OPT_OUT', label: '退出' },
    ],
  },
  {
    name: 'degrees_of_freedom_spec',
    label: '素材自由度规则',
    sdkPath: 'ad.creative.degrees_of_freedom_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'thumbnail_url',
    label: '缩略图 URL',
    sdkPath: 'ad.creative.thumbnail_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
  },
  {
    name: 'template_url',
    label: '模板 URL',
    sdkPath: 'ad.creative.template_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'template_url_spec',
    label: '模板 URL 规则',
    sdkPath: 'ad.creative.template_url_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'product_data',
    label: '商品数据',
    sdkPath: 'ad.creative.product_data',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'platform_customizations',
    label: '版位定制',
    sdkPath: 'ad.creative.platform_customizations',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    helpText: '为 instagram / facebook / audience_network 提供差异化创意。',
    excludeFromCreate: true,
  },
  {
    name: 'authorization_category',
    label: '授权类别',
    sdkPath: 'ad.creative.authorization_category',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'NONE',                                  label: '无' },
      { value: 'POLITICAL',                             label: '政治' },
      { value: 'POLITICAL_WITH_DIGITALLY_CREATED_MEDIA',label: '政治 + 数字合成素材' },
    ],
  },
  {
    name: 'branded_content_sponsor_page_id',
    label: '品牌内容赞助主页',
    sdkPath: 'ad.creative.branded_content_sponsor_page_id',
    level, channel, apiVersion,
    type: 'select',
    options: META_PAGES,
    group: 'branded_content',
    helpText: '合创广告中作为广告投放主体的赞助方主页 ID。',
  },
  {
    name: 'collaborative_ads_lsb_image_bank_id',
    label: '联合广告 LSB 图库 ID',
    sdkPath: 'ad.creative.collaborative_ads_lsb_image_bank_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'creative_sourcing_spec',
    label: '创意来源规则',
    sdkPath: 'ad.creative.creative_sourcing_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'dynamic_ad_voice',
    label: '动态广告主体',
    sdkPath: 'ad.creative.dynamic_ad_voice',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'STORY_OWNER', label: '帖子拥有者' },
      { value: 'DYNAMIC',     label: '动态' },
    ],
  },
  {
    name: 'interactive_components_spec',
    label: '交互组件规则',
    sdkPath: 'ad.creative.interactive_components_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'recommender_settings',
    label: '推荐器设置',
    sdkPath: 'ad.creative.recommender_settings',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },

  // ───────────── 跟踪 ─────────────
  {
    name: 'tracking_specs',
    label: '跟踪规则',
    sdkPath: 'ad.tracking_specs',
    level, channel, apiVersion,
    type: 'json',
    group: 'tracking',
    excludeFromCreate: true,
  },
  {
    name: 'conversion_specs',
    label: '转化规则',
    sdkPath: 'ad.conversion_specs',
    level, channel, apiVersion,
    type: 'json',
    group: 'tracking',
    excludeFromCreate: true,
  },
  {
    name: 'conversion_domain',
    label: '转化域名',
    sdkPath: 'ad.conversion_domain',
    level, channel, apiVersion,
    type: 'text',
    group: 'tracking',
    helpText: 'iOS 14.5+ AEM 必填。',
    requiredWhen: (_, root) => root?.campaign?.objective === 'OUTCOME_SALES'
      && root?.adset?.campaign_attribution === 'AEM',
  },
  {
    name: 'url_tags',
    label: 'URL 参数（UTM）',
    sdkPath: 'ad.creative.url_tags',
    level, channel, apiVersion,
    type: 'text',
    group: 'tracking',
    placeholder: 'utm_source=facebook&utm_medium=cpc&utm_campaign={{campaign.name}}',
  },

  // ───────────── 高级 ─────────────
  {
    name: 'adlabels',
    label: '广告标签',
    sdkPath: 'ad.adlabels',
    level, channel, apiVersion,
    type: 'tags',
    group: 'advanced',
  },
  {
    name: 'execution_options',
    label: '执行选项',
    sdkPath: 'ad.execution_options',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'advanced',
    options: [
      { value: 'validate_only',           label: '仅校验' },
      { value: 'include_recommendations', label: '包含推荐' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'source_ad_id',
    label: '源广告 ID（复制时）',
    sdkPath: 'ad.source_ad_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'audience_id',
    label: '受众 ID',
    sdkPath: 'ad.audience_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'date_format',
    label: '日期格式',
    sdkPath: 'ad.date_format',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'draft_adgroup_id',
    label: '草稿广告 ID',
    sdkPath: 'ad.draft_adgroup_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },

  // ═════════════ Phase 2.L 新增（SDK 验证 — adcreative.py + adcreativebrandedcontentads.py） ═════════════
  // — Click-to-Message / 信息广告（v25 占位） —
  {
    name: 'marketing_message_structured_spec',
    label: '消息广告结构（CTM）',
    sdkPath: 'ad.creative.marketing_message_structured_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    helpText: 'Click-to-Message 广告专用结构化消息内容（v25 高阶）。',
    excludeFromCreate: true,
  },
  {
    name: 'omnichannel_link_spec',
    label: '多渠道落地（Omnichannel）',
    sdkPath: 'ad.creative.omnichannel_link_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  // — Branded Content（旧版品牌内容标记） —
  {
    name: 'instagram_branded_content',
    label: 'Instagram 品牌内容设置',
    sdkPath: 'ad.creative.instagram_branded_content',
    level, channel, apiVersion,
    type: 'json',
    group: 'branded_content',
    helpText: 'Instagram 平台合创广告（branded content）配置 — 含合作创作者 ID、付费合作伙伴标签等。',
  },
  {
    name: 'facebook_branded_content',
    label: 'Facebook 品牌内容设置',
    sdkPath: 'ad.creative.facebook_branded_content',
    level, channel, apiVersion,
    type: 'json',
    group: 'branded_content',
    helpText: 'Facebook 平台合创广告配置。',
  },
  // — DSA 免责声明（欧盟监管） —
  {
    name: 'regional_regulation_disclaimer_spec',
    label: '区域监管免责声明',
    sdkPath: 'ad.creative.regional_regulation_disclaimer_spec',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  // — Playable Asset —
  {
    name: 'playable_asset_id',
    label: '可玩广告素材',
    sdkPath: 'ad.creative.playable_asset_id',
    level, channel, apiVersion,
    type: 'select',
    options: META_VIDEOS,
    group: 'creative',
    helpText: '可玩广告（Playable Ads）专用素材资源 ID。',
    dependsOn: { field: 'ad_format', equals: 'PLAYABLES' },
  },

  // — 合创广告 / Branded Content Ads（Ad 结构化部分，独立 group：'branded_content'） —
  // SDK: AdCreativeBrandedContentAds 14 fields — 广告主与创作者（KOL）合作授权 KOL 帖子作为广告素材投放
  {
    name: 'branded_content',
    label: '合创广告主结构',
    sdkPath: 'ad.creative.branded_content',
    level, channel, apiVersion,
    type: 'composite',
    group: 'branded_content',
    helpText: '广告主与创作者（KOL / 创作者）合作授权 KOL 帖子作为广告素材投放。',
    subFields: [
      { name: 'acting_business_id',           label: '投放方 BC ID',  sdkPath: 'acting_business_id',           level, channel, apiVersion, type: 'text' },
      { name: 'creator_ad_permission_type',   label: '创作者授权类型', sdkPath: 'creator_ad_permission_type',   level, channel, apiVersion, type: 'select',
        options: [
          { value: 'PRE_APPROVED', label: '预批准' },
          { value: 'EXPLICIT',     label: '明确授权' },
          { value: 'DISCOVERED',   label: '已发现内容' },
        ] },
      { name: 'partners',                     label: '合作创作者',     sdkPath: 'partners',                     level, channel, apiVersion, type: 'tags' },
      { name: 'parent_source_facebook_post_id',  label: 'Facebook 源帖子 ID',  sdkPath: 'parent_source_facebook_post_id',  level, channel, apiVersion, type: 'text' },
      { name: 'parent_source_instagram_media_id', label: 'Instagram 源帖子 ID', sdkPath: 'parent_source_instagram_media_id', level, channel, apiVersion, type: 'text' },
      { name: 'promoted_page_id',             label: '被推广主页',     sdkPath: 'promoted_page_id',             level, channel, apiVersion, type: 'select', options: META_PAGES },
      { name: 'testimonial',                  label: '推荐语',         sdkPath: 'testimonial',                  level, channel, apiVersion, type: 'textarea' },
      { name: 'testimonial_locale',           label: '推荐语语言',     sdkPath: 'testimonial_locale',           level, channel, apiVersion, type: 'text' },
      { name: 'automated_adgroup_creation',   label: '自动创建广告组', sdkPath: 'automated_adgroup_creation',   level, channel, apiVersion, type: 'switch' },
      { name: 'deliver_dynamic_partner_content', label: '投放动态合作内容', sdkPath: 'deliver_dynamic_partner_content', level, channel, apiVersion, type: 'switch' },
      { name: 'facebook_boost_post_access_token',  label: 'Facebook Boost token',  sdkPath: 'facebook_boost_post_access_token',  level, channel, apiVersion, type: 'text' },
      { name: 'instagram_boost_post_access_token', label: 'Instagram Boost token', sdkPath: 'instagram_boost_post_access_token', level, channel, apiVersion, type: 'text' },
      { name: 'content_search_input',         label: '内容搜索关键字', sdkPath: 'content_search_input',         level, channel, apiVersion, type: 'text' },
      { name: 'product_set_partner_selection_status', label: '产品集合伙伴选择状态', sdkPath: 'product_set_partner_selection_status', level, channel, apiVersion, type: 'text' },
    ],
  },
];

export default fields;
