/**
 * Meta Marketing API v25 — Campaign 创建/更新可写字段
 * Reference: https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group
 *
 * Phase 2.A：业务化中文 label + 全量激活 + 约束完整。
 * Phase 2.K v25 sync：
 *   - smart_promotion_type 在 v25 正式废弃 → excludeFromCreate
 *   - 新增 is_adset_budget_sharing_enabled（v24 起 adset-level 预算时必填）
 */

const channel = 'meta';
const level = 'campaign';
const apiVersion = 'meta-v25';

/** @type {import('./schema').FieldDef[]} */
const fields = [
  // ───────────── 基础 ─────────────
  {
    name: 'name',
    label: '系列名称',
    sdkPath: 'campaign.name',
    level, channel, apiVersion,
    type: 'text',
    required: true,
    group: 'basic',
    placeholder: '例：US-Summer-Sales-CBO-001',
    helpText: '系列（Campaign）的名称，用于在广告管理中识别。',
    sdkConstantsRef: 'Campaign.Fields.name',
  },
  {
    name: 'objective',
    label: '推广目标',
    sdkPath: 'campaign.objective',
    level, channel, apiVersion,
    type: 'select',
    required: true,
    group: 'basic',
    helpText: 'ODAX 体系下的一级推广目标，决定后续 AdSet 优化目标可选范围。',
    options: [
      { value: 'OUTCOME_AWARENESS',     label: '品牌认知（Awareness）' },
      { value: 'OUTCOME_TRAFFIC',       label: '流量（Traffic）' },
      { value: 'OUTCOME_ENGAGEMENT',    label: '互动（Engagement）' },
      { value: 'OUTCOME_LEADS',         label: '潜在客户（Leads）' },
      { value: 'OUTCOME_APP_PROMOTION', label: '应用推广（App Promotion）' },
      { value: 'OUTCOME_SALES',         label: '销售（Sales）' },
    ],
    sdkConstantsRef: 'Campaign.Objective',
    legacyStateKey: 'objective',
  },
  {
    name: 'special_ad_categories',
    label: '特殊广告类别',
    sdkPath: 'campaign.special_ad_categories',
    level, channel, apiVersion,
    type: 'multiselect',
    required: true,
    group: 'basic',
    helpText: '涉及就业、住房、信贷、社会议题/选举/政治、博彩、金融服务时必选。无则选「无」。',
    options: [
      { value: 'NONE',         label: '无' },
      { value: 'EMPLOYMENT',   label: '就业' },
      { value: 'HOUSING',      label: '住房' },
      { value: 'CREDIT',       label: '信贷' },
      { value: 'ISSUES_ELECTIONS_POLITICS',     label: '社会议题 / 选举 / 政治' },
      { value: 'ONLINE_GAMBLING_AND_GAMING',    label: '在线博彩与游戏' },
      { value: 'FINANCIAL_PRODUCTS_SERVICES',   label: '金融产品与服务' },
    ],
    defaultValue: ['NONE'],
    sdkConstantsRef: 'Campaign.SpecialAdCategories',
  },
  {
    name: 'special_ad_category_country',
    label: '特殊广告类别投放国家',
    sdkPath: 'campaign.special_ad_category_country',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'basic',
    helpText: '特殊广告类别下，投放的国家 ISO 代码列表。',
    options: [
      { value: 'US', label: '美国' }, { value: 'CA', label: '加拿大' },
      { value: 'GB', label: '英国' }, { value: 'AU', label: '澳大利亚' },
      { value: 'DE', label: '德国' }, { value: 'FR', label: '法国' },
    ],
    dependsOn: { field: 'special_ad_categories',
      predicate: (v) => Array.isArray(v) && v.length > 0 && !v.includes('NONE') },
    requiredWhen: (_, root) => {
      const cats = root?.campaign?.special_ad_categories;
      return Array.isArray(cats) && cats.length > 0 && !cats.includes('NONE');
    },
  },
  {
    name: 'buying_type',
    label: '购买类型',
    sdkPath: 'campaign.buying_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    helpText: '竞价购买（Auction）vs 预定购买（Reach & Frequency）。',
    options: [
      { value: 'AUCTION',  label: '竞价（Auction）' },
      { value: 'RESERVED', label: '预定（Reach & Frequency）' },
    ],
    defaultValue: 'AUCTION',
    sdkConstantsRef: 'Campaign.BuyingType',
  },
  {
    name: 'status',
    label: '初始状态',
    sdkPath: 'campaign.status',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'PAUSED', label: '已暂停' },
      { value: 'ACTIVE', label: '已激活' },
    ],
    defaultValue: 'PAUSED',
    sdkConstantsRef: 'Campaign.Status',
    excludeFromCreate: true,
  },

  // ───────────── 出价与预算 ─────────────
  {
    name: 'bid_strategy',
    label: '系列出价策略',
    sdkPath: 'campaign.bid_strategy',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    helpText: '系列级别的竞价策略（CBO 时使用）。',
    options: [
      { value: 'LOWEST_COST_WITHOUT_CAP',   label: '最大化成果（无上限）' },
      { value: 'LOWEST_COST_WITH_BID_CAP',  label: '出价上限（Bid Cap）' },
      { value: 'COST_CAP',                  label: '成本上限（Cost Cap）' },
      { value: 'LOWEST_COST_WITH_MIN_ROAS', label: 'ROAS 目标' },
    ],
    sdkConstantsRef: 'Campaign.BidStrategy',
    legacyStateKey: 'bidStrategy',
  },
  // ───────────── 预算 ───────────── (Phase 2.K：从 bidding 拆出独立 group)
  {
    name: 'daily_budget',
    label: '系列日预算（CBO）',
    sdkPath: 'campaign.daily_budget',
    level, channel, apiVersion,
    type: 'currency',
    group: 'budget',
    helpText: '启用 CBO（系列预算优化）时填写。与 lifetime_budget 二选一。',
    validation: { min: 1 },
    mutuallyExclusiveWith: ['lifetime_budget'],
    legacyStateKey: 'dailyBudget',
  },
  {
    name: 'lifetime_budget',
    label: '系列总预算',
    sdkPath: 'campaign.lifetime_budget',
    level, channel, apiVersion,
    type: 'currency',
    group: 'budget',
    helpText: '总预算模式。设置后 start_time / stop_time 必填。与 daily_budget 二选一。',
    validation: { min: 1 },
    mutuallyExclusiveWith: ['daily_budget'],
  },
  {
    name: 'spend_cap',
    label: '系列累计花费上限',
    sdkPath: 'campaign.spend_cap',
    level, channel, apiVersion,
    type: 'currency',
    group: 'budget',
    helpText: '系列累计花费达到上限后自动暂停。',
  },
  {
    name: 'budget_schedule_specs',
    label: '高峰期预算调整规则',
    sdkPath: 'campaign.budget_schedule_specs',
    level, channel, apiVersion,
    type: 'json',
    group: 'budget',
    helpText: '预算阶段性提升规则数组。',
    excludeFromCreate: true,
  },
  {
    name: 'is_adset_budget_sharing_enabled',
    label: '广告组预算共享',
    sdkPath: 'campaign.is_adset_budget_sharing_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'budget',
    helpText: 'v24+：当 adset 级使用预算时必须开启此项以声明 ABO 模式。',
    requiredWhen: (_, root) =>
      !!root?.adset?.daily_budget || !!root?.adset?.lifetime_budget,
  },
  {
    name: 'campaign_optimization_type',
    label: '系列内优化策略',
    sdkPath: 'campaign.campaign_optimization_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'NONE',     label: '无' },
      { value: 'ICO_ONLY', label: '仅系列内优化（ICO）' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'pacing_type',
    label: '投放节奏',
    sdkPath: 'campaign.pacing_type',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'bidding',
    options: [
      { value: 'standard',  label: '标准（平滑）' },
      { value: 'no_pacing', label: '无节奏（已弃用）' },
    ],
    excludeFromCreate: true,
  },

  // ───────────── 排期 ─────────────
  {
    name: 'start_time',
    label: '开始时间',
    sdkPath: 'campaign.start_time',
    level, channel, apiVersion,
    type: 'datetime',
    group: 'schedule',
    helpText: '使用 lifetime_budget 时必填。ISO 8601 格式。',
    requiredWhen: (_, root) => !!root?.campaign?.lifetime_budget,
  },
  {
    name: 'stop_time',
    label: '结束时间',
    sdkPath: 'campaign.stop_time',
    level, channel, apiVersion,
    type: 'datetime',
    group: 'schedule',
    helpText: '使用 lifetime_budget 时必填。',
    requiredWhen: (_, root) => !!root?.campaign?.lifetime_budget,
  },

  // ───────────── 高级 ─────────────
  {
    name: 'iterative_split_test_configs',
    label: 'A/B 测试配置',
    sdkPath: 'campaign.iterative_split_test_configs',
    level, channel, apiVersion,
    type: 'json',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'is_skadnetwork_attribution',
    label: 'SKAdNetwork 归因（iOS 14.5+）',
    sdkPath: 'campaign.is_skadnetwork_attribution',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    helpText: '推广目标为应用推广时建议启用。',
    dependsOn: { field: 'objective', equals: 'OUTCOME_APP_PROMOTION' },
  },
  {
    name: 'smart_promotion_type',
    label: '智能推广类型',
    sdkPath: 'campaign.smart_promotion_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'GUIDED_CREATION',       label: '引导创建（Guided）' },
      { value: 'SMART_APP_PROMOTION',   label: '智能应用推广' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'promoted_object',
    label: '系列级推广对象',
    sdkPath: 'campaign.promoted_object',
    level, channel, apiVersion,
    type: 'json',
    group: 'advanced',
    helpText: '像素 / 主页 / 应用 / 商品集合。AdSet 层通常会覆盖此项。',
    excludeFromCreate: true,
  },
  {
    name: 'source_campaign_id',
    label: '源系列 ID（复制时使用）',
    sdkPath: 'campaign.source_campaign_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'topline_id',
    label: 'Topline ID（预定购买）',
    sdkPath: 'campaign.topline_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    helpText: 'Reach & Frequency 预定购买使用。',
    dependsOn: { field: 'buying_type', equals: 'RESERVED' },
    requiredWhen: (_, root) => root?.campaign?.buying_type === 'RESERVED',
  },
  {
    name: 'execution_options',
    label: '执行选项',
    sdkPath: 'campaign.execution_options',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'advanced',
    options: [
      { value: 'validate_only',          label: '仅校验（不实际创建）' },
      { value: 'include_recommendations',label: '包含推荐项' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'adlabels',
    label: '广告标签',
    sdkPath: 'campaign.adlabels',
    level, channel, apiVersion,
    type: 'tags',
    group: 'advanced',
    helpText: '内部分组 / 报表用标签。',
    excludeFromCreate: true,
  },

  // ───────────── Phase 2.L 新增（v25 SDK 验证 — Ads Manager UI 暴露） ─────────────
  {
    name: 'is_message_campaign',
    label: '信息广告系列',
    sdkPath: 'campaign.is_message_campaign',
    level, channel, apiVersion,
    type: 'switch',
    group: 'basic',
    helpText: '启用后系列将以信息（Messenger / WhatsApp）为主要互动方式。',
  },
  {
    name: 'is_direct_send_campaign',
    label: '直接发送系列',
    sdkPath: 'campaign.is_direct_send_campaign',
    level, channel, apiVersion,
    type: 'switch',
    group: 'basic',
    helpText: '直接发送（Direct Send）系列变体；与 is_message_campaign 配套。',
  },
  {
    name: 'dsa_beneficiary',
    label: 'DSA 受益方',
    sdkPath: 'campaign.dsa_beneficiary',
    level, channel, apiVersion,
    type: 'text',
    group: 'basic',
    helpText: '欧盟数字服务法（DSA）合规：广告受益方主体名称（投放欧盟时必填）。',
  },
  {
    name: 'dsa_payor',
    label: 'DSA 付款方',
    sdkPath: 'campaign.dsa_payor',
    level, channel, apiVersion,
    type: 'text',
    group: 'basic',
    helpText: '欧盟数字服务法（DSA）合规：广告付款方主体名称（投放欧盟时必填）。',
  },
];

export default fields;
