/**
 * TikTok Business API v1.3 — AdGroup 创建/更新可写字段
 * Reference: POST /open_api/v1.3/adgroup/create/
 *
 * Phase 2.C：补 mock 选项 + 完整联动（optimization_event×optimization_goal /
 * placements×identity / objective_type×pixel/app 必填）。
 */

import {
  TIKTOK_IDENTITIES, TIKTOK_BC_ACCOUNTS, TIKTOK_PIXELS, TIKTOK_APPS,
  TIKTOK_PRODUCT_SETS, TIKTOK_AUDIENCES, TIKTOK_INTEREST_KEYWORDS,
  TIKTOK_INTEREST_CATEGORIES, TIKTOK_PANGLE_AUDIENCE_PACKAGES,
  TIKTOK_OFFLINE_EVENT_SETS, TIKTOK_DEVICE_MODELS, TIKTOK_ISPS, TIKTOK_CARRIERS,
  TIKTOK_LOCATIONS,
} from '../services/platformResources';

const channel = 'tiktok';
const level = 'adset';
const apiVersion = 'tiktok-v1.3';

// objective_type → adgroup.optimization_goal 联动（部分主流映射）
const OG = (vals) => ({ level: 'campaign', field: 'objective_type', in: vals });

/** @type {import('./schema').FieldDef[]} */
const fields = [
  // ───────────── 基础 ─────────────
  {
    name: 'adgroup_name',
    label: '广告组名称',
    sdkPath: 'adgroup.adgroup_name',
    level, channel, apiVersion,
    type: 'text',
    required: true,
    group: 'basic',
    validation: { max: 512 },
  },
  {
    name: 'promotion_type',
    label: '推广类型',
    sdkPath: 'adgroup.promotion_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'WEBSITE',         label: '网站' },
      { value: 'APP_ANDROID',     label: '应用（Android）' },
      { value: 'APP_IOS',         label: '应用（iOS）' },
      { value: 'LEAD_GENERATION', label: '潜在客户' },
      { value: 'OFFLINE',         label: '线下' },
      { value: 'TIKTOK_ACCOUNT',  label: 'TikTok 账号' },
      { value: 'TIKTOK_SHOP',     label: 'TikTok Shop' },
      { value: 'IN_APP_AD',       label: '应用内广告' },
    ],
  },
  {
    name: 'app_id',
    label: '推广应用',
    sdkPath: 'adgroup.app_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_APPS,
    group: 'basic',
    dependsOn: {
      predicate: (_, root) =>
        ['APP_ANDROID', 'APP_IOS'].includes(root?.adset?.promotion_type)
        || root?.campaign?.objective_type === 'APP_PROMOTION',
    },
    requiredWhen: (_, root) =>
      ['APP_ANDROID', 'APP_IOS'].includes(root?.adset?.promotion_type)
      || root?.campaign?.objective_type === 'APP_PROMOTION',
  },
  {
    name: 'identity_id',
    label: '投放身份',
    sdkPath: 'adgroup.identity_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_IDENTITIES,
    group: 'basic',
    helpText: '投放使用的 TikTok 账号身份。当版位含 TikTok 时必填。',
    requiredWhen: (_, root) =>
      Array.isArray(root?.adset?.placements)
      && root.adset.placements.includes('PLACEMENT_TIKTOK'),
  },
  {
    name: 'identity_type',
    label: '身份类型',
    sdkPath: 'adgroup.identity_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'CUSTOMIZED_USER', label: '自定义用户' },
      { value: 'AUTH_CODE',       label: '授权码' },
      { value: 'TT_USER',         label: 'TikTok 用户' },
      { value: 'BC_AUTH_TT',      label: 'BC 授权 TikTok' },
    ],
    requiredWhen: (_, root) =>
      Array.isArray(root?.adset?.placements)
      && root.adset.placements.includes('PLACEMENT_TIKTOK'),
  },
  {
    name: 'identity_authorized_bc_id',
    label: '授权商务中心（BC）',
    sdkPath: 'adgroup.identity_authorized_bc_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_BC_ACCOUNTS,
    group: 'basic',
    dependsOn: { field: 'identity_type', equals: 'BC_AUTH_TT' },
  },
  {
    name: 'placement_type',
    label: '版位选择方式',
    sdkPath: 'adgroup.placement_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'PLACEMENT_TYPE_AUTOMATIC', label: '自动' },
      { value: 'PLACEMENT_TYPE_NORMAL',    label: '手动' },
    ],
    defaultValue: 'PLACEMENT_TYPE_NORMAL',
  },
  {
    name: 'placements',
    label: '投放版位',
    sdkPath: 'adgroup.placements',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'basic',
    options: [
      { value: 'PLACEMENT_TIKTOK',            label: 'TikTok' },
      { value: 'PLACEMENT_PANGLE',            label: 'Pangle' },
      { value: 'PLACEMENT_GLOBAL_APP_BUNDLE', label: 'Global App Bundle（CapCut/Fizzo）' },
    ],
    dependsOn: { field: 'placement_type', equals: 'PLACEMENT_TYPE_NORMAL' },
    requiredWhen: (_, root) => root?.adset?.placement_type === 'PLACEMENT_TYPE_NORMAL',
  },
  {
    name: 'operation_status',
    label: '初始状态',
    sdkPath: 'adgroup.operation_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'ENABLE',  label: '启用' },
      { value: 'DISABLE', label: '禁用' },
    ],
    defaultValue: 'DISABLE',
    excludeFromCreate: true,
  },

  // ───────────── 出价与预算 ─────────────
  {
    name: 'budget_mode',
    label: '预算模式',
    sdkPath: 'adgroup.budget_mode',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'BUDGET_MODE_INFINITE',             label: '无限制' },
      { value: 'BUDGET_MODE_DAY',                  label: '日预算' },
      { value: 'BUDGET_MODE_TOTAL',                label: '总预算' },
      { value: 'BUDGET_MODE_DYNAMIC_DAILY_BUDGET', label: '动态日预算' },
    ],
    defaultValue: 'BUDGET_MODE_DAY',
  },
  {
    name: 'budget',
    label: '广告组预算',
    sdkPath: 'adgroup.budget',
    level, channel, apiVersion,
    type: 'currency',
    group: 'bidding',
    validation: { min: 20 },
    helpText: 'CBO 模式由系列预算管理；ABO 模式（budget_mode=DAY/TOTAL）时必填。≥ 20 USD。',
    dependsOn: { predicate: (_, root) =>
      !root?.campaign?.budget_optimize_on
      && ['BUDGET_MODE_DAY', 'BUDGET_MODE_TOTAL'].includes(root?.adset?.budget_mode),
    },
    requiredWhen: (_, root) =>
      !root?.campaign?.budget_optimize_on
      && ['BUDGET_MODE_DAY', 'BUDGET_MODE_TOTAL'].includes(root?.adset?.budget_mode),
    legacyStateKey: 'dailyBudget',
  },
  {
    name: 'optimization_goal',
    label: '优化目标',
    sdkPath: 'adgroup.optimization_goal',
    level, channel, apiVersion,
    type: 'select',
    required: true,
    group: 'bidding',
    options: [
      { value: 'CLICK',                 label: '点击', dependsOn: OG(['TRAFFIC']) },
      { value: 'TRAFFIC_LANDING_PAGE_VIEW', label: '落地页浏览', dependsOn: OG(['TRAFFIC', 'WEB_CONVERSIONS']) },
      { value: 'CONVERT',               label: '转化', dependsOn: OG(['WEB_CONVERSIONS', 'PRODUCT_SALES', 'SHOP_PURCHASES']) },
      { value: 'INSTALL',               label: '安装', dependsOn: OG(['APP_PROMOTION']) },
      { value: 'IN_APP_EVENT',          label: '应用内事件', dependsOn: OG(['APP_PROMOTION']) },
      { value: 'VALUE',                 label: '价值（ROAS）', dependsOn: OG(['WEB_CONVERSIONS', 'PRODUCT_SALES', 'SHOP_PURCHASES', 'APP_PROMOTION']) },
      { value: 'REACH',                 label: '触达', dependsOn: OG(['REACH']) },
      { value: 'SHOW',                  label: '展示', dependsOn: OG(['REACH']) },
      { value: 'VIDEO_VIEW',            label: '视频观看', dependsOn: OG(['VIDEO_VIEWS']) },
      { value: 'ENGAGED_VIEW',          label: '完成观看', dependsOn: OG(['VIDEO_VIEWS']) },
      { value: 'ENGAGED_VIEW_FIFTEEN',  label: '完成观看 15s', dependsOn: OG(['VIDEO_VIEWS']) },
      { value: 'PRODUCT_CLICK_IN_LIVE', label: '直播商品点击', dependsOn: OG(['SHOP_PURCHASES']) },
      { value: 'LIVE_VIEW',             label: '直播观看', dependsOn: OG(['SHOP_PURCHASES', 'COMMUNITY_INTERACTION']) },
      { value: 'FOLLOWERS',             label: '粉丝', dependsOn: OG(['COMMUNITY_INTERACTION']) },
      { value: 'PROFILE_VIEWS',         label: '主页访问', dependsOn: OG(['COMMUNITY_INTERACTION']) },
      { value: 'INTERACTIONS',          label: '互动', dependsOn: OG(['COMMUNITY_INTERACTION', 'ENGAGEMENT']) },
      { value: 'LEAD_GENERATION',       label: '潜在客户', dependsOn: OG(['LEAD_GENERATION']) },
      { value: 'INITIATE_CHECKOUT',     label: '开始结账', dependsOn: OG(['PRODUCT_SALES', 'SHOP_PURCHASES']) },
      { value: 'MT_LIVE_ROOM',          label: '直播间', dependsOn: OG(['SHOP_PURCHASES']) },
    ],
    legacyStateKey: 'adsetGoal',
  },
  {
    name: 'billing_event',
    label: '计费事件',
    sdkPath: 'adgroup.billing_event',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'CPC',  label: 'CPC（按点击）',
        dependsOn: { field: 'optimization_goal', in: ['CLICK', 'TRAFFIC_LANDING_PAGE_VIEW'] } },
      { value: 'CPM',  label: 'CPM（按千次展示）',
        dependsOn: { field: 'optimization_goal', in: ['REACH', 'SHOW', 'VIDEO_VIEW'] } },
      { value: 'OCPM', label: 'oCPM（优化千次展示）',
        dependsOn: { field: 'optimization_goal', in: ['CONVERT', 'INSTALL', 'IN_APP_EVENT', 'VALUE'] } },
      { value: 'CPV',  label: 'CPV（按观看）',
        dependsOn: { field: 'optimization_goal', in: ['VIDEO_VIEW', 'ENGAGED_VIEW', 'ENGAGED_VIEW_FIFTEEN'] } },
    ],
  },
  {
    name: 'pacing',
    label: '投放节奏',
    sdkPath: 'adgroup.pacing',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'PACING_MODE_SMOOTH', label: '标准（平滑）' },
      { value: 'PACING_MODE_FAST',   label: '加速' },
    ],
    defaultValue: 'PACING_MODE_SMOOTH',
  },
  {
    name: 'bid_type',
    label: '出价方式',
    sdkPath: 'adgroup.bid_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'BID_TYPE_NO_BID',         label: '最低成本' },
      { value: 'BID_TYPE_CUSTOM',         label: '成本上限 / 出价上限' },
      { value: 'BID_TYPE_MAX_CONVERSION', label: '最大化转化' },
    ],
    legacyStateKey: 'bidStrategy',
  },
  {
    name: 'bid_price',
    label: '出价金额',
    sdkPath: 'adgroup.bid_price',
    level, channel, apiVersion,
    type: 'currency',
    group: 'bidding',
    helpText: 'CBO 时由系列出价类型决定；ABO 时看本广告组出价类型。',
    dependsOn: { predicate: (_, root) => {
      const bt = root?.adset?.bid_type || root?.campaign?.bid_type;
      return bt === 'BID_TYPE_CUSTOM';
    } },
    requiredWhen: (_, root) => {
      const bt = root?.adset?.bid_type || root?.campaign?.bid_type;
      return bt === 'BID_TYPE_CUSTOM';
    },
    legacyStateKey: 'bidAmount',
  },
  {
    name: 'conversion_bid_price',
    label: '转化出价',
    sdkPath: 'adgroup.conversion_bid_price',
    level, channel, apiVersion,
    type: 'currency',
    group: 'bidding',
  },
  {
    name: 'cpv_video_duration',
    label: 'CPV 视频时长',
    sdkPath: 'adgroup.cpv_video_duration',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'TWO_SECONDS', label: '2 秒' },
      { value: 'SIX_SECONDS', label: '6 秒' },
    ],
    dependsOn: { field: 'billing_event', equals: 'CPV' },
    requiredWhen: (_, root) => root?.adset?.billing_event === 'CPV',
  },
  {
    name: 'deep_bid_type',
    label: '深度出价类型',
    sdkPath: 'adgroup.deep_bid_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'VO_MIN_ROAS',      label: '最低 ROAS' },
      { value: 'VO_HIGHEST_VALUE', label: '最高价值' },
      { value: 'AEO',              label: 'AEO 应用事件优化' },
      { value: 'DEFAULT',          label: '默认' },
    ],
  },
  {
    name: 'deep_cpa_bid',
    label: '深度 CPA 出价',
    sdkPath: 'adgroup.deep_cpa_bid',
    level, channel, apiVersion,
    type: 'currency',
    group: 'bidding',
    dependsOn: { field: 'deep_bid_type', equals: 'AEO' },
  },
  {
    name: 'roas_bid',
    label: 'ROAS 目标',
    sdkPath: 'adgroup.roas_bid',
    level, channel, apiVersion,
    type: 'number',
    group: 'bidding',
    validation: { min: 0.01 },
    dependsOn: { field: 'deep_bid_type', equals: 'VO_MIN_ROAS' },
    requiredWhen: (_, root) => root?.adset?.deep_bid_type === 'VO_MIN_ROAS',
  },
  {
    name: 'optimization_event',
    label: '优化事件',
    sdkPath: 'adgroup.optimization_event',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    helpText: '可选事件依优化目标而定。',
    options: [
      // Web events（CONVERT / VALUE）
      { value: 'PURCHASE',              label: '购买',
        dependsOn: { field: 'optimization_goal', in: ['CONVERT', 'VALUE'] } },
      { value: 'COMPLETE_PAYMENT',      label: '完成支付',
        dependsOn: { field: 'optimization_goal', in: ['CONVERT', 'VALUE'] } },
      { value: 'INITIATE_CHECKOUT',     label: '开始结账',
        dependsOn: { field: 'optimization_goal', in: ['CONVERT', 'VALUE'] } },
      { value: 'ON_WEB_CART',           label: '加入购物车',
        dependsOn: { field: 'optimization_goal', equals: 'CONVERT' } },
      { value: 'ON_WEB_ADD_TO_WISHLIST',label: '加入愿望单',
        dependsOn: { field: 'optimization_goal', equals: 'CONVERT' } },
      { value: 'ON_WEB_DETAIL',         label: '商品详情浏览',
        dependsOn: { field: 'optimization_goal', equals: 'CONVERT' } },
      { value: 'ON_WEB_ORDER',          label: '下单',
        dependsOn: { field: 'optimization_goal', in: ['CONVERT', 'VALUE'] } },
      { value: 'ON_WEB_REGISTER',       label: '注册',
        dependsOn: { field: 'optimization_goal', equals: 'CONVERT' } },
      { value: 'SUBSCRIBE',             label: '订阅',
        dependsOn: { field: 'optimization_goal', equals: 'CONVERT' } },
      // Lead generation
      { value: 'FORM',                  label: '表单提交',
        dependsOn: { field: 'optimization_goal', equals: 'LEAD_GENERATION' } },
      { value: 'CONSULT',               label: '咨询',
        dependsOn: { field: 'optimization_goal', equals: 'LEAD_GENERATION' } },
      { value: 'BUTTON',                label: '按钮点击',
        dependsOn: { field: 'optimization_goal', in: ['LEAD_GENERATION', 'CLICK'] } },
      // Traffic / landing
      { value: 'LANDING_PAGE_VIEW',     label: '落地页浏览',
        dependsOn: { field: 'optimization_goal', in: ['TRAFFIC_LANDING_PAGE_VIEW', 'CLICK'] } },
      { value: 'DOWNLOAD_START',        label: '下载开始',
        dependsOn: { field: 'optimization_goal', equals: 'CLICK' } },
      // App events
      { value: 'INSTALL_APP',           label: '安装应用',
        dependsOn: { field: 'optimization_goal', equals: 'INSTALL' } },
      { value: 'LAUNCH_APP',            label: '启动应用',
        dependsOn: { field: 'optimization_goal', equals: 'INSTALL' } },
      { value: 'IN_APP_PURCHASE',       label: '应用内购买',
        dependsOn: { field: 'optimization_goal', equals: 'IN_APP_EVENT' } },
      { value: 'IN_APP_AD_CLICK',       label: '应用内广告点击',
        dependsOn: { field: 'optimization_goal', equals: 'IN_APP_EVENT' } },
      { value: 'IN_APP_AD_IMPR',        label: '应用内广告展示',
        dependsOn: { field: 'optimization_goal', equals: 'IN_APP_EVENT' } },
      { value: 'NEXT_DAY_OPEN',         label: '次日打开',
        dependsOn: { field: 'optimization_goal', equals: 'IN_APP_EVENT' } },
      { value: 'CUSTOM_PAGE_EVENT',     label: '自定义页面事件' },
    ],
    requiredWhen: (_, root) =>
      ['CONVERT', 'VALUE', 'INSTALL', 'IN_APP_EVENT', 'LEAD_GENERATION']
        .includes(root?.adset?.optimization_goal)
      || ['WEB_CONVERSIONS', 'PRODUCT_SALES', 'SHOP_PURCHASES', 'APP_PROMOTION']
        .includes(root?.campaign?.objective_type),
  },

  // ───────────── 跟踪 ─────────────
  {
    name: 'pixel_id',
    label: '转化像素',
    sdkPath: 'adgroup.pixel_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_PIXELS,
    group: 'tracking',
    helpText: '网站转化 / 商品销售优化时必填。',
    requiredWhen: (_, root) =>
      ['WEB_CONVERSIONS', 'PRODUCT_SALES', 'SHOP_PURCHASES']
        .includes(root?.campaign?.objective_type),
  },
  {
    name: 'tracking_pixel_id',
    label: '跟踪像素',
    sdkPath: 'adgroup.tracking_pixel_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_PIXELS,
    group: 'tracking',
  },
  {
    name: 'tracking_app_id',
    label: '跟踪应用',
    sdkPath: 'adgroup.tracking_app_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_APPS,
    group: 'tracking',
  },
  {
    name: 'tracking_offline_event_set_ids',
    label: '线下事件集',
    sdkPath: 'adgroup.tracking_offline_event_set_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_OFFLINE_EVENT_SETS,
    group: 'tracking',
  },
  // Phase 2.L: JSON → composite，3 个 select 子字段（click / view / engaged_view 三窗口）
  {
    name: 'event_attribution_window',
    label: '事件归因窗口',
    sdkPath: 'adgroup.event_attribution_window',
    level, channel, apiVersion,
    type: 'composite',
    group: 'tracking',
    helpText: '点击 / 浏览 / 互动观看的归因时长（天）。',
    subFields: [
      { name: 'click_window',         label: '点击归因窗口', sdkPath: 'click_window',         level, channel, apiVersion,
        type: 'select',
        options: [
          { value: 'CLICK_THROUGH_1_DAY',   label: '1 天' },
          { value: 'CLICK_THROUGH_7_DAYS',  label: '7 天' },
          { value: 'CLICK_THROUGH_28_DAYS', label: '28 天' },
        ] },
      { name: 'view_window',          label: '浏览归因窗口', sdkPath: 'view_window',          level, channel, apiVersion,
        type: 'select',
        options: [
          { value: 'VIEW_THROUGH_OFF',    label: '关闭' },
          { value: 'VIEW_THROUGH_1_DAY',  label: '1 天' },
          { value: 'VIEW_THROUGH_7_DAYS', label: '7 天' },
        ] },
      { name: 'engaged_view_window',  label: '互动观看归因', sdkPath: 'engaged_view_window',  level, channel, apiVersion,
        type: 'select',
        options: [
          { value: 'ENGAGED_VIEW_OFF',    label: '关闭' },
          { value: 'ENGAGED_VIEW_1_DAY',  label: '1 天' },
          { value: 'ENGAGED_VIEW_7_DAYS', label: '7 天' },
        ] },
    ],
  },

  // ───────────── 排期 ─────────────
  {
    name: 'schedule_type',
    label: '排期类型',
    sdkPath: 'adgroup.schedule_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'schedule',
    options: [
      { value: 'SCHEDULE_FROM_NOW',  label: '立即开始（不设结束）' },
      { value: 'SCHEDULE_START_END', label: '指定开始与结束时间' },
    ],
  },
  {
    name: 'schedule_start_time',
    label: '排期开始时间',
    sdkPath: 'adgroup.schedule_start_time',
    level, channel, apiVersion,
    type: 'datetime',
    group: 'schedule',
  },
  {
    name: 'schedule_end_time',
    label: '排期结束时间',
    sdkPath: 'adgroup.schedule_end_time',
    level, channel, apiVersion,
    type: 'datetime',
    group: 'schedule',
    dependsOn: { field: 'schedule_type', equals: 'SCHEDULE_START_END' },
    requiredWhen: (_, root) => root?.adset?.schedule_type === 'SCHEDULE_START_END',
  },
  {
    name: 'dayparting',
    label: '分时段投放',
    sdkPath: 'adgroup.dayparting',
    level, channel, apiVersion,
    type: 'text',
    group: 'schedule',
    helpText: '336 字符的 0/1 串：48 槽位/天 × 7 天。',
    validation: { pattern: '^[01]{336}$' },
  },
  {
    name: 'frequency',
    label: '频次上限',
    sdkPath: 'adgroup.frequency',
    level, channel, apiVersion,
    type: 'number',
    group: 'schedule',
    excludeFromCreate: true,
  },
  {
    name: 'frequency_schedule',
    label: '频次窗口（天）',
    sdkPath: 'adgroup.frequency_schedule',
    level, channel, apiVersion,
    type: 'number',
    group: 'schedule',
    excludeFromCreate: true,
  },

  // ───────────── 定向 ─────────────
  {
    name: 'location_ids',
    label: '投放地区',
    sdkPath: 'adgroup.location_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    required: true,
    group: 'targeting',
    hideInUi: true,  // Phase 2.M: 由 GeoLocationField 接管
    options: TIKTOK_LOCATIONS,
    legacyStateKey: 'selectedLocations',
  },
  {
    name: 'languages',
    label: '语言',
    sdkPath: 'adgroup.languages',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: 'en', label: 'English' }, { value: 'zh', label: '中文' },
      { value: 'ja', label: '日本語' }, { value: 'ko', label: '한국어' },
      { value: 'es', label: 'Español' }, { value: 'fr', label: 'Français' },
      { value: 'de', label: 'Deutsch' }, { value: 'pt', label: 'Português' },
      { value: 'it', label: 'Italiano' }, { value: 'ar', label: 'العربية' },
      { value: 'ru', label: 'Русский' }, { value: 'th', label: 'ไทย' },
      { value: 'vi', label: 'Tiếng Việt' }, { value: 'id', label: 'Bahasa Indonesia' },
    ],
    legacyStateKey: 'selectedLanguage',
  },
  {
    name: 'gender',
    label: '性别',
    sdkPath: 'adgroup.gender',
    level, channel, apiVersion,
    type: 'select',
    group: 'targeting',
    options: [
      { value: 'GENDER_UNLIMITED', label: '不限' },
      { value: 'GENDER_MALE',      label: '男' },
      { value: 'GENDER_FEMALE',    label: '女' },
    ],
    defaultValue: 'GENDER_UNLIMITED',
  },
  {
    name: 'age_groups',
    label: '年龄段',
    sdkPath: 'adgroup.age_groups',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: 'AGE_13_17',  label: '13-17' },
      { value: 'AGE_18_24',  label: '18-24' },
      { value: 'AGE_25_34',  label: '25-34' },
      { value: 'AGE_35_44',  label: '35-44' },
      { value: 'AGE_45_54',  label: '45-54' },
      { value: 'AGE_55_100', label: '55+' },
    ],
  },
  {
    name: 'spending_power',
    label: '消费能力',
    sdkPath: 'adgroup.spending_power',
    level, channel, apiVersion,
    type: 'select',
    group: 'targeting',
    options: [
      { value: 'ALL',  label: '全部' },
      { value: 'HIGH', label: '高消费人群' },
    ],
  },
  {
    name: 'household_income',
    label: '家庭收入',
    sdkPath: 'adgroup.household_income',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: 'TOP_5',  label: '前 5%' },
      { value: 'TOP_10', label: '前 6-10%' },
      { value: 'TOP_25', label: '前 11-25%' },
      { value: 'TOP_50', label: '前 26-50%' },
    ],
  },
  {
    name: 'audience_ids',
    label: '受众（包含）',
    sdkPath: 'adgroup.audience_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_AUDIENCES,
    group: 'targeting',
    mutuallyExclusiveWith: ['excluded_audience_ids'],
  },
  {
    name: 'excluded_audience_ids',
    label: '受众（排除）',
    sdkPath: 'adgroup.excluded_audience_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_AUDIENCES,
    group: 'targeting',
  },
  {
    name: 'interest_keyword_ids',
    label: '兴趣关键词',
    sdkPath: 'adgroup.interest_keyword_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_INTEREST_KEYWORDS,
    group: 'targeting',
  },
  {
    name: 'interest_category_ids',
    label: '兴趣类别',
    sdkPath: 'adgroup.interest_category_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_INTEREST_CATEGORIES,
    group: 'targeting',
  },
  // Phase 2.L: JSON → composite，4 个子字段（动作类目 / 时间窗口 / 场景 / 用户动作）
  {
    name: 'video_actions_v2',
    label: '视频互动定向',
    sdkPath: 'adgroup.actions',
    level, channel, apiVersion,
    type: 'composite',
    group: 'targeting',
    helpText: '基于用户对视频内容的互动行为定向。',
    subFields: [
      { name: 'action_category_ids', label: '动作类目', sdkPath: 'action_category_ids', level, channel, apiVersion,
        type: 'multiselect', options: TIKTOK_INTEREST_CATEGORIES,
        helpText: '触发用户互动的内容类别。' },
      { name: 'action_period',  label: '时间窗口（天）', sdkPath: 'action_period', level, channel, apiVersion,
        type: 'select',
        options: [
          { value: 7,  label: '近 7 天' },
          { value: 15, label: '近 15 天' },
          { value: 30, label: '近 30 天' },
          { value: 60, label: '近 60 天' },
          { value: 180, label: '近 180 天' },
        ] },
      { name: 'action_scene', label: '场景', sdkPath: 'action_scene', level, channel, apiVersion,
        type: 'multiselect',
        options: [
          { value: 'VIDEO_RELATED',   label: '视频相关' },
          { value: 'CREATOR_RELATED', label: '创作者相关' },
          { value: 'HASHTAG_RELATED', label: '标签相关' },
        ] },
      { name: 'video_user_actions', label: '用户动作', sdkPath: 'video_user_actions', level, channel, apiVersion,
        type: 'multiselect',
        options: [
          { value: 'WATCHED_TO_END', label: '完整观看' },
          { value: 'LIKED',          label: '点赞' },
          { value: 'COMMENTED',      label: '评论' },
          { value: 'SHARED',         label: '分享' },
        ] },
    ],
  },
  {
    name: 'included_custom_actions',
    label: '自定义行为（包含）',
    sdkPath: 'adgroup.included_custom_actions',
    level, channel, apiVersion,
    type: 'json',
    group: 'targeting',
    excludeFromCreate: true,
  },
  {
    name: 'excluded_custom_actions',
    label: '自定义行为（排除）',
    sdkPath: 'adgroup.excluded_custom_actions',
    level, channel, apiVersion,
    type: 'json',
    group: 'targeting',
    excludeFromCreate: true,
  },
  {
    name: 'device_price_ranges',
    label: '设备价格区间',
    sdkPath: 'adgroup.device_price_ranges',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: '0-99',     label: '< $100' },
      { value: '100-299',  label: '$100 - $299' },
      { value: '300-599',  label: '$300 - $599' },
      { value: '600-999',  label: '$600 - $999' },
      { value: '1000+',    label: '$1000+' },
    ],
  },
  {
    name: 'operating_systems',
    label: '操作系统',
    sdkPath: 'adgroup.operating_systems',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: 'ANDROID', label: 'Android' },
      { value: 'IOS',     label: 'iOS' },
    ],
  },
  {
    name: 'min_android_version',
    label: 'Android 最低版本',
    sdkPath: 'adgroup.min_android_version',
    level, channel, apiVersion,
    type: 'select',
    group: 'targeting',
    options: [
      { value: 'ANDROID_4_0',  label: '4.0+' }, { value: 'ANDROID_5_0',  label: '5.0+' },
      { value: 'ANDROID_6_0',  label: '6.0+' }, { value: 'ANDROID_7_0',  label: '7.0+' },
      { value: 'ANDROID_8_0',  label: '8.0+' }, { value: 'ANDROID_9_0',  label: '9.0+' },
      { value: 'ANDROID_10_0', label: '10.0+' }, { value: 'ANDROID_11_0', label: '11.0+' },
    ],
    dependsOn: { field: 'operating_systems',
      predicate: (v) => Array.isArray(v) && v.includes('ANDROID') },
  },
  {
    name: 'min_ios_version',
    label: 'iOS 最低版本',
    sdkPath: 'adgroup.min_ios_version',
    level, channel, apiVersion,
    type: 'text',
    group: 'targeting',
    placeholder: '例：14.0',
    dependsOn: { field: 'operating_systems',
      predicate: (v) => Array.isArray(v) && v.includes('IOS') },
  },
  {
    name: 'device_model_ids',
    label: '设备型号',
    sdkPath: 'adgroup.device_model_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_DEVICE_MODELS,
    group: 'targeting',
  },
  {
    name: 'network_types',
    label: '网络类型',
    sdkPath: 'adgroup.network_types',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: 'WIFI', label: 'Wi-Fi' }, { value: '2G', label: '2G' },
      { value: '3G',   label: '3G' },    { value: '4G', label: '4G' },
      { value: '5G',   label: '5G' },
    ],
  },
  {
    name: 'isp_ids',
    label: 'ISP',
    sdkPath: 'adgroup.isp_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_ISPS,
    group: 'targeting',
  },
  {
    name: 'carrier_ids',
    label: '运营商',
    sdkPath: 'adgroup.carrier_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_CARRIERS,
    group: 'targeting',
  },
  {
    name: 'pangle_audience_package_ids',
    label: 'Pangle 受众包',
    sdkPath: 'adgroup.pangle_audience_package_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_PANGLE_AUDIENCE_PACKAGES,
    group: 'targeting',
    dependsOn: { field: 'placements',
      predicate: (v) => Array.isArray(v) && v.includes('PLACEMENT_PANGLE') },
  },
  {
    name: 'pangle_block_app_list_id',
    label: 'Pangle 屏蔽应用 ID',
    sdkPath: 'adgroup.pangle_block_app_list_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'targeting',
    dependsOn: { field: 'placements',
      predicate: (v) => Array.isArray(v) && v.includes('PLACEMENT_PANGLE') },
    excludeFromCreate: true,
  },
  {
    name: 'audience_rule',
    label: '受众规则',
    sdkPath: 'adgroup.audience_rule',
    level, channel, apiVersion,
    type: 'json',
    group: 'targeting',
    excludeFromCreate: true,
  },
  {
    name: 'auto_targeting_enabled',
    label: '智能受众扩展',
    sdkPath: 'adgroup.auto_targeting_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'targeting',
  },

  // ───────────── 高级 ─────────────
  {
    name: 'creative_material_mode',
    label: '创意素材模式',
    sdkPath: 'adgroup.creative_material_mode',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'CUSTOM',         label: '手动（每广告独立）' },
      { value: 'DYNAMIC',        label: '动态创意优化' },
      { value: 'SMART_CREATIVE', label: '智能创意' },
    ],
  },
  {
    name: 'feed_type',
    label: 'Feed 类型',
    sdkPath: 'adgroup.feed_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'CUSTOMIZED_GRADUATED_RANK', label: '自定义分级排序' },
      { value: 'INTELLIGENT',               label: '智能' },
    ],
  },
  {
    name: 'comment_disabled',
    label: '禁止评论',
    sdkPath: 'adgroup.comment_disabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
  },
  {
    name: 'video_download_disabled',
    label: '禁止视频下载',
    sdkPath: 'adgroup.video_download_disabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
  },
  {
    name: 'share_disabled',
    label: '禁止分享',
    sdkPath: 'adgroup.share_disabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
  },
  {
    name: 'app_profile_page_state',
    label: '应用主页状态',
    sdkPath: 'adgroup.app_profile_page_state',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [{ value: 'ON', label: '启用' }, { value: 'OFF', label: '禁用' }],
    excludeFromCreate: true,
  },
  {
    name: 'brand_safety_type',
    label: '品牌安全等级',
    sdkPath: 'adgroup.brand_safety_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'NO_BRAND_SAFETY',    label: '不启用' },
      { value: 'FULL_INVENTORY',     label: '完整库存' },
      { value: 'STANDARD_INVENTORY', label: '标准库存' },
      { value: 'LIMITED_INVENTORY',  label: '严格库存' },
      { value: 'EXPANDED_INVENTORY', label: '扩展库存' },
    ],
  },
  {
    name: 'brand_safety_partner',
    label: '品牌安全合作方',
    sdkPath: 'adgroup.brand_safety_partner',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'IAS',           label: 'IAS' },
      { value: 'OPEN_SLATE',    label: 'OpenSlate' },
      { value: 'DOUBLE_VERIFY', label: 'DoubleVerify' },
      { value: 'ZEFR',          label: 'Zefr' },
    ],
  },
  {
    name: 'category_id',
    label: '类目 ID',
    sdkPath: 'adgroup.category_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'product_source',
    label: '商品来源',
    sdkPath: 'adgroup.product_source',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'STORE',    label: 'TikTok 店铺' },
      { value: 'CATALOG',  label: '商品目录' },
      { value: 'SHOWCASE', label: '橱窗' },
    ],
  },
  {
    name: 'product_set_id',
    label: '商品集',
    sdkPath: 'adgroup.product_set_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_PRODUCT_SETS,
    group: 'advanced',
  },
  {
    name: 'shopping_ads_type',
    label: '购物广告类型',
    sdkPath: 'adgroup.shopping_ads_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'VIDEO',           label: '视频购物广告' },
      { value: 'CATALOG_LISTING', label: '目录列表' },
      { value: 'LIVE',            label: '直播购物' },
    ],
  },
  {
    name: 'inventory_filter_enabled',
    label: '库存过滤',
    sdkPath: 'adgroup.inventory_filter_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
  },
  {
    name: 'product_specific_type',
    label: '商品筛选方式',
    sdkPath: 'adgroup.product_specific_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'ALL_PRODUCTS',        label: '全部商品' },
      { value: 'CUSTOMIZED_PRODUCTS', label: '自定义商品' },
      { value: 'DYNAMIC_PRODUCTS',    label: '动态商品' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'item_group_ids',
    label: '商品组 ID',
    sdkPath: 'adgroup.item_group_ids',
    level, channel, apiVersion,
    type: 'tags',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'rf_purchased_type',
    label: 'R&F 购买类型',
    sdkPath: 'adgroup.rf_purchased_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'BUYOUT',    label: '买断' },
      { value: 'CPM_BASED', label: '按 CPM' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'reach_frequency_settings',
    label: 'R&F 设置',
    sdkPath: 'adgroup.reach_frequency_settings',
    level, channel, apiVersion,
    type: 'json',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'split_test_group_id',
    label: '拆分测试组 ID',
    sdkPath: 'adgroup.split_test_group_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  // Phase 2.L: JSON → composite，3 个 switch 子字段（年龄 / 性别 / 兴趣扩展）
  {
    name: 'targeting_expansion',
    label: '定向扩展',
    sdkPath: 'adgroup.targeting_expansion',
    level, channel, apiVersion,
    type: 'composite',
    group: 'targeting',
    helpText: '允许 TikTok 在指定的年龄 / 性别 / 兴趣关键词之外触达更优受众。',
    subFields: [
      { name: 'expansion_enabled_for_age',     label: '年龄扩展',   sdkPath: 'expansion_enabled_for_age',     level, channel, apiVersion, type: 'switch' },
      { name: 'expansion_enabled_for_gender',  label: '性别扩展',   sdkPath: 'expansion_enabled_for_gender',  level, channel, apiVersion, type: 'switch' },
      { name: 'expansion_enabled_for_interest_keyword', label: '兴趣关键词扩展', sdkPath: 'expansion_enabled_for_interest_keyword', level, channel, apiVersion, type: 'switch' },
    ],
  },

  // ═════════════ Phase 2.L 新增（SDK AdgroupCreateBody 验证） ═════════════
  {
    name: 'secondary_optimization_event',
    label: '次级优化事件',
    sdkPath: 'adgroup.secondary_optimization_event',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'PURCHASE',         label: '购买' },
      { value: 'COMPLETE_PAYMENT', label: '完成支付' },
      { value: 'PLACE_AN_ORDER',   label: '下单' },
      { value: 'INITIATE_CHECKOUT',label: '开始结账' },
      { value: 'ADD_TO_CART',      label: '加入购物车' },
      { value: 'ADD_PAYMENT_INFO', label: '添加支付信息' },
    ],
    helpText: '深度出价时（deep_bid_type=DEEP_VALUE）的次级优化事件。',
    dependsOn: { field: 'deep_bid_type', in: ['DEEP_VALUE', 'VO_MIN_ROAS', 'VO_HIGHEST_VALUE'] },
  },
  {
    name: 'audience_type',
    label: '受众类型',
    sdkPath: 'adgroup.audience_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'targeting',
    options: [
      { value: 'NORMAL',            label: '常规受众' },
      { value: 'EXISTING_CUSTOMER', label: '已有客户' },
      { value: 'ENGAGED_AUDIENCE',  label: '已互动受众' },
    ],
  },
  {
    name: 'tiktok_subplacements',
    label: 'TikTok 子版位',
    sdkPath: 'adgroup.tiktok_subplacements',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [
      { value: 'IN_FEED',  label: 'In-Feed 信息流' },
      { value: 'TOP_VIEW', label: 'TopView 开屏' },
    ],
    helpText: 'TikTok 主版位下的子版位（仅 placements 含 PLACEMENT_TIKTOK 时可见）。',
    dependsOn: { field: 'placements',
      predicate: (v) => Array.isArray(v) && v.includes('PLACEMENT_TIKTOK') },
  },
  {
    name: 'zipcode_ids',
    label: '邮编定向',
    sdkPath: 'adgroup.zipcode_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [],  // 由 platformResources zipcode 资源派生（实施时填充）
    helpText: '美国 / 英国 / 加拿大等支持邮编定向的地区使用。',
  },
  {
    name: 'contextual_tag_ids',
    label: '上下文标签',
    sdkPath: 'adgroup.contextual_tag_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'targeting',
    options: [],  // 由 platformResources contextual tag 派生
    helpText: 'NEW v1.3+：基于上下文内容的精细化定向。',
  },
  {
    name: 'bid_display_mode',
    label: '出价展示模式',
    sdkPath: 'adgroup.bid_display_mode',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'STANDARD', label: '标准' },
      { value: 'COMPACT',  label: '简洁' },
    ],
    excludeFromCreate: true,
  },
];

export default fields;
