/**
 * TikTok Business API v1.3 — Campaign 创建/更新可写字段
 * Reference: POST /open_api/v1.3/campaign/create/
 *
 * Phase 2.C：catalog/store 改 select。
 */

import { TIKTOK_CATALOGS, TIKTOK_STORES, TIKTOK_APPS } from '../services/platformResources';

const channel = 'tiktok';
const level = 'campaign';
const apiVersion = 'tiktok-v1.3';

/** @type {import('./schema').FieldDef[]} */
const fields = [
  {
    name: 'campaign_name',
    label: '系列名称',
    sdkPath: 'campaign.campaign_name',
    level, channel, apiVersion,
    type: 'text',
    customRenderer: 'nameTemplate',
    required: true,
    group: 'basic',
    validation: { max: 512 },
  },
  {
    name: 'campaign_type',
    label: '系列类型',
    sdkPath: 'campaign.campaign_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'REGULAR_CAMPAIGN', label: '常规系列' },
      { value: 'IOS_14_CAMPAIGN',  label: 'iOS 14 专用系列' },
    ],
    defaultValue: 'REGULAR_CAMPAIGN',
  },
  {
    name: 'objective_type',
    label: '推广目标',
    sdkPath: 'campaign.objective_type',
    level, channel, apiVersion,
    type: 'select',
    required: true,
    group: 'basic',
    helpText: '决定后续 AdGroup 优化目标可选范围。',
    options: [
      { value: 'REACH',                 label: '触达' },
      { value: 'TRAFFIC',               label: '流量' },
      { value: 'VIDEO_VIEWS',           label: '视频观看' },
      { value: 'COMMUNITY_INTERACTION', label: '社区互动' },
      { value: 'LEAD_GENERATION',       label: '潜在客户' },
      { value: 'WEB_CONVERSIONS',       label: '网站转化' },
      { value: 'PRODUCT_SALES',         label: '商品销售' },
      { value: 'APP_PROMOTION',         label: '应用推广' },
      { value: 'ENGAGEMENT',            label: '互动' },
      { value: 'SHOP_PURCHASES',        label: 'TikTok Shop 购买' },
    ],
    legacyStateKey: 'objective',
  },
  {
    name: 'app_promotion_type',
    label: '应用推广子类型',
    sdkPath: 'campaign.app_promotion_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'APP_INSTALL',     label: '应用安装' },
      { value: 'APP_RETARGETING', label: '应用再营销' },
    ],
    dependsOn: { field: 'objective_type', equals: 'APP_PROMOTION' },
    requiredWhen: (_, root) => root?.campaign?.objective_type === 'APP_PROMOTION',
  },
  {
    name: 'special_industries',
    label: '特殊行业',
    sdkPath: 'campaign.special_industries',
    level, channel, apiVersion,
    type: 'multiselect',
    group: 'basic',
    options: [
      { value: 'EMPLOYMENT', label: '就业' },
      { value: 'HOUSING',    label: '住房' },
      { value: 'CREDIT',     label: '信贷' },
    ],
  },
  {
    name: 'operation_status',
    label: '初始状态',
    sdkPath: 'campaign.operation_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'ENABLE',  label: '启用' },
      { value: 'DISABLE', label: '禁用' },
    ],
    defaultValue: 'DISABLE',
    excludeFromCreate: true,
  },

  // ───────────── 出价与预算 ─────────────
  {
    name: 'budget_mode',
    label: '预算模式',
    sdkPath: 'campaign.budget_mode',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'BUDGET_MODE_INFINITE', label: '无限制' },
      { value: 'BUDGET_MODE_DAY',      label: '日预算' },
      { value: 'BUDGET_MODE_TOTAL',    label: '总预算' },
    ],
    defaultValue: 'BUDGET_MODE_DAY',
  },
  {
    name: 'budget',
    label: '系列预算',
    sdkPath: 'campaign.budget',
    level, channel, apiVersion,
    type: 'currency',
    group: 'bidding',
    helpText: 'budget_mode 为 DAY 或 TOTAL 时必填。系列预算 ≥ 50 USD。',
    validation: { min: 50 },
    dependsOn: { field: 'budget_mode', in: ['BUDGET_MODE_DAY', 'BUDGET_MODE_TOTAL'] },
    requiredWhen: (_, root) => ['BUDGET_MODE_DAY', 'BUDGET_MODE_TOTAL']
      .includes(root?.campaign?.budget_mode),
    legacyStateKey: 'dailyBudget',
  },
  {
    name: 'budget_optimize_on',
    label: '系列预算优化（CBO）',
    sdkPath: 'campaign.budget_optimize_on',
    level, channel, apiVersion,
    type: 'switch',
    group: 'bidding',
  },
  {
    name: 'bid_type',
    label: '系列出价类型',
    sdkPath: 'campaign.bid_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'BID_TYPE_NO_BID', label: '最低成本' },
      { value: 'BID_TYPE_CUSTOM', label: '成本上限' },
    ],
    dependsOn: { field: 'budget_optimize_on', equals: true },
  },
  {
    name: 'optimization_goal',
    label: '系列优化目标',
    sdkPath: 'campaign.optimization_goal',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    helpText: 'CBO 启用时必填。',
    options: [
      { value: 'CONVERT',      label: '转化' }, { value: 'INSTALL',      label: '安装' },
      { value: 'IN_APP_EVENT', label: '应用内事件' }, { value: 'VALUE',    label: '价值（ROAS）' },
      { value: 'CLICK',        label: '点击' }, { value: 'REACH',        label: '触达' },
      { value: 'SHOW',         label: '展示' }, { value: 'VIDEO_VIEW',   label: '视频观看' },
      { value: 'ENGAGED_VIEW', label: '完成观看' }, { value: 'LIVE_VIEW', label: '直播观看' },
    ],
    dependsOn: { field: 'budget_optimize_on', equals: true },
    requiredWhen: (_, root) => !!root?.campaign?.budget_optimize_on,
  },
  {
    name: 'deep_bid_type',
    label: '深度优化出价类型',
    sdkPath: 'campaign.deep_bid_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'VO_MIN_ROAS',      label: '最低 ROAS（VO_MIN_ROAS）' },
      { value: 'VO_HIGHEST_VALUE', label: '最高价值' },
    ],
  },
  {
    name: 'roas_bid',
    label: 'ROAS 目标值',
    sdkPath: 'campaign.roas_bid',
    level, channel, apiVersion,
    type: 'number',
    group: 'bidding',
    validation: { min: 0.01 },
    dependsOn: { field: 'deep_bid_type', equals: 'VO_MIN_ROAS' },
    requiredWhen: (_, root) => root?.campaign?.deep_bid_type === 'VO_MIN_ROAS',
  },

  // ───────────── 高级 ─────────────
  // Phase 2.L: 9 个 API-only / 合作方 / 内部字段加 excludeFromCreate
  {
    name: 'rf_buy_type',
    label: '购买类型',
    sdkPath: 'campaign.rf_buy_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'AUCTION', label: '竞价' },
      { value: 'RF',      label: 'Reach & Frequency 预定' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'rta_id',
    label: 'RTA ID',
    sdkPath: 'campaign.rta_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'rta_product_selection_enabled',
    label: 'RTA 商品筛选',
    sdkPath: 'campaign.rta_product_selection_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'campaign_app_profile_page_state',
    label: '应用主页状态',
    sdkPath: 'campaign.campaign_app_profile_page_state',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [{ value: 'ON', label: '启用' }, { value: 'OFF', label: '禁用' }],
    excludeFromCreate: true,
  },
  {
    name: 'campaign_product_source',
    label: '商品来源',
    sdkPath: 'campaign.campaign_product_source',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'STORE',    label: 'TikTok 店铺' },
      { value: 'CATALOG',  label: '商品目录' },
      { value: 'SHOWCASE', label: '橱窗' },
    ],
  },
  {
    name: 'catalog_id',
    label: '商品目录',
    sdkPath: 'campaign.catalog_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_CATALOGS,
    group: 'advanced',
    dependsOn: { field: 'campaign_product_source', equals: 'CATALOG' },
    requiredWhen: (_, root) => root?.campaign?.campaign_product_source === 'CATALOG',
  },
  {
    name: 'store_id',
    label: 'TikTok 店铺',
    sdkPath: 'campaign.store_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_STORES,
    group: 'advanced',
    dependsOn: { field: 'campaign_product_source', equals: 'STORE' },
    requiredWhen: (_, root) => root?.campaign?.campaign_product_source === 'STORE',
  },
  {
    name: 'is_smart_performance_campaign',
    label: '智能性能系列',
    sdkPath: 'campaign.is_smart_performance_campaign',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'is_advanced_dedicated_campaign',
    label: '高级专属系列',
    sdkPath: 'campaign.is_advanced_dedicated_campaign',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'rf_campaign_type',
    label: 'R&F 系列子类型',
    sdkPath: 'campaign.rf_campaign_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'STANDARD', label: '标准' },
      { value: 'TOPVIEW',  label: 'TopView' },
    ],
    dependsOn: { field: 'rf_buy_type', equals: 'RF' },
    excludeFromCreate: true,
  },
  {
    name: 'postback_window_mode',
    label: '回传窗口模式',
    sdkPath: 'campaign.postback_window_mode',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'POSTBACK_WINDOW_TYPE_1', label: '类型 1' },
      { value: 'POSTBACK_WINDOW_TYPE_2', label: '类型 2' },
      { value: 'POSTBACK_WINDOW_TYPE_3', label: '类型 3' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'sales_destination',
    label: '销售目的地',
    sdkPath: 'campaign.sales_destination',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'WEBSITE',         label: '网站' },
      { value: 'APP',             label: '应用' },
      { value: 'TIKTOK_SHOP',     label: 'TikTok Shop' },
      { value: 'WEBSITE_AND_APP', label: '网站 + 应用' },
    ],
    excludeFromCreate: true,
  },

  // ═════════════ Phase 2.L 新增（SDK CampaignCreateBody 验证） ═════════════
  {
    name: 'bid_type',
    label: '系列出价类型',
    sdkPath: 'campaign.bid_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'bidding',
    options: [
      { value: 'BID_TYPE_NO_BID',         label: '无出价上限（最大转化量）' },
      { value: 'BID_TYPE_CUSTOM',         label: '自定义出价上限' },
      { value: 'BID_TYPE_MAX_CONVERSION', label: '最大转化（系统调价）' },
    ],
  },
  {
    name: 'app_id',
    label: '推广应用',
    sdkPath: 'campaign.app_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_APPS,
    group: 'basic',
    helpText: '应用推广目标时，选择被推广的 app（与 adset.app_id 同步）。',
    dependsOn: { field: 'objective_type', equals: 'APP_PROMOTION' },
  },
  {
    name: 'catalog_enabled',
    label: '启用商品目录',
    sdkPath: 'campaign.catalog_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
  },
  {
    name: 'disable_skan_campaign',
    label: '禁用 SKAdNetwork',
    sdkPath: 'campaign.disable_skan_campaign',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    helpText: 'iOS 14.5+ SKAN 归因开关；适配某些 MMP 配置时使用。',
  },
  {
    name: 'is_search_campaign',
    label: '搜索广告系列',
    sdkPath: 'campaign.is_search_campaign',
    level, channel, apiVersion,
    type: 'switch',
    group: 'basic',
    helpText: '启用后系列将作为 TikTok 搜索广告投放（v1.3+ Search Ads）。',
  },
  // — 内部 / 合作方字段（excludeFromCreate） —
  {
    name: 'virtual_objective_type',
    label: '虚拟目标类型',
    sdkPath: 'campaign.virtual_objective_type',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'internal_channel',
    label: '内部渠道',
    sdkPath: 'campaign.internal_channel',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'plugin_partner',
    label: '插件合作方',
    sdkPath: 'campaign.plugin_partner',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'request_id',
    label: '请求幂等 ID',
    sdkPath: 'campaign.request_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'po_number',
    label: 'PO 编号',
    sdkPath: 'campaign.po_number',
    level, channel, apiVersion,
    type: 'text',
    group: 'advanced',
    excludeFromCreate: true,
  },
  {
    name: 'rta_bid_enabled',
    label: 'RTA 出价启用',
    sdkPath: 'campaign.rta_bid_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'advanced',
    excludeFromCreate: true,
  },
];

export default fields;
