/**
 * TikTok Business API v1.3 — Ad 创建/更新可写字段
 * Reference: POST /open_api/v1.3/ad/create/
 *
 * Phase 2.C：补 mock 选项 + ad_format 联动必填。
 */

import {
  TIKTOK_IDENTITIES, TIKTOK_BC_ACCOUNTS, TIKTOK_VIDEOS, TIKTOK_IMAGES,
  TIKTOK_MUSIC, TIKTOK_CARDS, TIKTOK_SPARK_POSTS, TIKTOK_INSTANT_PAGES,
  TIKTOK_BRAND_LOGOS, TIKTOK_PIXELS, TIKTOK_APPS, TIKTOK_PRODUCT_SETS,
} from '../services/platformResources';

const channel = 'tiktok';
const level = 'ad';
const apiVersion = 'tiktok-v1.3';

/** @type {import('./schema').FieldDef[]} */
const fields = [
  // ───────────── 基础 ─────────────
  {
    name: 'ad_name',
    label: '广告名称',
    sdkPath: 'ad.ad_name',
    level, channel, apiVersion,
    type: 'text',
    required: true,
    group: 'basic',
    validation: { max: 512 },
  },
  {
    name: 'ad_format',
    label: '广告形式',
    sdkPath: 'ad.ad_format',
    level, channel, apiVersion,
    type: 'select',
    required: true,
    group: 'basic',
    options: [
      { value: 'SINGLE_IMAGE',    label: '单图' },
      { value: 'SINGLE_VIDEO',    label: '单视频' },
      { value: 'CAROUSEL_ADS',    label: '轮播' },
      { value: 'CATALOG_CAROUSEL',label: '目录轮播' },
      { value: 'COLLECTION_ADS',  label: 'Collection' },
      { value: 'SPARK_ADS',       label: 'Spark Ads（推广已有帖子）' },
      { value: 'PLAYABLE_ADS',    label: '可玩广告' },
      { value: 'INSTANT_PAGE_ADS',label: '即时页面广告' },
    ],
    legacyStateKey: 'adType',
  },
  {
    name: 'identity_id',
    label: '投放身份',
    sdkPath: 'ad.identity_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_IDENTITIES,
    group: 'basic',
  },
  {
    name: 'identity_type',
    label: '身份类型',
    sdkPath: 'ad.identity_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'CUSTOMIZED_USER', label: '自定义用户' },
      { value: 'AUTH_CODE',       label: '授权码' },
      { value: 'TT_USER',         label: 'TikTok 用户' },
      { value: 'BC_AUTH_TT',      label: 'BC 授权 TikTok' },
    ],
  },
  {
    name: 'identity_authorized_bc_id',
    label: '授权商务中心（BC）',
    sdkPath: 'ad.identity_authorized_bc_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_BC_ACCOUNTS,
    group: 'basic',
    dependsOn: { field: 'identity_type', equals: 'BC_AUTH_TT' },
  },
  {
    name: 'operation_status',
    label: '初始状态',
    sdkPath: 'ad.operation_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'basic',
    options: [
      { value: 'ENABLE',  label: '启用' },
      { value: 'DISABLE', label: '禁用' },
    ],
    defaultValue: 'DISABLE',
    excludeFromCreate: true,
  },

  // ───────────── 创意 ─────────────
  {
    name: 'ad_text',
    label: '广告文案',
    sdkPath: 'ad.ad_text',
    level, channel, apiVersion,
    type: 'textarea',
    group: 'creative',
    validation: { max: 100 },
    helpText: 'Phase 2.M：在产品模块「📝 文案」per 素材组配置。',
    excludeFromCreate: true,
  },
  {
    name: 'ad_texts',
    label: '多文案（DCO）',
    sdkPath: 'ad.ad_texts',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    helpText: '动态创意优化用文案数组。',
    excludeFromCreate: true,
  },
  {
    name: 'video_id',
    label: '视频素材',
    sdkPath: 'ad.video_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_VIDEOS,
    group: 'creative',
    dependsOn: { field: 'ad_format', in: ['SINGLE_VIDEO', 'SPARK_ADS'] },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'SINGLE_VIDEO',
  },
  {
    name: 'image_ids',
    label: '图片素材',
    sdkPath: 'ad.image_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_IMAGES,
    group: 'creative',
    dependsOn: { field: 'ad_format', in: ['SINGLE_IMAGE', 'CAROUSEL_ADS', 'CATALOG_CAROUSEL', 'COLLECTION_ADS'] },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'SINGLE_IMAGE',
  },
  {
    name: 'avatar_icon_web_uri',
    label: '头像 URI',
    sdkPath: 'ad.avatar_icon_web_uri',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
  },
  {
    name: 'display_name',
    label: '显示名称',
    sdkPath: 'ad.display_name',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    validation: { max: 40 },
    excludeFromCreate: true,
  },
  {
    name: 'app_name',
    label: '应用名称',
    sdkPath: 'ad.app_name',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
  },
  {
    name: 'music_id',
    label: '音乐',
    sdkPath: 'ad.music_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_MUSIC,
    group: 'creative',
  },
  {
    name: 'card_id',
    label: '互动卡片',
    sdkPath: 'ad.card_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_CARDS,
    group: 'creative',
  },
  {
    name: 'item_duet_status',
    label: '允许合拍',
    sdkPath: 'ad.item_duet_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [{ value: 'ENABLE', label: '启用' }, { value: 'DISABLE', label: '禁用' }],
  },
  {
    name: 'item_stitch_status',
    label: '允许 Stitch',
    sdkPath: 'ad.item_stitch_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [{ value: 'ENABLE', label: '启用' }, { value: 'DISABLE', label: '禁用' }],
  },
  {
    name: 'is_aco',
    label: '自动创意优化',
    sdkPath: 'ad.is_aco',
    level, channel, apiVersion,
    type: 'switch',
    group: 'creative',
  },
  {
    name: 'creative_authorized',
    label: '创意授权',
    sdkPath: 'ad.creative_authorized',
    level, channel, apiVersion,
    type: 'switch',
    group: 'creative',
  },
  {
    name: 'tiktok_item_id',
    label: 'TikTok 帖子（Spark Ads）',
    sdkPath: 'ad.tiktok_item_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_SPARK_POSTS,
    group: 'creative',
    dependsOn: { field: 'ad_format', equals: 'SPARK_ADS' },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'SPARK_ADS',
  },
  {
    name: 'product_specific_type',
    label: '商品筛选方式',
    sdkPath: 'ad.product_specific_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'ALL_PRODUCTS',        label: '全部' },
      { value: 'CUSTOMIZED_PRODUCTS', label: '自定义' },
      { value: 'DYNAMIC_PRODUCTS',    label: '动态' },
    ],
  },
  {
    name: 'item_group_ids',
    label: '商品组',
    sdkPath: 'ad.item_group_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: TIKTOK_PRODUCT_SETS,
    group: 'creative',
  },
  {
    name: 'sku_ids',
    label: 'SKU ID',
    sdkPath: 'ad.sku_ids',
    level, channel, apiVersion,
    type: 'tags',
    group: 'creative',
  },
  {
    name: 'showcase_products',
    label: '橱窗商品',
    sdkPath: 'ad.showcase_products',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'dark_post_status',
    label: '暗推（Dark Post）',
    sdkPath: 'ad.dark_post_status',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [{ value: 'ON', label: '启用' }, { value: 'OFF', label: '禁用' }],
  },
  {
    name: 'page_id',
    label: '即时页',
    sdkPath: 'ad.page_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_INSTANT_PAGES,
    group: 'creative',
    dependsOn: { field: 'ad_format', equals: 'INSTANT_PAGE_ADS' },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'INSTANT_PAGE_ADS',
  },
  {
    name: 'playable_url',
    label: '可玩广告 URL',
    sdkPath: 'ad.playable_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
    dependsOn: { field: 'ad_format', equals: 'PLAYABLE_ADS' },
    requiredWhen: (_, root) => root?.ad?.ad_format === 'PLAYABLE_ADS',
  },
  {
    name: 'vertical_video_strategy',
    label: '竖屏视频策略',
    sdkPath: 'ad.vertical_video_strategy',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'NONE',      label: '无' },
      { value: 'AUTOMATIC', label: '自动' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'auto_message_id',
    label: '自动消息 ID',
    sdkPath: 'ad.auto_message_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'brand_logo_id',
    label: '品牌 Logo',
    sdkPath: 'ad.brand_logo_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_BRAND_LOGOS,
    group: 'creative',
  },
  {
    name: 'cta_text',
    label: '行动号召文案',
    sdkPath: 'ad.cta_text',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'call_to_action',
    label: '行动号召按钮',
    sdkPath: 'ad.call_to_action',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    excludeFromCreate: true,
    options: [
      { value: 'APPLY_NOW',         label: '立即申请' },
      { value: 'BOOK_NOW',          label: '立即预订' },
      { value: 'CONTACT_US',        label: '联系我们' },
      { value: 'DOWNLOAD_NOW',      label: '立即下载' },
      { value: 'EXPERIENCE_NOW',    label: '立即体验' },
      { value: 'GET_QUOTE',         label: '获取报价' },
      { value: 'GET_TICKETS_NOW',   label: '立即购票' },
      { value: 'INSTALL_NOW',       label: '立即安装' },
      { value: 'INTERESTED',        label: '感兴趣' },
      { value: 'LEARN_MORE',        label: '了解更多' },
      { value: 'LISTEN_NOW',        label: '立即收听' },
      { value: 'ORDER_NOW',         label: '立即订购' },
      { value: 'PLAY_GAME',         label: '玩游戏' },
      { value: 'PREORDER_NOW',      label: '立即预订' },
      { value: 'READ_MORE',         label: '阅读更多' },
      { value: 'SHOP_NOW',          label: '立即购买' },
      { value: 'SIGN_UP',           label: '立即注册' },
      { value: 'SUBSCRIBE',         label: '订阅' },
      { value: 'VIEW_NOW',          label: '立即查看' },
      { value: 'VIEW_PROFILE',      label: '查看主页' },
      { value: 'VISIT_STORE',       label: '访问店铺' },
      { value: 'WATCH_LIVE',        label: '观看直播' },
      { value: 'WATCH_NOW',         label: '立即观看' },
      { value: 'SEND_MESSAGE',      label: '发送消息' },
    ],
  },
  {
    name: 'call_to_action_id',
    label: '动态 CTA ID',
    sdkPath: 'ad.call_to_action_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
  },
  {
    name: 'landing_page_url',
    label: '落地页 URL',
    sdkPath: 'ad.landing_page_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
    excludeFromCreate: true,  // Phase 2.M：由产品模块「📝 文案」per 素材组配置
  },
  {
    name: 'landing_page_urls',
    label: '多落地页 URL',
    sdkPath: 'ad.landing_page_urls',
    level, channel, apiVersion,
    type: 'json',
    group: 'creative',
    excludeFromCreate: true,
  },
  {
    name: 'deeplink',
    label: '深链',
    sdkPath: 'ad.deeplink',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
  },
  {
    name: 'deeplink_type',
    label: '深链类型',
    sdkPath: 'ad.deeplink_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'NORMAL',   label: '普通' },
      { value: 'DEFERRED', label: '延迟（Deferred）' },
    ],
  },
  {
    name: 'fallback_type',
    label: '降级类型',
    sdkPath: 'ad.fallback_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'WEB',          label: 'Web' },
      { value: 'APP_DOWNLOAD', label: '应用下载' },
    ],
  },
  {
    name: 'phone_region_calling_code',
    label: '电话区号',
    sdkPath: 'ad.phone_region_calling_code',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    dependsOn: { field: 'call_to_action', equals: 'CONTACT_US' },
    requiredWhen: (_, root) => root?.ad?.call_to_action === 'CONTACT_US',
  },
  {
    name: 'phone_number',
    label: '电话号码',
    sdkPath: 'ad.phone_number',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    dependsOn: { field: 'call_to_action', equals: 'CONTACT_US' },
    requiredWhen: (_, root) => root?.ad?.call_to_action === 'CONTACT_US',
  },
  {
    name: 'profile_image_url',
    label: '主页图片 URL',
    sdkPath: 'ad.profile_image_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'creative',
  },
  {
    name: 'is_creative_authorized',
    label: '创意已授权（Spark）',
    sdkPath: 'ad.is_creative_authorized',
    level, channel, apiVersion,
    type: 'switch',
    group: 'creative',
    excludeFromCreate: true,
  },

  // ───────────── 跟踪 ─────────────
  {
    name: 'utm_params',
    label: 'UTM 参数',
    sdkPath: 'ad.utm_params',
    level, channel, apiVersion,
    type: 'json',
    group: 'tracking',
    helpText: '数组：[{ key, value }]。',
    excludeFromCreate: true,
  },
  {
    name: 'tracking_pixel_id',
    label: '跟踪像素',
    sdkPath: 'ad.tracking_pixel_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_PIXELS,
    group: 'tracking',
  },
  {
    name: 'tracking_app_id',
    label: '跟踪应用',
    sdkPath: 'ad.tracking_app_id',
    level, channel, apiVersion,
    type: 'select',
    options: TIKTOK_APPS,
    group: 'tracking',
  },
  {
    name: 'click_tracking_url',
    label: '点击跟踪 URL',
    sdkPath: 'ad.click_tracking_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'tracking',
  },
  {
    name: 'impression_tracking_url',
    label: '展示跟踪 URL',
    sdkPath: 'ad.impression_tracking_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'tracking',
  },
  {
    name: 'tracking_message_event_url',
    label: '消息事件跟踪 URL',
    sdkPath: 'ad.tracking_message_event_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'tracking',
    excludeFromCreate: true,
  },
  {
    name: 'vast_moat_enabled',
    label: '启用 VAST MOAT',
    sdkPath: 'ad.vast_moat_enabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'tracking',
    excludeFromCreate: true,
  },
  // Phase 2.L: rename 与 SDK 对齐 — viewability_* → brand_safety_*
  {
    name: 'brand_safety_postbid_partner',
    label: '品牌安全后竞价合作方',
    sdkPath: 'ad.brand_safety_postbid_partner',
    level, channel, apiVersion,
    type: 'select',
    group: 'tracking',
    options: [
      { value: 'IAS',           label: 'IAS' },
      { value: 'DOUBLE_VERIFY', label: 'DoubleVerify' },
      { value: 'ZEFR',          label: 'Zefr' },
      { value: 'OFF',           label: '关闭' },
    ],
  },
  {
    name: 'brand_safety_vast_url',
    label: '品牌安全 VAST URL',
    sdkPath: 'ad.brand_safety_vast_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'tracking',
  },

  // ───────────── 高级 ─────────────
  {
    name: 'creative_type',
    label: '创意类型',
    sdkPath: 'ad.creative_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'CUSTOM_CREATIVE',  label: '自定义创意' },
      { value: 'CATALOG_CREATIVE', label: '目录创意' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'product_recommend_type',
    label: '商品推荐类型',
    sdkPath: 'ad.product_recommend_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'ALL_PRODUCTS', label: '全部商品' },
      { value: 'CUSTOMIZED',   label: '自定义' },
    ],
    excludeFromCreate: true,
  },
  {
    name: 'aigc_disclosure_type',
    label: 'AIGC 标识',
    sdkPath: 'ad.aigc_disclosure_type',
    level, channel, apiVersion,
    type: 'select',
    group: 'advanced',
    options: [
      { value: 'NONE',         label: '无' },
      { value: 'AI_GENERATED', label: 'AI 生成' },
    ],
  },

  // ═════════════ Phase 2.L 新增（SDK AdcreateCreatives 验证 — 70+ 字段交叉审计） ═════════════
  // — 免责声明 composite（金融 / 制药 / 健康等行业必填） —
  {
    name: 'disclaimer',
    label: '免责声明',
    sdkPath: 'ad.disclaimer',
    level, channel, apiVersion,
    type: 'composite',
    group: 'creative',
    helpText: '金融 / 制药 / 健康等垂直行业广告的合规免责声明。',
    subFields: [
      { name: 'disclaimer_type',         label: '类型',          sdkPath: 'disclaimer_type',         level, channel, apiVersion,
        type: 'select',
        options: [
          { value: 'NONE',                  label: '无' },
          { value: 'FINANCIAL_DISCLAIMER',  label: '金融' },
          { value: 'PHARMACEUTICAL_DISCLAIMER', label: '制药' },
          { value: 'HEALTH_DISCLAIMER',     label: '健康' },
        ] },
      { name: 'disclaimer_text',         label: '免责文案',      sdkPath: 'disclaimer_text',         level, channel, apiVersion, type: 'textarea' },
      { name: 'disclaimer_clickable_texts', label: '可点击文本',  sdkPath: 'disclaimer_clickable_texts', level, channel, apiVersion, type: 'tags' },
      { name: 'auto_disclaimer_types',   label: '自动免责类型',  sdkPath: 'auto_disclaimer_types',   level, channel, apiVersion, type: 'tags' },
    ],
  },

  // — 联系方式 — phone_region_code（与 phone_region_calling_code 不同） —
  {
    name: 'phone_region_code',
    label: '电话国家码',
    sdkPath: 'ad.phone_region_code',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    helpText: '与 phone_number 一起出现（与 phone_region_calling_code 区号不同）。',
    placeholder: 'CN / US / GB',
    dependsOn: { field: 'call_to_action', equals: 'CONTACT_US' },
  },

  // — TikTok Page —
  {
    name: 'tiktok_page_category',
    label: 'TikTok 主页类别',
    sdkPath: 'ad.tiktok_page_category',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'BUSINESS',    label: '商家' },
      { value: 'CREATOR',     label: '创作者' },
      { value: 'GAMING',      label: '游戏' },
      { value: 'EDUCATION',   label: '教育' },
      { value: 'OTHER',       label: '其它' },
    ],
  },

  // — Custom Product Page URL（cpp_url） —
  {
    name: 'cpp_url',
    label: '自定义产品页 URL',
    sdkPath: 'ad.cpp_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'cta',
    helpText: '为购物广告自定义的产品页面 URL。',
  },

  // — End Card CTA —
  {
    name: 'end_card_cta',
    label: '结束卡 CTA 文案',
    sdkPath: 'ad.end_card_cta',
    level, channel, apiVersion,
    type: 'text',
    group: 'creative',
    helpText: '视频结束时显示的 CTA 文案。',
  },

  // — Promotional Music Disabled —
  {
    name: 'promotional_music_disabled',
    label: '禁用推广音乐',
    sdkPath: 'ad.promotional_music_disabled',
    level, channel, apiVersion,
    type: 'switch',
    group: 'creative',
  },

  // — Dynamic Ads（DCO） —
  {
    name: 'dynamic_destination',
    label: '动态目的地',
    sdkPath: 'ad.dynamic_destination',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'DEFAULT',  label: '默认' },
      { value: 'STORE',    label: 'TikTok 店铺' },
      { value: 'WEBSITE',  label: '网站' },
      { value: 'APP',      label: '应用' },
    ],
  },
  {
    name: 'dynamic_format',
    label: '动态格式',
    sdkPath: 'ad.dynamic_format',
    level, channel, apiVersion,
    type: 'select',
    group: 'creative',
    options: [
      { value: 'DYNAMIC_CREATIVE', label: '动态创意' },
      { value: 'CREATIVE_BUNDLE',  label: '创意打包' },
    ],
  },
  {
    name: 'instant_product_page_used',
    label: '使用 Instant 产品页',
    sdkPath: 'ad.instant_product_page_used',
    level, channel, apiVersion,
    type: 'switch',
    group: 'creative',
  },

  // — Tracking 新增 —
  {
    name: 'tracking_offline_event_set_ids',
    label: '离线事件集（Ad 级）',
    sdkPath: 'ad.tracking_offline_event_set_ids',
    level, channel, apiVersion,
    type: 'multiselect',
    options: [],  // 由 platformResources offlineEventSets 派生
    group: 'tracking',
  },
  {
    name: 'tracking_message_event_set_id',
    label: '消息事件集 ID',
    sdkPath: 'ad.tracking_message_event_set_id',
    level, channel, apiVersion,
    type: 'text',
    group: 'tracking',
  },
  {
    name: 'video_view_tracking_url',
    label: '视频浏览跟踪 URL',
    sdkPath: 'ad.video_view_tracking_url',
    level, channel, apiVersion,
    type: 'url',
    group: 'tracking',
  },

  // — 内部 / 垂直行业（excludeFromCreate） —
  {
    name: 'vehicle_ids',
    label: '车型 ID（汽车广告）',
    sdkPath: 'ad.vehicle_ids',
    level, channel, apiVersion,
    type: 'tags',
    group: 'advanced',
    excludeFromCreate: true,
  },
];

export default fields;
