import { Check, MessageSquarePlus, Plus, SlidersHorizontal } from 'lucide-react'
import { useState } from 'react'
import useMarketingOpsStore from '@stores/marketingOpsStore'

const ReportPreferencePanel=()=>{
 const preferences=useMarketingOpsStore(s=>s.reportPreferences),add=useMarketingOpsStore(s=>s.addReportPreference),toggle=useMarketingOpsStore(s=>s.toggleReportPreference)
 const [open,setOpen]=useState(false),[notice,setNotice]=useState('')
 const submit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),scope=d.get('scope');add({title:d.get('title'),detail:d.get('detail'),scope,source:'报告反馈',enabled:true,createdAt:'刚刚'});setOpen(false);setNotice(scope==='仅本次报告'?'已记录为本次报告修改，不影响后续模板':`已保存为${scope}`)}
 return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary-50 text-primary-700"><SlidersHorizontal size={18}/></span><div><h3 className="font-bold">报告反馈与偏好</h3><p className="mt-1 text-xs text-neutral-500">区分一次性修改、模板偏好和品牌长期偏好，避免单次反馈污染长期规则</p></div></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><MessageSquarePlus size={14}/>添加报告反馈</button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{preferences.map(x=><label key={x.id} className="flex cursor-pointer items-start justify-between gap-3 rounded-xl bg-neutral-50 p-3"><span><span className="flex items-center gap-2"><strong className="text-sm">{x.title||x.label}</strong><em className="rounded-full bg-white px-2 py-0.5 text-[10px] not-italic text-primary-700">{x.scope||'品牌长期偏好'}</em></span><span className="mt-1 block text-xs leading-5 text-neutral-500">{x.detail}</span><span className="mt-1 block text-[10px] text-neutral-400">{x.source} · {x.createdAt||'历史反馈'}</span></span><input type="checkbox" checked={x.enabled} onChange={()=>toggle(x.id)} className="mt-1 h-4 w-4 accent-violet-600"/></label>)}</div>{notice&&<p className="mt-3 flex items-center gap-2 text-xs font-semibold text-success-700"><Check size={13}/>{notice}</p>}{open&&<div className="fixed inset-0 z-[9998] grid place-items-center bg-neutral-950/40 p-4" onMouseDown={()=>setOpen(false)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><h3 className="font-bold">记录报告反馈</h3><p className="mt-1 text-xs text-neutral-500">先确定影响范围，再保存反馈内容</p><label className="mt-4 block text-sm">影响范围<select name="scope" className="mt-1.5 w-full rounded-lg border bg-white px-3 py-2.5"><option>仅本次报告</option><option>当前报告模板</option><option>品牌长期偏好</option><option>行业模板候选</option></select></label><label className="mt-3 block text-sm">反馈名称<input name="title" required placeholder="例如：管理层摘要优先" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="mt-3 block text-sm">具体要求<textarea name="detail" required placeholder="描述应增加、减少或调整的内容" className="mt-1.5 min-h-24 w-full rounded-lg border px-3 py-2.5"/></label><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2 text-sm">取消</button><button className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white"><Plus size={14}/>保存反馈</button></div></form></div>}</section>
}
export default ReportPreferencePanel
