export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'AdsGo AI – Your 24/7 AI Ad Expert',
    category: 'Business Services > Marketing & Advertising',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 26, 2026 07:18 PM',
    image: 'https://picsum.photos/seed/adsgo/150/150',
    description: 'Turn $1 into $4 With AI Ads. The world\'s first AI ad agent that handles everything automatically. Setup in 5 minutes | Average ROI: 300%+ Create and launch campaigns on the go with AdsGo Mobile. Discover your best audience and ad strategy in minutes with AI Ads and Auto Optimization. Powerful campaigns that actually work — helping small',
    usps: ['AI Auto Management', '300%+ ROI', 'Mobile Campaigns', 'Audience Discovery', 'Auto Optimization'],
    assets: {
      others: [
        { id: 1, type: 'video', duration: '00:15', thumbnail: 'https://picsum.photos/seed/v1/150/150' },
        { id: 2, type: 'video', duration: '00:11', thumbnail: 'https://picsum.photos/seed/v2/150/150' },
        { id: 3, type: 'video', duration: '00:09', thumbnail: 'https://picsum.photos/seed/v3/150/150' },
        { id: 4, type: 'video', duration: '00:04', thumbnail: 'https://picsum.photos/seed/v4/150/150' }
      ]
    }
  },
  {
    id: 2,
    name: 'AI Marketing Analytics Suite - Premium Edition',
    category: 'Business Services > Marketing & Advertising',
    type: 'Unrecognized',
    source: 'Manual',
    updatedOn: 'Jan 26, 2026 07:15 PM',
    image: 'https://picsum.photos/seed/analytics/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 3,
    name: 'SIVEIS Cargo Liner for Dogs, Universal Nonslip Waterproof Pet Dog Back Seat Cover, Washable Car Boot Protector Mat ...',
    category: 'Pet Supplies > Pet Travel Accessories',
    type: 'Service',
    source: 'URL',
    updatedOn: 'Jan 26, 2026 07:12 PM',
    image: 'https://picsum.photos/seed/pet/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 4,
    name: '「STAY TRUE」刺繍ワッペン コーデュロイ切替裏フリースストライプシャツ',
    category: 'Apparel > Men\'s Clothing',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 21, 2026 06:54 PM',
    image: 'https://picsum.photos/seed/shirt/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 5,
    name: 'ComfyBrace Posture Corrector-Back Brace for Men and Women- Fully Adjustable Straightener for Mid, Upper Spine Sup...',
    category: 'Health > Medical Services',
    type: 'Physical Goods',
    source: 'Manual',
    updatedOn: 'Jan 21, 2026 06:53 PM',
    image: 'https://picsum.photos/seed/brace/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 6,
    name: 'PRISTINE Himalayan Tea/Inspired by Westin Hotel Reed Diffuser for Home | Fresh Bergamot/White Tea Room Fragrance...',
    category: 'Home > Cleaning Supplies',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 20, 2026 08:30 PM',
    image: 'https://picsum.photos/seed/tea/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 7,
    name: 'Smart Home Security Camera 4K Ultra HD with Night Vision',
    category: 'Electronics > Security',
    type: 'Physical Goods',
    source: 'Manual',
    updatedOn: 'Jan 19, 2026 11:45 AM',
    image: 'https://picsum.photos/seed/camera/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 8,
    name: 'Ergonomic Standing Desk with Memory Presets',
    category: 'Furniture > Office',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 18, 2026 04:20 PM',
    image: 'https://picsum.photos/seed/desk/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 9,
    name: 'Digital Marketing Course - Zero to Hero 2026',
    category: 'Education > Online Courses',
    type: 'Service',
    source: 'URL',
    updatedOn: 'Jan 17, 2026 09:10 AM',
    image: 'https://picsum.photos/seed/course/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 10,
    name: 'Wireless Noise Cancelling Headphones - Pro Series',
    category: 'Electronics > Audio',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 16, 2026 02:30 PM',
    image: 'https://picsum.photos/seed/audio/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 11,
    name: 'Organic Bamboo Bed Sheet Set - Queen Size',
    category: 'Home > Bedding',
    type: 'Physical Goods',
    source: 'Manual',
    updatedOn: 'Jan 15, 2026 10:15 AM',
    image: 'https://picsum.photos/seed/bed/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 12,
    name: 'Portable Power Bank 20000mAh with Quick Charge',
    category: 'Electronics > Accessories',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 14, 2026 08:45 PM',
    image: 'https://picsum.photos/seed/power/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 13,
    name: 'Yoga Mat with Alignment Lines - Non-Slip Eco-Friendly',
    category: 'Sports > Fitness',
    type: 'Physical Goods',
    source: 'Manual',
    updatedOn: 'Jan 13, 2026 07:20 AM',
    image: 'https://picsum.photos/seed/yoga/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 14,
    name: 'Gourmet Coffee Bean Selection - Arabica Blend',
    category: 'Food > Beverage',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 12, 2026 11:30 AM',
    image: 'https://picsum.photos/seed/coffee/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 15,
    name: 'Skin Care Radiance Serum with Vitamin C',
    category: 'Beauty > Skin Care',
    type: 'Physical Goods',
    source: 'URL',
    updatedOn: 'Jan 11, 2026 03:50 PM',
    image: 'https://picsum.photos/seed/skin/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 16,
    name: 'Subscription Box: Monthly Surprise Gadgets',
    category: 'Services > Subscriptions',
    type: 'Service',
    source: 'Shopify',
    updatedOn: 'Jan 10, 2026 10:00 AM',
    image: 'https://picsum.photos/seed/sub/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 17,
    name: 'Mechanical Gaming Keyboard with RGB Backlight',
    category: 'Electronics > Computing',
    type: 'Physical Goods',
    source: 'Manual',
    updatedOn: 'Jan 09, 2026 06:15 PM',
    image: 'https://picsum.photos/seed/kb/150/150',
    description: '',
    usps: [],
    assets: {}
  },
  {
    id: 18,
    name: 'UV Toothbrush Sanitizer and Holder',
    category: 'Home > Personal Care',
    type: 'Physical Goods',
    source: 'Shopify',
    updatedOn: 'Jan 08, 2026 09:40 AM',
    image: 'https://picsum.photos/seed/brush/150/150',
    description: '',
    usps: [],
    assets: {}
  }
];
