import { Check, EyeOff, FlaskConical, GitBranch, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import useMarketingOpsStore from '@stores/marketingOpsStore'
import useBrandStore from '@stores/brandStore'

const IndustryCandidatesPanel=()=>{
 const items=useMarketingOpsStore(s=>s.industryCandidates)
 const review=useMarketingOpsStore(s=>s.reviewIndustryCandidate)
 const publishCandidate=useBrandStore(s=>s.publishIndustryCandidate)
 const [selected,setSelected]=useState(null)
 const [targetType,setTargetType]=useState('skill')
 const [notice,setNotice]=useState('')
 const publish=x=>{const result=publishCandidate({title:x.title,summary:x.summary,targetType});if(!result)return;review(x.id,'已升级');setSelected(null);setNotice(result.type==='skill'?`已创建行业 Skill ${result.version}，目标行业品牌已收到升级提醒`:'已发布为 L2 行业公共知识，可进入分发中心')}
 return <div className="mx-auto max-w-6xl space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 text-amber-700"><GitBranch size={19}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-amber-700">Cross-brand Learning</p><h2 className="mt-1 text-xl font-bold">多品牌经验如何成为行业能力</h2><p className="mt-1 text-sm text-neutral-500">只聚合匿名结果、共同条件与效果信号，不读取或迁移品牌私有规则。</p></div></div></section>{notice&&<div className="rounded-xl border border-success-200 bg-success-50 px-4 py-3 text-xs font-semibold text-success-700">{notice}</div>}<div className="grid gap-4 md:grid-cols-2">{items.map(x=><article key={x.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><Sparkles size={18} className="text-amber-600"/><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${x.status==='待审核'?'bg-amber-50 text-amber-700':'bg-success-50 text-success-700'}`}>{x.status}</span></div><h3 className="mt-4 font-bold">{x.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{x.summary}</p><div className="mt-4 grid grid-cols-3 gap-2">{[['匿名品牌',x.id===1?'4':'7'],['动作证据',x.id===1?'11':'23'],['验证有效',x.id===1?'8':'17']].map(([a,b])=><div key={a} className="rounded-xl bg-neutral-50 p-3"><p className="text-lg font-bold">{b}</p><p className="text-[10px] text-neutral-400">{a}</p></div>)}</div><div className="mt-3 flex items-center gap-2 rounded-xl bg-neutral-50 p-3 text-xs text-neutral-600"><EyeOff size={14}/>证据已移除品牌名、预算和客户私有规则</div>{x.status==='待审核'&&<div className="mt-4 flex gap-2 border-t pt-4"><button onClick={()=>setSelected(x)} className="inline-flex items-center gap-1 rounded-lg bg-neutral-900 px-3 py-2 text-xs text-white"><Check size={13}/>审核并升级</button><button onClick={()=>review(x.id,'已忽略')} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><X size={13}/>暂不采用</button></div>}</article>)}</div>
 {selected&&<div className="fixed inset-0 z-[9999] grid place-items-center bg-neutral-950/50 p-4" onMouseDown={()=>setSelected(null)}><div onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start gap-3"><FlaskConical size={19} className="text-amber-700"/><div><h3 className="font-bold">将共性经验升级为行业能力</h3><p className="mt-1 text-xs text-neutral-500">{selected.title}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2">{[['skill','生成 Skill 新版本'],['knowledge','发布为 L2 知识']].map(([id,label])=><button key={id} onClick={()=>setTargetType(id)} className={`rounded-xl border p-3 text-xs font-bold ${targetType===id?'border-cyan-500 bg-cyan-50 text-cyan-800':''}`}>{label}</button>)}</div><div className="mt-4 space-y-2">{[['当前规则','低于目标时识别低效预算'],['候选新增','促销阶段和高意向流量增加保护窗口'],['适用条件','运动服饰 DTC · 冷启动或促销阶段'],['不适用条件','数据不足、学习期不稳定或品牌明确禁止'],['发布影响',targetType==='skill'?'创建行业 Skill 新版本并生成品牌升级提醒':'进入公共知识库并允许平台分发']].map(([a,b])=><div key={a} className="rounded-xl bg-neutral-50 p-3"><p className="text-[10px] text-neutral-400">{a}</p><p className="mt-1 text-xs font-semibold">{b}</p></div>)}</div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setSelected(null)} className="rounded-xl border px-4 py-2.5 text-sm">取消</button><button onClick={()=>publish(selected)} className="rounded-xl bg-neutral-950 px-5 py-2.5 text-sm font-bold text-white">确认发布</button></div></div></div>}
 </div>
}
export default IndustryCandidatesPanel
