import { useState } from 'react'
import { ExternalLink, Package, Plus, Search, Sparkles, Star, Trash2, X } from 'lucide-react'
import useMarketingOpsStore from '@stores/marketingOpsStore'

const ProductLibraryPage=()=>{
  const products=useMarketingOpsStore(s=>s.products),add=useMarketingOpsStore(s=>s.addProduct),update=useMarketingOpsStore(s=>s.updateProduct),remove=useMarketingOpsStore(s=>s.removeProduct)
  const [query,setQuery]=useState(''),[modal,setModal]=useState(false),[analyzing,setAnalyzing]=useState(false)
  const list=products.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()))
  const submit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);add({name:d.get('name'),category:d.get('category'),price:d.get('price'),audience:d.get('audience'),markets:d.get('markets').split(/[,，]/).filter(Boolean),sellingPoints:d.get('sellingPoints').split(/[,，]/).filter(Boolean)});setModal(false)}
  return <div className="space-y-5"><section className="flex flex-col gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">产品库</h2><p className="mt-1 text-sm text-neutral-500">独立管理品牌销售对象，并供素材生成、策略、Luna 和报告选择使用。</p></div><button onClick={()=>setModal(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-neutral-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={15}/>添加产品</button></section><div className="relative max-w-sm"><Search className="absolute left-3 top-2.5 text-neutral-400" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索产品" className="w-full rounded-lg border bg-white py-2 pl-9 pr-3 text-sm"/></div><section className="grid gap-4 lg:grid-cols-2">{list.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-xl bg-primary-50 text-primary-600"><Package size={23}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{item.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${item.status==='主推'?'bg-warning-50 text-warning-700':'bg-neutral-100 text-neutral-600'}`}>{item.status}</span></div><p className="mt-1 text-xs text-neutral-500">{item.category} · {item.price} · {item.source}</p></div><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-neutral-400 hover:bg-danger-50 hover:text-danger-600"><Trash2 size={15}/></button></div><div className="mt-4 grid gap-3 rounded-xl bg-neutral-50 p-4 text-xs sm:grid-cols-2"><div><p className="text-neutral-400">目标市场</p><p className="mt-1">{item.markets.join('、')}</p></div><div><p className="text-neutral-400">目标受众</p><p className="mt-1">{item.audience}</p></div></div><div className="mt-3 flex flex-wrap gap-2">{item.sellingPoints.map(x=><span key={x} className="rounded-full bg-primary-50 px-2.5 py-1 text-xs text-primary-700">{x}</span>)}</div><div className="mt-4 flex flex-wrap gap-2 border-t pt-4"><button onClick={()=>update(item.id,{status:item.status==='主推'?'在售':'主推'})} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><Star size={13}/>{item.status==='主推'?'取消主推':'设为主推'}</button><button className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><Sparkles size={13}/>交给 Luna 分析</button><button className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><ExternalLink size={13}/>用于素材生成</button></div></article>)}</section>
  {modal&&<div className="fixed inset-0 z-[9998] grid place-items-center bg-neutral-950/40 p-4" onMouseDown={()=>setModal(false)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex justify-between border-b p-5"><div><h3 className="font-bold">添加产品</h3><p className="mt-1 text-xs text-neutral-500">支持手动填写，链接分析为前端模拟</p></div><button type="button" onClick={()=>setModal(false)}><X size={18}/></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="sm:col-span-2 text-sm">商品链接（可选）<div className="mt-1.5 flex gap-2"><input name="url" placeholder="https://..." className="min-w-0 flex-1 rounded-lg border px-3 py-2.5"/><button type="button" onClick={()=>{setAnalyzing(true);setTimeout(()=>setAnalyzing(false),800)}} className="rounded-lg border px-3 text-xs">{analyzing?'分析中…':'分析链接'}</button></div></label><label className="sm:col-span-2 text-sm">产品名称<input required name="name" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="text-sm">分类<input name="category" defaultValue="运动服饰" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="text-sm">价格<input name="price" placeholder="$68" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="sm:col-span-2 text-sm">目标受众<input name="audience" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="sm:col-span-2 text-sm">市场<input name="markets" placeholder="美国，加拿大" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label><label className="sm:col-span-2 text-sm">核心卖点<input name="sellingPoints" placeholder="高腰支撑，四向弹力，不透肤" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button type="button" onClick={()=>setModal(false)} className="rounded-lg border px-4 py-2 text-sm">取消</button><button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">保存产品</button></footer></form></div>}</div>
}
export default ProductLibraryPage
