import { ArrowDown, ArrowUp, Check, Database, FlaskConical, GripVertical, Plus, ShieldCheck, Sparkles, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'

const base = {
  name: '电商预算与素材健康检查', industry: '电商', version: 'v1.0', status: 'draft', iconKey: 'budget',
  description: '识别低效预算与素材疲劳，并生成分场景、可验证的运营建议。',
  problem: 'ROAS 下滑时判断问题来自预算、素材还是经营阶段，并给出可确认动作。',
  scenarios: '日常账户检查；ROAS/CPA 预警；优化师主动诊断', exclusions: '数据不足；学习期未稳定；品牌禁止自动建议',
  triggers: ['主动调用', '定时任务', '预警触发'], requiredDatasets: ['广告账户数据', '素材表现数据'], requiredViews: ['Campaign 效率拆解', '素材疲劳监控'],
  knowledgeRefs: ['L2 广告投放基准与最佳实践', 'L3 竞品与市场动态'],
  steps: ['读取近 7 日与前 7 日指标', '对比行业基准与品牌目标', '检查学习期、促销期和品牌保护规则', '区分冷启动与再营销场景', '生成预算、素材与观察建议'],
  output: '结构化诊断 + 预算或素材动作 + 观察窗口', confirmationPolicy: '预算、关停和发布必须由有权限成员确认', verificationPolicy: '执行后 48–72 小时验证 ROAS、CPA、CTR 与购买量',
}

const Field = ({label, children, hint}) => <label className="block text-xs font-semibold text-slate-700">{label}{children}{hint&&<span className="mt-1 block font-normal text-slate-400">{hint}</span>}</label>
const inputClass = 'mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-cyan-500'

const StructuredSkillEditor = ({skill,onClose,onSave}) => {
  const [form,setForm]=useState({...base,...skill,steps:skill?.steps||base.steps})
  const [stage,setStage]=useState(0)
  const [testing,setTesting]=useState(false)
  const [tested,setTested]=useState(false)
  const [newStep,setNewStep]=useState('')
  const stages=['问题与场景','数据与知识','方法步骤','输出与权限','验证并发布']
  const readiness=useMemo(()=>[form.name,form.problem,form.requiredDatasets?.length,form.steps?.length,form.output,form.verificationPolicy].filter(Boolean).length,[form])
  const list=(key)=>(form[key]||[]).join('、')
  const setList=(key,value)=>setForm({...form,[key]:value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean)})
  const move=(index,delta)=>{const next=[...form.steps],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setForm({...form,steps:next})}
  const run=()=>{setTesting(true);setTimeout(()=>{setTesting(false);setTested(true);setStage(4)},700)}
  const save=(published=false)=>onSave({...form,status:published?'published':form.status,enabled:published,version:form.version||'v1.0'})
  return <div className="fixed inset-0 z-[9998] flex items-center justify-center bg-slate-950/60 p-3 backdrop-blur-sm" onMouseDown={onClose}><div onMouseDown={e=>e.stopPropagation()} className="flex max-h-[94vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-[#f7f8fa] shadow-2xl">
    <header className="flex items-start justify-between border-b bg-white p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-700">Skill Factory</p><h2 className="mt-1 text-xl font-bold">{skill?'编辑结构化 Skill':'把优化师方法沉淀为 Skill'}</h2><p className="mt-1 text-xs text-slate-500">不是填写一段 Prompt，而是定义可调用、可确认、可验证的标准工作方法。</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-lg hover:bg-slate-100"><X size={18}/></button></header>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[230px_1fr]">
      <aside className="border-b bg-slate-950 p-4 text-white lg:border-b-0 lg:border-r"><div className="flex gap-2 overflow-x-auto lg:block lg:space-y-1">{stages.map((x,i)=><button key={x} onClick={()=>setStage(i)} className={`flex min-h-11 shrink-0 items-center gap-3 rounded-xl px-3 text-left text-xs font-semibold lg:w-full ${stage===i?'bg-cyan-400 text-slate-950':'text-slate-300 hover:bg-slate-900'}`}><span className="grid h-6 w-6 place-items-center rounded-full border border-current text-[10px]">{i+1}</span>{x}</button>)}</div><div className="mt-5 hidden rounded-xl border border-slate-800 p-3 lg:block"><p className="text-[10px] text-slate-400">定义完整度</p><p className="mt-2 text-2xl font-bold text-cyan-300">{Math.round(readiness/6*100)}%</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-cyan-400" style={{width:`${readiness/6*100}%`}}/></div></div></aside>
      <main className="min-h-0 overflow-y-auto p-5 lg:p-7">
        {stage===0&&<div className="mx-auto max-w-3xl space-y-5"><div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-cyan-900"><Sparkles size={16} className="mr-2 inline"/><strong>已模拟提取资深优化师方法：</strong>系统预填了问题、场景与步骤，请由平台管理员确认后发布。</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Skill 名称"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={inputClass}/></Field><Field label="适用行业"><select value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})} className={inputClass}>{['电商','应用','游戏','金融','教育','全行业'].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="解决的问题"><textarea value={form.problem} onChange={e=>setForm({...form,problem:e.target.value})} className={`${inputClass} min-h-24`}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="典型使用场景"><textarea value={form.scenarios} onChange={e=>setForm({...form,scenarios:e.target.value})} className={`${inputClass} min-h-24`}/></Field><Field label="不适用场景"><textarea value={form.exclusions} onChange={e=>setForm({...form,exclusions:e.target.value})} className={`${inputClass} min-h-24`}/></Field></div></div>}
        {stage===1&&<div className="mx-auto max-w-3xl space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="触发方式" hint="使用顿号分隔"><input value={list('triggers')} onChange={e=>setList('triggers',e.target.value)} className={inputClass}/></Field><Field label="所需数据集"><input value={list('requiredDatasets')} onChange={e=>setList('requiredDatasets',e.target.value)} className={inputClass}/></Field><Field label="所需数据视图"><input value={list('requiredViews')} onChange={e=>setList('requiredViews',e.target.value)} className={inputClass}/></Field><Field label="引用公共知识"><input value={list('knowledgeRefs')} onChange={e=>setList('knowledgeRefs',e.target.value)} className={inputClass}/></Field></div><div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Database size={17} className="text-cyan-700"/><h3 className="text-sm font-bold">运行前数据条件</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{['广告指标可用','品牌目标已配置','允许读取 L4 知识'].map(x=><label key={x} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-semibold"><input type="checkbox" defaultChecked className="accent-cyan-600"/>{x}</label>)}</div></div></div>}
        {stage===2&&<div className="mx-auto max-w-3xl"><h3 className="text-sm font-bold">判断步骤</h3><p className="mt-1 text-xs text-slate-500">顺序代表 Luna 执行该方法时的推理与检查顺序。</p><div className="mt-4 space-y-2">{form.steps.map((x,i)=><div key={`${x}-${i}`} className="flex items-center gap-2 rounded-xl border bg-white p-3"><GripVertical size={15} className="text-slate-300"/><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-slate-950 text-[10px] font-bold text-white">{i+1}</span><input value={x} onChange={e=>setForm({...form,steps:form.steps.map((v,j)=>j===i?e.target.value:v)})} className="min-w-0 flex-1 bg-transparent text-sm outline-none"/><button onClick={()=>move(i,-1)} className="p-2 text-slate-400"><ArrowUp size={14}/></button><button onClick={()=>move(i,1)} className="p-2 text-slate-400"><ArrowDown size={14}/></button><button onClick={()=>setForm({...form,steps:form.steps.filter((_,j)=>j!==i)})} className="p-2 text-rose-500"><Trash2 size={14}/></button></div>)}</div><div className="mt-3 flex gap-2"><input value={newStep} onChange={e=>setNewStep(e.target.value)} placeholder="新增一个判断步骤" className={inputClass}/><button onClick={()=>{if(newStep.trim()){setForm({...form,steps:[...form.steps,newStep.trim()]});setNewStep('')}}} className="mt-1.5 grid h-11 w-12 place-items-center rounded-xl bg-slate-950 text-white"><Plus size={16}/></button></div></div>}
        {stage===3&&<div className="mx-auto max-w-3xl space-y-5"><Field label="标准输出"><textarea value={form.output} onChange={e=>setForm({...form,output:e.target.value})} className={`${inputClass} min-h-24`}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="人工确认规则"><textarea value={form.confirmationPolicy} onChange={e=>setForm({...form,confirmationPolicy:e.target.value})} className={`${inputClass} min-h-28`}/></Field><Field label="效果验证规则"><textarea value={form.verificationPolicy} onChange={e=>setForm({...form,verificationPolicy:e.target.value})} className={`${inputClass} min-h-28`}/></Field></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldCheck size={15} className="mr-2 inline"/>预算、关停和发布等高影响输出只能生成待确认动作，不会由 Luna 直接执行。</div></div>}
        {stage===4&&<div className="mx-auto max-w-3xl space-y-5"><section className={`rounded-2xl border p-5 ${tested?'border-emerald-200 bg-emerald-50':'bg-white'}`}><div className="flex items-start gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tested?'bg-emerald-600 text-white':'bg-slate-100 text-slate-500'}`}>{tested?<Check size={18}/>:<FlaskConical size={18}/>}</span><div><h3 className="font-bold">{tested?'试运行通过':'发布前试运行'}</h3><p className="mt-1 text-xs text-slate-500">使用 LumaFit 示例数据验证输入、品牌覆盖、输出与确认规则。</p></div></div>{tested&&<div className="mt-4 grid gap-3 sm:grid-cols-3">{[['输入','ROAS 1.82 · 频次 4.7'],['品牌覆盖','促销期保护再营销'],['输出','冷启动 -15% · 再营销观察']].map(([a,b])=><div key={a} className="rounded-xl bg-white p-3"><p className="text-[10px] text-slate-400">{a}</p><p className="mt-1 text-xs font-bold">{b}</p></div>)}</div>}<button onClick={run} disabled={testing} className="mt-4 rounded-xl border bg-white px-4 py-2.5 text-xs font-bold">{testing?'正在执行 5 个判断步骤…':tested?'重新试运行':'开始试运行'}</button></section><div className="grid gap-4 sm:grid-cols-3"><Field label="版本"><input value={form.version} onChange={e=>setForm({...form,version:e.target.value})} className={inputClass}/></Field><div className="sm:col-span-2 rounded-xl border bg-white p-4 text-xs text-slate-500"><strong className="text-slate-800">发布后：</strong>Skill 将进入平台分发中心，可按行业或指定品牌分发；品牌仍需完成适配后才会生效。</div></div></div>}
      </main>
    </div>
    <footer className="flex items-center justify-between gap-3 border-t bg-white p-4"><button onClick={()=>save(false)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">保存草稿</button><div className="flex gap-2"><button disabled={stage===0} onClick={()=>setStage(x=>x-1)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold disabled:opacity-30">上一步</button>{stage<4?<button onClick={()=>setStage(x=>x+1)} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white">下一步</button>:<button disabled={!tested} onClick={()=>save(true)} className="rounded-xl bg-cyan-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-30">发布 {form.version}</button>}</div></footer>
  </div></div>
}

export default StructuredSkillEditor
