import { useMemo, useState } from 'react'
import { AlertTriangle, Bell, CheckCircle2, Clock3, Search, Trash2, UserRoundCheck, X } from 'lucide-react'
import useMarketingOpsStore from '@stores/marketingOpsStore'

const NotificationsPage = () => {
  const notifications = useMarketingOpsStore(state => state.notifications)
  const markNotificationRead = useMarketingOpsStore(state => state.markNotificationRead)
  const markAllNotificationsRead = useMarketingOpsStore(state => state.markAllNotificationsRead)
  const deleteNotification = useMarketingOpsStore(state => state.deleteNotification)
  const clearReadNotifications = useMarketingOpsStore(state => state.clearReadNotifications)
  const resolveAlertWithAction = useMarketingOpsStore(state => state.resolveAlertWithAction)
  const [filter, setFilter] = useState('all')
  const [query, setQuery] = useState('')
  const [handling, setHandling] = useState(null)
  const list = useMemo(() => notifications.filter(item => (filter === 'all' || (filter === 'unread' ? !item.read : item.category === filter)) && `${item.title}${item.detail}`.toLowerCase().includes(query.toLowerCase())), [notifications, filter, query])
  return <div className="space-y-5">
    <section className="flex flex-col gap-4 rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold">全部通知</h2><p className="mt-1 text-sm text-neutral-500">集中查看预警、任务、报告与 Luna 操作消息</p></div><div className="flex gap-2"><button onClick={markAllNotificationsRead} className="rounded-lg border px-3 py-2 text-xs font-semibold">全部已读</button><button onClick={clearReadNotifications} className="rounded-lg border px-3 py-2 text-xs font-semibold text-danger-600">清理已读</button></div></section>
    <section className="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1">{[['all','全部'],['unread','未读'],['alert','预警'],['system','系统']].map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${filter===id?'bg-neutral-900 text-white':'text-neutral-500 hover:bg-neutral-100'}`}>{label}</button>)}</div><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-neutral-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索通知" className="rounded-lg border py-2 pl-8 pr-3 text-sm"/></div></div>
      <div className="divide-y">{list.map(item=><div key={item.id} className={`flex gap-4 p-5 ${item.read?'':'bg-primary-50/30'}`}><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.category==='alert'?'bg-danger-50 text-danger-600':'bg-primary-50 text-primary-600'}`}>{item.read?<CheckCircle2 size={18}/>:item.category==='alert'?<AlertTriangle size={18}/>:<Bell size={18}/>}</div><button onClick={()=>markNotificationRead(item.id)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold">{item.title}</h3>{!item.read&&<span className="h-2 w-2 rounded-full bg-danger-500"/>}{item.category==='alert'&&<span className="rounded-full bg-neutral-100 px-2 py-0.5 text-[10px]">{item.status || '待处理'} · {item.assignee || '未指派'}</span>}</div><p className="mt-1 text-sm text-neutral-500">{item.detail}</p><p className="mt-2 flex items-center gap-1 text-xs text-neutral-400"><Clock3 size={12}/>{item.time}</p></button>{item.category==='alert'&&<button onClick={()=>setHandling(item)} className="h-9 rounded-lg border px-3 text-xs font-semibold text-neutral-600 hover:bg-neutral-50">处理</button>}<button onClick={()=>deleteNotification(item.id)} className="h-9 w-9 rounded-lg text-neutral-400 hover:bg-danger-50 hover:text-danger-600"><Trash2 size={15} className="mx-auto"/></button></div>)}</div>
      {list.length===0&&<p className="py-16 text-center text-sm text-neutral-400">没有匹配的通知</p>}
    </section>
    {handling&&<div className="fixed inset-0 z-[2000] grid place-items-center bg-neutral-950/40 p-4" onMouseDown={()=>setHandling(null)}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);resolveAlertWithAction(handling.id,{status:data.get('status'),assignee:data.get('assignee'),resolution:data.get('resolution')});setHandling(null)}} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex justify-between border-b p-5"><div><h3 className="font-bold">处理预警</h3><p className="mt-1 text-xs text-neutral-500">{handling.title}</p></div><button type="button" onClick={()=>setHandling(null)}><X size={18}/></button></div><div className="space-y-4 p-5"><label className="block text-sm">指派给<select name="assignee" defaultValue={handling.assignee || '优化师'} className="mt-1.5 w-full rounded-lg border bg-white px-3 py-2.5"><option>优化师</option><option>Mia Chen</option><option>Alex Wu</option></select></label><label className="block text-sm">处理状态<select name="status" defaultValue={handling.status || '处理中'} className="mt-1.5 w-full rounded-lg border bg-white px-3 py-2.5"><option>待处理</option><option>处理中</option><option>已解决</option><option>已忽略</option></select></label><label className="block text-sm">处理动作<textarea required name="resolution" defaultValue={handling.resolution || ''} className="mt-1.5 min-h-28 w-full rounded-lg border px-3 py-2.5" placeholder="例如：将目标广告组预算下调 15%，执行后观察 48 小时"/></label><p className="rounded-lg bg-primary-50 px-3 py-2 text-xs text-primary-700">保存后会同步生成运营动作；标记“已解决”的动作将自动进入效果验证。</p></div><div className="flex justify-end gap-2 border-t p-4"><button type="button" onClick={()=>setHandling(null)} className="rounded-lg border px-4 py-2 text-sm">取消</button><button className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white"><UserRoundCheck size={15}/>保存并进入动作链</button></div></form></div>}
  </div>
}
export default NotificationsPage
